# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5199e21e72245f58916f90420cb4822acca7f87956e633852c5b3326b23ea88c
# To regenerate: alef generate
# To verify freshness: alef verify

import builtins

from . import options

from typing import Any, AsyncIterator, Literal, TypedDict

class AssistantMessage:
    content: AssistantContent | None
    name: str | None
    tool_calls: list[ToolCall] | None
    refusal: str | None
    function_call: FunctionCall | None
    reasoning_content: str | None
    def __init__(
        self,
        content: AssistantContent | None = None,
        name: str | None = None,
        tool_calls: list[ToolCall] | None = None,
        refusal: str | None = None,
        function_call: FunctionCall | None = None,
        reasoning_content: str | None = None,
    ) -> None: ...
    def text(self) -> str | None: ...
    def refusal_text(self) -> str | None: ...
    def reasoning_text(self) -> str | None: ...
    def output_images(self) -> list[ImageUrl]: ...
    def output_audio(self) -> list[AudioContent]: ...
    @staticmethod
    def from_json(json_str: str) -> AssistantMessage: ...

class AudioContent:
    data: str
    format: str
    def __init__(
        self,
        data: str = ...,
        format: str = ...,  # noqa: A002
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> AudioContent: ...

class AuthConfig:
    auth_type: AuthType
    env_var: str | None
    def __init__(
        self,
        type: AuthType,  # noqa: A002
        env_var: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> AuthConfig: ...

class BatchListQuery:
    limit: int | None
    after: str | None
    def __init__(self, limit: int | None = None, after: str | None = None) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> BatchListQuery: ...

class BatchListResponse:
    object: str
    data: list[BatchObject]
    has_more: bool | None
    first_id: str | None
    last_id: str | None
    def __init__(
        self,
        object: str = ...,  # noqa: A002
        data: list[BatchObject] = ...,
        has_more: bool | None = None,
        first_id: str | None = None,
        last_id: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> BatchListResponse: ...

class BatchObject:
    id: str
    object: str
    endpoint: str
    input_file_id: str
    completion_window: str
    status: BatchStatus
    output_file_id: str | None
    error_file_id: str | None
    created_at: int
    completed_at: int | None
    failed_at: int | None
    expired_at: int | None
    request_counts: BatchRequestCounts | None
    metadata: str | None
    def __init__(
        self,
        id: str = ...,  # noqa: A002
        object: str = ...,  # noqa: A002
        endpoint: str = ...,
        input_file_id: str = ...,
        completion_window: str = ...,
        status: BatchStatus = ...,
        created_at: int = ...,
        output_file_id: str | None = None,
        error_file_id: str | None = None,
        completed_at: int | None = None,
        failed_at: int | None = None,
        expired_at: int | None = None,
        request_counts: BatchRequestCounts | None = None,
        metadata: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> BatchObject: ...

class BatchRequestCounts:
    total: int
    completed: int
    failed: int
    def __init__(self, total: int = ..., completed: int = ..., failed: int = ...) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> BatchRequestCounts: ...

class BedrockConfig:
    region: str | None
    cross_region_prefix: str | None
    access_key_id: str | None
    secret_access_key: str | None
    session_token: str | None
    def __init__(
        self,
        region: str | None = None,
        cross_region_prefix: str | None = None,
        access_key_id: str | None = None,
        secret_access_key: str | None = None,
        session_token: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> BedrockConfig: ...

class BudgetConfig:
    global_limit: float | None
    model_limits: dict[str, float]
    enforcement: Enforcement
    def __init__(
        self,
        model_limits: dict[str, float] = ...,
        enforcement: Enforcement = ...,
        global_limit: float | None = None,
    ) -> None: ...
    @staticmethod
    def default() -> BudgetConfig: ...
    @staticmethod
    def from_json(json_str: str) -> BudgetConfig: ...

class CacheConfig:
    max_entries: int
    ttl: int | None
    backend: CacheBackend
    def __init__(
        self,
        max_entries: int = ...,
        ttl: int | None = None,
        backend: CacheBackend = ...,
    ) -> None: ...
    @staticmethod
    def default() -> CacheConfig: ...
    @staticmethod
    def from_json(json_str: str) -> CacheConfig: ...

class CatalogRefreshConfig:
    enabled: bool
    source_url: str
    ttl_seconds: int
    cache_path: str | None
    def __init__(
        self,
        enabled: bool = ...,
        source_url: str = ...,
        ttl_seconds: int = ...,
        cache_path: str | None = None,
    ) -> None: ...
    @staticmethod
    def default() -> CatalogRefreshConfig: ...
    @staticmethod
    def from_json(json_str: str) -> CatalogRefreshConfig: ...

class ChatCompletionChunk:
    id: str
    object: str
    created: int
    model: str
    choices: list[StreamChoice]
    usage: Usage | None
    system_fingerprint: str | None
    service_tier: str | None
    def __init__(
        self,
        id: str = ...,  # noqa: A002
        object: str = ...,  # noqa: A002
        created: int = ...,
        model: str = ...,
        choices: list[StreamChoice] = ...,
        usage: Usage | None = None,
        system_fingerprint: str | None = None,
        service_tier: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ChatCompletionChunk: ...

class ChatCompletionRequest:
    model: str
    messages: list[Message]
    temperature: float | None
    top_p: float | None
    n: int | None
    stream: bool | None
    stop: StopSequence | None
    max_tokens: int | None
    presence_penalty: float | None
    frequency_penalty: float | None
    logit_bias: dict[str, float] | None
    user: str | None
    tools: list[ChatCompletionTool] | None
    tool_choice: ToolChoice | None
    parallel_tool_calls: bool | None
    response_format: ResponseFormat | None
    stream_options: StreamOptions | None
    seed: int | None
    reasoning_effort: ReasoningEffort | None
    modalities: list[Modality] | None
    logprobs: bool | None
    top_logprobs: int | None
    max_completion_tokens: int | None
    service_tier: str | None
    store: bool | None
    metadata: dict[str, str] | None
    prediction: str | None
    audio: str | None
    web_search_options: str | None
    extra_body: str | None
    def __init__(
        self,
        model: str = ...,
        messages: list[Message] = ...,
        temperature: float | None = None,
        top_p: float | None = None,
        n: int | None = None,
        stream: bool | None = None,
        stop: StopSequence | None = None,
        max_tokens: int | None = None,
        presence_penalty: float | None = None,
        frequency_penalty: float | None = None,
        logit_bias: dict[str, float] | None = None,
        user: str | None = None,
        tools: list[ChatCompletionTool] | None = None,
        tool_choice: ToolChoice | None = None,
        parallel_tool_calls: bool | None = None,
        response_format: ResponseFormat | None = None,
        stream_options: StreamOptions | None = None,
        seed: int | None = None,
        reasoning_effort: ReasoningEffort | None = None,
        modalities: list[Modality] | None = None,
        logprobs: bool | None = None,
        top_logprobs: int | None = None,
        max_completion_tokens: int | None = None,
        service_tier: str | None = None,
        store: bool | None = None,
        metadata: dict[str, str] | None = None,
        prediction: str | None = None,
        audio: str | None = None,
        web_search_options: str | None = None,
        extra_body: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ChatCompletionRequest: ...

class ChatCompletionResponse:
    id: str
    object: str
    created: int
    model: str
    choices: list[Choice]
    usage: Usage | None
    system_fingerprint: str | None
    service_tier: str | None
    def __init__(
        self,
        id: str = ...,  # noqa: A002
        object: str = ...,  # noqa: A002
        created: int = ...,
        model: str = ...,
        choices: list[Choice] = ...,
        usage: Usage | None = None,
        system_fingerprint: str | None = None,
        service_tier: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ChatCompletionResponse: ...

class ChatCompletionTool:
    tool_type: ToolType
    function: FunctionDefinition
    def __init__(
        self,
        type: ToolType,  # noqa: A002
        function: FunctionDefinition,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ChatCompletionTool: ...

class Choice:
    index: int
    message: AssistantMessage
    finish_reason: FinishReason | None
    logprobs: str | None
    def __init__(
        self,
        index: int = ...,
        message: AssistantMessage | None = None,
        finish_reason: FinishReason | None = None,
        logprobs: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> Choice: ...

class CreateBatchRequest:
    input_file_id: str
    endpoint: str
    completion_window: str
    metadata: str | None
    def __init__(
        self,
        input_file_id: str = ...,
        endpoint: str = ...,
        completion_window: str = ...,
        metadata: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CreateBatchRequest: ...

class CreateFileRequest:
    file: str
    purpose: FilePurpose
    filename: str | None
    def __init__(
        self,
        file: str = ...,
        purpose: FilePurpose = ...,
        filename: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CreateFileRequest: ...

class CreateImageRequest:
    prompt: str
    model: str | None
    n: int | None
    size: str | None
    quality: str | None
    style: str | None
    response_format: str | None
    user: str | None
    def __init__(
        self,
        prompt: str = ...,
        model: str | None = None,
        n: int | None = None,
        size: str | None = None,
        quality: str | None = None,
        style: str | None = None,
        response_format: str | None = None,
        user: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CreateImageRequest: ...

class CreateResponseRequest:
    model: str
    input: str
    instructions: str | None
    tools: list[ResponseTool] | None
    temperature: float | None
    max_output_tokens: int | None
    metadata: str | None
    extra_body: str | None
    stream: bool | None
    def __init__(
        self,
        model: str = ...,
        input: str = ...,  # noqa: A002
        instructions: str | None = None,
        tools: list[ResponseTool] | None = None,
        temperature: float | None = None,
        max_output_tokens: int | None = None,
        metadata: str | None = None,
        extra_body: str | None = None,
        stream: bool | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CreateResponseRequest: ...

class CreateSpeechRequest:
    model: str
    input: str
    voice: str
    response_format: str | None
    speed: float | None
    def __init__(
        self,
        model: str = ...,
        input: str = ...,  # noqa: A002
        voice: str = ...,
        response_format: str | None = None,
        speed: float | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CreateSpeechRequest: ...

class CreateTranscriptionRequest:
    model: str
    file: str
    language: str | None
    prompt: str | None
    response_format: str | None
    temperature: float | None
    def __init__(
        self,
        model: str = ...,
        file: str = ...,
        language: str | None = None,
        prompt: str | None = None,
        response_format: str | None = None,
        temperature: float | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CreateTranscriptionRequest: ...

class CustomProviderConfig:
    name: str
    base_url: str
    auth_header: AuthHeaderFormat
    model_prefixes: list[str]
    def __init__(
        self,
        name: str,
        base_url: str,
        auth_header: AuthHeaderFormat,
        model_prefixes: list[str],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> CustomProviderConfig: ...

class DecodedDataUrl:
    mime: str
    data: bytes
    def __init__(self, mime: str = ..., data: bytes = ...) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> DecodedDataUrl: ...

class DeleteResponse:
    id: str
    object: str
    deleted: bool
    def __init__(
        self,
        id: str = ...,  # noqa: A002
        object: str = ...,  # noqa: A002
        deleted: bool = ...,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> DeleteResponse: ...

class DeveloperMessage:
    content: str
    name: str | None
    def __init__(self, content: str = ..., name: str | None = None) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> DeveloperMessage: ...

class DocumentContent:
    data: str
    media_type: str
    def __init__(self, data: str = ..., media_type: str = ...) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> DocumentContent: ...

class EmbeddingObject:
    object: str
    embedding: list[float]
    index: int
    def __init__(
        self,
        object: str,  # noqa: A002
        embedding: list[float],
        index: int,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> EmbeddingObject: ...

class EmbeddingRequest:
    model: str
    input: EmbeddingInput
    encoding_format: EmbeddingFormat | None
    dimensions: int | None
    user: str | None
    def __init__(
        self,
        model: str = ...,
        input: EmbeddingInput = ...,  # noqa: A002
        encoding_format: EmbeddingFormat | None = None,
        dimensions: int | None = None,
        user: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> EmbeddingRequest: ...

class EmbeddingResponse:
    object: str
    data: list[EmbeddingObject]
    model: str
    usage: Usage | None
    def __init__(
        self,
        object: str,  # noqa: A002
        data: list[EmbeddingObject],
        model: str,
        usage: Usage | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> EmbeddingResponse: ...

class FileListQuery:
    purpose: str | None
    limit: int | None
    after: str | None
    def __init__(
        self,
        purpose: str | None = None,
        limit: int | None = None,
        after: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> FileListQuery: ...

class FileListResponse:
    object: str
    data: list[FileObject]
    has_more: bool | None
    def __init__(
        self,
        object: str = ...,  # noqa: A002
        data: list[FileObject] = ...,
        has_more: bool | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> FileListResponse: ...

class FileObject:
    id: str
    object: str
    bytes: int
    created_at: int
    filename: str
    purpose: str
    status: str | None
    def __init__(
        self,
        id: str = ...,  # noqa: A002
        object: str = ...,  # noqa: A002
        bytes: int = ...,  # noqa: A002
        created_at: int = ...,
        filename: str = ...,
        purpose: str = ...,
        status: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> FileObject: ...

class FunctionCall:
    name: str
    arguments: str
    def __init__(self, name: str, arguments: str) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> FunctionCall: ...

class FunctionDefinition:
    name: str
    description: str | None
    parameters: str | None
    strict: bool | None
    def __init__(
        self,
        name: str,
        description: str | None = None,
        parameters: str | None = None,
        strict: bool | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> FunctionDefinition: ...

class FunctionMessage:
    content: str
    name: str
    def __init__(self, content: str = ..., name: str = ...) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> FunctionMessage: ...

class Image:
    url: str | None
    b64_json: str | None
    revised_prompt: str | None
    def __init__(
        self,
        url: str | None = None,
        b64_json: str | None = None,
        revised_prompt: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> Image: ...

class ImageUrl:
    url: str
    detail: ImageDetail | None
    def __init__(self, url: str = ..., detail: ImageDetail | None = None) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ImageUrl: ...

class ImagesResponse:
    created: int
    data: list[Image]
    def __init__(self, created: int = ..., data: list[Image] = ...) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ImagesResponse: ...

class InFlightLimitConfig:
    max_in_flight: int | None
    def __init__(self, max_in_flight: int | None = None) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> InFlightLimitConfig: ...

class IntentPrototype:
    name: str
    embedding: list[float]
    model: str
    def __init__(self, name: str, embedding: list[float], model: str) -> None: ...

class JsonSchemaFormat:
    name: str
    description: str | None
    schema: str
    strict: bool | None
    def __init__(
        self,
        name: str = ...,
        schema: str = ...,
        description: str | None = None,
        strict: bool | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> JsonSchemaFormat: ...

class LlmBudgetConfig:
    global_limit: float | None
    model_limits: dict[str, float] | None
    enforcement: str | None
    def __init__(
        self,
        global_limit: float | None = None,
        model_limits: dict[str, float] | None = None,
        enforcement: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> LlmBudgetConfig: ...

class LlmCacheConfig:
    max_entries: int | None
    ttl_seconds: int | None
    backend: str | None
    backend_config: dict[str, str] | None
    def __init__(
        self,
        max_entries: int | None = None,
        ttl_seconds: int | None = None,
        backend: str | None = None,
        backend_config: dict[str, str] | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> LlmCacheConfig: ...

class LlmConfig:
    model: str
    api_key: str | None
    base_url: str | None
    timeout_secs: int | None
    max_retries: int | None
    temperature: float | None
    max_tokens: int | None
    load_env: bool | None
    headers: dict[str, str] | None
    providers: list[LlmProviderConfig] | None
    cache: LlmCacheConfig | None
    budget: LlmBudgetConfig | None
    rate_limit: LlmRateLimitConfig | None
    in_flight_limit: LlmInFlightLimitConfig | None
    cost_tracking: bool | None
    tracing: bool | None
    cooldown_secs: int | None
    health_check_secs: int | None
    bedrock: BedrockConfig | None
    def __init__(
        self,
        model: str = ...,
        api_key: str | None = None,
        base_url: str | None = None,
        timeout_secs: int | None = None,
        max_retries: int | None = None,
        temperature: float | None = None,
        max_tokens: int | None = None,
        load_env: bool | None = None,
        headers: dict[str, str] | None = None,
        providers: list[LlmProviderConfig] | None = None,
        cache: LlmCacheConfig | None = None,
        budget: LlmBudgetConfig | None = None,
        rate_limit: LlmRateLimitConfig | None = None,
        in_flight_limit: LlmInFlightLimitConfig | None = None,
        cost_tracking: bool | None = None,
        tracing: bool | None = None,
        cooldown_secs: int | None = None,
        health_check_secs: int | None = None,
        bedrock: BedrockConfig | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> LlmConfig: ...

class LlmInFlightLimitConfig:
    max_in_flight: int | None
    def __init__(self, max_in_flight: int | None = None) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> LlmInFlightLimitConfig: ...

class LlmProviderConfig:
    name: str
    base_url: str
    auth_header: str | None
    model_prefixes: list[str]
    def __init__(
        self,
        name: str = ...,
        base_url: str = ...,
        model_prefixes: list[str] = ...,
        auth_header: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> LlmProviderConfig: ...

class LlmRateLimitConfig:
    rpm: int | None
    tpm: int | None
    window_seconds: int | None
    def __init__(
        self,
        rpm: int | None = None,
        tpm: int | None = None,
        window_seconds: int | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> LlmRateLimitConfig: ...

class ModelInfo:
    input_cost_per_token: float
    output_cost_per_token: float
    cache_read_input_token_cost: float | None
    cache_creation_input_token_cost: float | None
    input_cost_per_audio_token: float | None
    output_cost_per_audio_token: float | None
    output_cost_per_reasoning_token: float | None
    max_tokens: int | None
    max_input_tokens: int | None
    max_output_tokens: int | None
    mode: str | None
    supports_vision: bool | None
    supports_function_calling: bool | None
    supports_reasoning: bool | None
    supports_structured_output: bool | None
    supports_audio_input: bool | None
    supports_audio_output: bool | None
    supports_prompt_caching: bool | None
    tiers: list[ModelTier]
    def __init__(
        self,
        input_cost_per_token: float = ...,
        output_cost_per_token: float = ...,
        tiers: list[ModelTier] = ...,
        cache_read_input_token_cost: float | None = None,
        cache_creation_input_token_cost: float | None = None,
        input_cost_per_audio_token: float | None = None,
        output_cost_per_audio_token: float | None = None,
        output_cost_per_reasoning_token: float | None = None,
        max_tokens: int | None = None,
        max_input_tokens: int | None = None,
        max_output_tokens: int | None = None,
        mode: str | None = None,
        supports_vision: bool | None = None,
        supports_function_calling: bool | None = None,
        supports_reasoning: bool | None = None,
        supports_structured_output: bool | None = None,
        supports_audio_input: bool | None = None,
        supports_audio_output: bool | None = None,
        supports_prompt_caching: bool | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ModelInfo: ...

class ModelObject:
    id: str
    object: str
    created: int
    owned_by: str
    def __init__(
        self,
        id: str = ...,  # noqa: A002
        object: str = ...,  # noqa: A002
        created: int = ...,
        owned_by: str = ...,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ModelObject: ...

class ModelTier:
    min_context_tokens: int
    input_cost_per_token: float
    output_cost_per_token: float
    cache_read_input_token_cost: float | None
    cache_creation_input_token_cost: float | None
    input_cost_per_audio_token: float | None
    output_cost_per_audio_token: float | None
    output_cost_per_reasoning_token: float | None
    def __init__(
        self,
        min_context_tokens: int = ...,
        input_cost_per_token: float = ...,
        output_cost_per_token: float = ...,
        cache_read_input_token_cost: float | None = None,
        cache_creation_input_token_cost: float | None = None,
        input_cost_per_audio_token: float | None = None,
        output_cost_per_audio_token: float | None = None,
        output_cost_per_reasoning_token: float | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ModelTier: ...

class ModelsListResponse:
    object: str
    data: list[ModelObject]
    def __init__(
        self,
        object: str = ...,  # noqa: A002
        data: list[ModelObject] = ...,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ModelsListResponse: ...

class ModerationCategories:
    sexual: bool
    hate: bool
    harassment: bool
    self_harm: bool
    sexual_minors: bool
    hate_threatening: bool
    violence_graphic: bool
    self_harm_intent: bool
    self_harm_instructions: bool
    harassment_threatening: bool
    violence: bool
    def __init__(
        self,
        sexual: bool = ...,
        hate: bool = ...,
        harassment: bool = ...,
        self_harm: bool = ...,
        sexual_minors: bool = ...,
        hate_threatening: bool = ...,
        violence_graphic: bool = ...,
        self_harm_intent: bool = ...,
        self_harm_instructions: bool = ...,
        harassment_threatening: bool = ...,
        violence: bool = ...,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ModerationCategories: ...

class ModerationCategoryScores:
    sexual: float
    hate: float
    harassment: float
    self_harm: float
    sexual_minors: float
    hate_threatening: float
    violence_graphic: float
    self_harm_intent: float
    self_harm_instructions: float
    harassment_threatening: float
    violence: float
    def __init__(
        self,
        sexual: float = ...,
        hate: float = ...,
        harassment: float = ...,
        self_harm: float = ...,
        sexual_minors: float = ...,
        hate_threatening: float = ...,
        violence_graphic: float = ...,
        self_harm_intent: float = ...,
        self_harm_instructions: float = ...,
        harassment_threatening: float = ...,
        violence: float = ...,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ModerationCategoryScores: ...

class ModerationRequest:
    input: ModerationInput
    model: str | None
    def __init__(
        self,
        input: ModerationInput = ...,  # noqa: A002
        model: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ModerationRequest: ...

class ModerationResponse:
    id: str
    model: str
    results: list[ModerationResult]
    def __init__(
        self,
        id: str,  # noqa: A002
        model: str,
        results: list[ModerationResult],
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ModerationResponse: ...

class ModerationResult:
    flagged: bool
    categories: ModerationCategories
    category_scores: ModerationCategoryScores
    def __init__(
        self,
        flagged: bool,
        categories: ModerationCategories,
        category_scores: ModerationCategoryScores,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ModerationResult: ...

class OcrImage:
    id: str
    image_base64: str | None
    def __init__(
        self,
        id: str,  # noqa: A002
        image_base64: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> OcrImage: ...

class OcrPage:
    index: int
    markdown: str
    images: list[OcrImage] | None
    dimensions: PageDimensions | None
    def __init__(
        self,
        index: int,
        markdown: str,
        images: list[OcrImage] | None = None,
        dimensions: PageDimensions | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> OcrPage: ...

class OcrRequest:
    model: str
    document: OcrDocument
    pages: list[int] | None
    include_image_base64: bool | None
    def __init__(
        self,
        model: str = ...,
        document: OcrDocument = ...,
        pages: list[int] | None = None,
        include_image_base64: bool | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> OcrRequest: ...

class OcrResponse:
    pages: list[OcrPage]
    model: str
    usage: Usage | None
    def __init__(self, pages: list[OcrPage], model: str, usage: Usage | None = None) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> OcrResponse: ...

class PageDimensions:
    width: int
    height: int
    def __init__(self, width: int, height: int) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> PageDimensions: ...

class PromptTokensDetails:
    cached_tokens: int
    audio_tokens: int
    def __init__(self, cached_tokens: int = ..., audio_tokens: int = ...) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> PromptTokensDetails: ...

class ProviderCapabilities:
    vision: bool
    reasoning: bool
    structured_output: bool
    function_calling: bool
    audio_in: bool
    audio_out: bool
    video_in: bool
    def __init__(
        self,
        vision: bool = ...,
        reasoning: bool = ...,
        structured_output: bool = ...,
        function_calling: bool = ...,
        audio_in: bool = ...,
        audio_out: bool = ...,
        video_in: bool = ...,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ProviderCapabilities: ...

class ProviderConfig:
    name: str
    display_name: str | None
    base_url: str | None
    auth: AuthConfig | None
    endpoints: list[str] | None
    model_prefixes: list[str] | None
    param_mappings: dict[str, str] | None
    def __init__(
        self,
        name: str,
        display_name: str | None = None,
        base_url: str | None = None,
        auth: AuthConfig | None = None,
        endpoints: list[str] | None = None,
        model_prefixes: list[str] | None = None,
        param_mappings: dict[str, str] | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ProviderConfig: ...

class RateLimitConfig:
    rpm: int | None
    tpm: int | None
    window: int | None
    def __init__(
        self,
        window: int | None = None,
        rpm: int | None = None,
        tpm: int | None = None,
    ) -> None: ...
    @staticmethod
    def default() -> RateLimitConfig: ...
    @staticmethod
    def from_json(json_str: str) -> RateLimitConfig: ...

class RerankRequest:
    model: str
    query: str
    documents: list[RerankDocument]
    top_n: int | None
    return_documents: bool | None
    def __init__(
        self,
        model: str = ...,
        query: str = ...,
        documents: list[RerankDocument] = ...,
        top_n: int | None = None,
        return_documents: bool | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> RerankRequest: ...

class RerankResponse:
    id: str | None
    results: list[RerankResult]
    meta: str | None
    def __init__(
        self,
        results: list[RerankResult],
        id: str | None = None,  # noqa: A002
        meta: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> RerankResponse: ...

class RerankResult:
    index: int
    relevance_score: float
    document: RerankResultDocument | None
    def __init__(
        self,
        index: int,
        relevance_score: float,
        document: RerankResultDocument | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> RerankResult: ...

class RerankResultDocument:
    text: str
    def __init__(self, text: str) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> RerankResultDocument: ...

class ResponseObject:
    id: str
    object: str
    created_at: int
    model: str
    status: str
    output: list[ResponseOutputItem]
    usage: ResponseUsage | None
    error: str | None
    def __init__(
        self,
        id: str = ...,  # noqa: A002
        object: str = ...,  # noqa: A002
        created_at: int = ...,
        model: str = ...,
        status: str = ...,
        output: list[ResponseOutputItem] = ...,
        usage: ResponseUsage | None = None,
        error: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ResponseObject: ...

class ResponseOutputItem:
    item_type: str
    content: str
    def __init__(
        self,
        type: str = ...,  # noqa: A002
        content: str = ...,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ResponseOutputItem: ...

class ResponseTool:
    tool_type: str
    config: str
    def __init__(
        self,
        type: str = ...,  # noqa: A002
        config: str = ...,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ResponseTool: ...

class ResponseUsage:
    input_tokens: int
    output_tokens: int
    total_tokens: int
    def __init__(
        self,
        input_tokens: int = ...,
        output_tokens: int = ...,
        total_tokens: int = ...,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ResponseUsage: ...

class SearchRequest:
    model: str
    query: str
    max_results: int | None
    search_domain_filter: list[str] | None
    country: str | None
    def __init__(
        self,
        model: str = ...,
        query: str = ...,
        max_results: int | None = None,
        search_domain_filter: list[str] | None = None,
        country: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SearchRequest: ...

class SearchResponse:
    results: list[SearchResult]
    model: str
    def __init__(self, results: list[SearchResult], model: str) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SearchResponse: ...

class SearchResult:
    title: str
    url: str
    snippet: str
    date: str | None
    def __init__(self, title: str, url: str, snippet: str, date: str | None = None) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SearchResult: ...

class SpecificFunction:
    name: str
    def __init__(self, name: str = ...) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SpecificFunction: ...

class SpecificToolChoice:
    choice_type: ToolType
    function: SpecificFunction
    def __init__(
        self,
        type: ToolType = ...,  # noqa: A002
        function: SpecificFunction | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SpecificToolChoice: ...

class StreamChoice:
    index: int
    delta: StreamDelta
    finish_reason: FinishReason | None
    def __init__(
        self,
        index: int = ...,
        delta: StreamDelta | None = None,
        finish_reason: FinishReason | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> StreamChoice: ...

class StreamDelta:
    role: str | None
    content: str | None
    tool_calls: list[StreamToolCall] | None
    function_call: StreamFunctionCall | None
    refusal: str | None
    reasoning_content: str | None
    def __init__(
        self,
        role: str | None = None,
        content: str | None = None,
        tool_calls: list[StreamToolCall] | None = None,
        function_call: StreamFunctionCall | None = None,
        refusal: str | None = None,
        reasoning_content: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> StreamDelta: ...

class StreamFunctionCall:
    name: str | None
    arguments: str | None
    def __init__(self, name: str | None = None, arguments: str | None = None) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> StreamFunctionCall: ...

class StreamOptions:
    include_usage: bool | None
    def __init__(self, include_usage: bool | None = None) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> StreamOptions: ...

class StreamToolCall:
    index: int
    id: str | None
    call_type: ToolType | None
    function: StreamFunctionCall | None
    def __init__(
        self,
        index: int = ...,
        id: str | None = None,  # noqa: A002
        type: ToolType | None = None,  # noqa: A002
        function: StreamFunctionCall | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> StreamToolCall: ...

class SystemMessage:
    content: UserContent
    name: str | None
    def __init__(self, content: UserContent = ..., name: str | None = None) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> SystemMessage: ...

class ToolCall:
    id: str
    call_type: ToolType
    function: FunctionCall
    def __init__(
        self,
        id: str,  # noqa: A002
        type: ToolType,  # noqa: A002
        function: FunctionCall,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ToolCall: ...

class ToolMessage:
    content: UserContent
    tool_call_id: str
    name: str | None
    def __init__(
        self,
        content: UserContent = ...,
        tool_call_id: str = ...,
        name: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> ToolMessage: ...

class TranscriptionResponse:
    text: str
    language: str | None
    duration: float | None
    segments: list[TranscriptionSegment] | None
    def __init__(
        self,
        text: str = ...,
        language: str | None = None,
        duration: float | None = None,
        segments: list[TranscriptionSegment] | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TranscriptionResponse: ...

class TranscriptionSegment:
    id: int
    start: float
    end: float
    text: str
    def __init__(
        self,
        id: int = ...,  # noqa: A002
        start: float = ...,
        end: float = ...,
        text: str = ...,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> TranscriptionSegment: ...

class Usage:
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    prompt_tokens_details: PromptTokensDetails | None
    def __init__(
        self,
        prompt_tokens: int = ...,
        completion_tokens: int = ...,
        total_tokens: int = ...,
        prompt_tokens_details: PromptTokensDetails | None = None,
    ) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> Usage: ...

class UserMessage:
    content: UserContent
    name: str | None
    def __init__(self, content: UserContent = ..., name: str | None = None) -> None: ...
    @staticmethod
    def from_json(json_str: str) -> UserMessage: ...

class WaitForBatchConfig:
    initial_interval_secs: float
    max_interval_secs: float
    backoff_multiplier: float
    timeout_secs: float | None
    def __init__(
        self,
        initial_interval_secs: float = ...,
        max_interval_secs: float = ...,
        backoff_multiplier: float = ...,
        timeout_secs: float | None = None,
    ) -> None: ...
    @staticmethod
    def default() -> WaitForBatchConfig: ...
    @staticmethod
    def from_json(json_str: str) -> WaitForBatchConfig: ...

class DefaultClient:
    async def chat(self, req: ChatCompletionRequest) -> ChatCompletionResponse: ...
    def chat_stream(self, req: ChatCompletionRequest) -> AsyncIterator[ChatCompletionChunk]: ...
    async def embed(self, req: EmbeddingRequest) -> EmbeddingResponse: ...
    async def list_models(self) -> ModelsListResponse: ...
    async def image_generate(self, req: CreateImageRequest) -> ImagesResponse: ...
    async def speech(self, req: CreateSpeechRequest) -> bytes: ...
    async def transcribe(self, req: CreateTranscriptionRequest) -> TranscriptionResponse: ...
    async def moderate(self, req: ModerationRequest) -> ModerationResponse: ...
    async def rerank(self, req: RerankRequest) -> RerankResponse: ...
    async def search(self, req: SearchRequest) -> SearchResponse: ...
    async def ocr(self, req: OcrRequest) -> OcrResponse: ...
    async def create_file(self, req: CreateFileRequest) -> FileObject: ...
    async def retrieve_file(self, file_id: str) -> FileObject: ...
    async def delete_file(self, file_id: str) -> DeleteResponse: ...
    async def list_files(self, query: FileListQuery | None = None) -> FileListResponse: ...
    async def file_content(self, file_id: str) -> bytes: ...
    async def create_batch(self, req: CreateBatchRequest) -> BatchObject: ...
    async def retrieve_batch(self, batch_id: str) -> BatchObject: ...
    async def list_batches(self, query: BatchListQuery | None = None) -> BatchListResponse: ...
    async def cancel_batch(self, batch_id: str) -> BatchObject: ...
    async def fetch_batch_for_polling(self, batch_id: str) -> BatchObject: ...
    async def wait_for_batch(self, batch_id: str, config: WaitForBatchConfig) -> BatchObject: ...
    async def create_response(self, req: CreateResponseRequest) -> ResponseObject: ...
    async def retrieve_response(self, response_id: str) -> ResponseObject: ...
    async def cancel_response(self, response_id: str) -> ResponseObject: ...
class SingleflightResult: ...

class AssistantContent:
    @staticmethod
    def from_text(value: str) -> AssistantContent: ...

    @staticmethod
    def from_parts(value: list[AssistantPart]) -> AssistantContent: ...

    def __init__(self, value: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class AssistantPartTextVariant(TypedDict):
    type: Literal["text"]
    text: str

class AssistantPartRefusalVariant(TypedDict):
    type: Literal["refusal"]
    refusal: str

class AssistantPartOutputImageVariant(TypedDict):
    type: Literal["output_image"]
    image_url: ImageUrl

class AssistantPartOutputAudioVariant(TypedDict):
    type: Literal["output_audio"]
    audio: AudioContent

class AssistantPart:
    type: str
    @staticmethod
    def text(text: str) -> AssistantPart: ...

    @staticmethod
    def refusal(refusal: str) -> AssistantPart: ...

    @staticmethod
    def output_image(image_url: options.ImageUrl | dict[str, Any]) -> AssistantPart: ...

    @staticmethod
    def output_audio(audio: options.AudioContent | dict[str, Any]) -> AssistantPart: ...

    def __init__(self, value: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class AuthHeaderFormat:
    @staticmethod
    def from_api_key(value: str) -> AuthHeaderFormat: ...

    def __init__(self, value: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class AuthType:
    BEARER: AuthType = ...
    API_KEY: AuthType = ...
    NONE: AuthType = ...
    UNKNOWN: AuthType = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class BatchStatus:
    VALIDATING: BatchStatus = ...
    FAILED: BatchStatus = ...
    IN_PROGRESS: BatchStatus = ...
    FINALIZING: BatchStatus = ...
    COMPLETED: BatchStatus = ...
    EXPIRED: BatchStatus = ...
    CANCELLING: BatchStatus = ...
    CANCELLED: BatchStatus = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class CacheBackendMemoryVariant(TypedDict):
    type: Literal["memory"]

class CacheBackendOpenDalVariant(TypedDict):
    type: Literal["open_dal"]
    scheme: str
    config: dict[str, str]

class CacheBackend:
    type: str
    @staticmethod
    def open_dal(scheme: str, config: dict[str, str]) -> CacheBackend: ...

    def __init__(self, value: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class CircuitState:
    CLOSED: CircuitState = ...
    OPEN: CircuitState = ...
    HALF_OPEN: CircuitState = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class ContentPartTextVariant(TypedDict):
    type: Literal["text"]
    text: str

class ContentPartImageUrlVariant(TypedDict):
    type: Literal["image_url"]
    image_url: ImageUrl

class ContentPartDocumentVariant(TypedDict):
    type: Literal["document"]
    document: DocumentContent

class ContentPartInputAudioVariant(TypedDict):
    type: Literal["input_audio"]
    input_audio: AudioContent

class ContentPart:
    type: str
    @staticmethod
    def text(text: str) -> ContentPart: ...

    @staticmethod
    def image_url(image_url: options.ImageUrl | dict[str, Any]) -> ContentPart: ...

    @staticmethod
    def document(document: options.DocumentContent | dict[str, Any]) -> ContentPart: ...

    @staticmethod
    def input_audio(input_audio: options.AudioContent | dict[str, Any]) -> ContentPart: ...

    def __init__(self, value: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class EmbeddingContentPartTextVariant(TypedDict):
    type: Literal["text"]
    text: str

class EmbeddingContentPartImageUrlVariant(TypedDict):
    type: Literal["image_url"]
    image_url: ImageUrl

class EmbeddingContentPartImageBase64Variant(TypedDict):
    type: Literal["image_base64"]
    image_base64: str

class EmbeddingContentPart:
    type: str
    @staticmethod
    def text(text: str) -> EmbeddingContentPart: ...

    @staticmethod
    def image_url(image_url: options.ImageUrl | dict[str, Any]) -> EmbeddingContentPart: ...

    @staticmethod
    def image_base64(image_base64: str) -> EmbeddingContentPart: ...

    def __init__(self, value: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class EmbeddingFormat:
    FLOAT: EmbeddingFormat = ...
    BASE64: EmbeddingFormat = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class EmbeddingInput:
    @staticmethod
    def from_single(value: str) -> EmbeddingInput: ...

    @staticmethod
    def from_multiple(value: list[str]) -> EmbeddingInput: ...

    @staticmethod
    def from_multimodal(value: list[EmbeddingContentPart]) -> EmbeddingInput: ...

    def __init__(self, value: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Enforcement:
    HARD: Enforcement = ...
    SOFT: Enforcement = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class FilePurpose:
    ASSISTANTS: FilePurpose = ...
    BATCH: FilePurpose = ...
    FINE_TUNE: FilePurpose = ...
    VISION: FilePurpose = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class FinishReason:
    STOP: FinishReason = ...
    LENGTH: FinishReason = ...
    TOOL_CALLS: FinishReason = ...
    CONTENT_FILTER: FinishReason = ...
    FUNCTION_CALL: FinishReason = ...
    OTHER: FinishReason = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class HealthStatus:
    HEALTHY: HealthStatus = ...
    UNHEALTHY: HealthStatus = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class ImageDetail:
    LOW: ImageDetail = ...
    HIGH: ImageDetail = ...
    AUTO: ImageDetail = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class MessageSystemVariant(TypedDict):
    role: Literal["system"]
    content: UserContent
    name: str | None

class MessageUserVariant(TypedDict):
    role: Literal["user"]
    content: UserContent
    name: str | None

class MessageAssistantVariant(TypedDict):
    role: Literal["assistant"]
    content: AssistantContent | None
    name: str | None
    tool_calls: list[ToolCall] | None
    refusal: str | None
    function_call: FunctionCall | None
    reasoning_content: str | None

class MessageToolVariant(TypedDict):
    role: Literal["tool"]
    content: UserContent
    tool_call_id: str
    name: str | None

class MessageDeveloperVariant(TypedDict):
    role: Literal["developer"]
    content: str
    name: str | None

class MessageFunctionVariant(TypedDict):
    role: Literal["function"]
    content: str
    name: str

class Message:
    role: str
    system: SystemMessage | None
    user: UserMessage | None
    assistant: AssistantMessage | None
    tool: ToolMessage | None
    developer: DeveloperMessage | None
    function: FunctionMessage | None
    @staticmethod
    def from_system(value: options.SystemMessage | dict[str, Any]) -> Message: ...

    @staticmethod
    def from_user(value: options.UserMessage | dict[str, Any]) -> Message: ...

    @staticmethod
    def from_assistant(value: options.AssistantMessage | dict[str, Any]) -> Message: ...

    @staticmethod
    def from_tool(value: options.ToolMessage | dict[str, Any]) -> Message: ...

    @staticmethod
    def from_developer(value: options.DeveloperMessage | dict[str, Any]) -> Message: ...

    @staticmethod
    def from_function(value: options.FunctionMessage | dict[str, Any]) -> Message: ...

    def __init__(self, value: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Modality:
    TEXT: Modality = ...
    AUDIO: Modality = ...
    IMAGE: Modality = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class ModerationInput:
    @staticmethod
    def from_single(value: str) -> ModerationInput: ...

    @staticmethod
    def from_multiple(value: list[str]) -> ModerationInput: ...

    def __init__(self, value: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class OcrDocumentUrlVariant(TypedDict):
    type: Literal["document_url"]
    url: str

class OcrDocumentBase64Variant(TypedDict):
    type: Literal["base64"]
    data: str
    media_type: str

class OcrDocument:
    type: str
    @staticmethod
    def url(url: str) -> OcrDocument: ...

    @staticmethod
    def base64(data: str, media_type: str) -> OcrDocument: ...

    def __init__(self, value: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class ReasoningEffort:
    LOW: ReasoningEffort = ...
    MEDIUM: ReasoningEffort = ...
    HIGH: ReasoningEffort = ...
    MINIMAL: ReasoningEffort = ...
    MAX: ReasoningEffort = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class RefreshOutcome:
    DISABLED: RefreshOutcome = ...
    FROM_CACHE: RefreshOutcome = ...
    FETCHED: RefreshOutcome = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class RerankDocument:
    @staticmethod
    def from_text(value: str) -> RerankDocument: ...

    @staticmethod
    def object(text: str) -> RerankDocument: ...

    def __init__(self, value: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class ResponseFormatTextVariant(TypedDict):
    type: Literal["text"]

class ResponseFormatJsonObjectVariant(TypedDict):
    type: Literal["json_object"]

class ResponseFormatJsonSchemaVariant(TypedDict):
    type: Literal["json_schema"]
    json_schema: JsonSchemaFormat

class ResponseFormat:
    type: str
    @staticmethod
    def json_schema(json_schema: options.JsonSchemaFormat | dict[str, Any]) -> ResponseFormat: ...

    def __init__(self, value: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class StopSequence:
    @staticmethod
    def from_single(value: str) -> StopSequence: ...

    @staticmethod
    def from_multiple(value: list[str]) -> StopSequence: ...

    def __init__(self, value: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class StreamFormat:
    SSE: StreamFormat = ...
    AWS_EVENT_STREAM: StreamFormat = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class ToolChoice:
    mode: ToolChoiceMode | None
    specific: SpecificToolChoice | None
    @staticmethod
    def from_mode(value: ToolChoiceMode) -> ToolChoice: ...

    @staticmethod
    def from_specific(value: options.SpecificToolChoice | dict[str, Any]) -> ToolChoice: ...

    def __init__(self, value: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class ToolChoiceMode:
    AUTO: ToolChoiceMode = ...
    REQUIRED: ToolChoiceMode = ...
    NONE: ToolChoiceMode = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class ToolType:
    FUNCTION: ToolType = ...
    def __init__(self, value: int | str) -> None: ...
    def __hash__(self) -> int: ...

class UserContent:
    @staticmethod
    def from_text(value: str) -> UserContent: ...

    @staticmethod
    def from_parts(value: list[ContentPart]) -> UserContent: ...

    def __init__(self, value: dict[str, Any] | str | None = None, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class CatalogRefreshError(Exception): ...
class DisabledError(CatalogRefreshError): ...
class InsecureUrlError(CatalogRefreshError): ...
class FetchError(CatalogRefreshError): ...
class ParseError(CatalogRefreshError): ...
class CacheError(CatalogRefreshError): ...
class LiterLlmError(Exception): ...
class AuthenticationError(LiterLlmError): ...
class RateLimitedError(LiterLlmError): ...
class BadRequestError(LiterLlmError): ...
class ContextWindowExceededError(LiterLlmError): ...
class ContentPolicyError(LiterLlmError): ...
class NotFoundError(LiterLlmError): ...
class ServerError(LiterLlmError): ...
class ServiceUnavailableError(LiterLlmError): ...
class LiterLlmTimeoutError(LiterLlmError): ...
class StreamingError(LiterLlmError): ...
class EndpointNotSupportedError(LiterLlmError): ...
class InvalidHeaderError(LiterLlmError): ...
class SerializationError(LiterLlmError): ...
class BudgetExceededError(LiterLlmError): ...
class HookRejectedError(LiterLlmError): ...
class InternalError(LiterLlmError): ...
class OutboundForbiddenError(LiterLlmError): ...
class IdempotencyConflictError(LiterLlmError): ...
class IdempotencyInFlightError(LiterLlmError): ...

class LiterLlmErrorInfo:
    code: int
    status_code: int
    is_transient: bool
    error_type: str

def liter_llm_error_info(err: Any) -> LiterLlmErrorInfo: ...

def all_providers() -> list[ProviderConfig]: ...
def capabilities(provider_name: str) -> ProviderCapabilities: ...
def check_bound(context: str, current_len: int, incoming: int, limit: int) -> None: ...
def clear() -> None: ...
def clear_catalog_overlay() -> None: ...
def completion_cost(model: str, prompt_tokens: int, completion_tokens: int) -> float | None: ...
def completion_cost_with_cache(
    model: str,
    prompt_tokens: int,
    cached_tokens: int,
    completion_tokens: int,
) -> float | None: ...

def complex_provider_names() -> list[str]: ...
def count_request_tokens(model: str, req: ChatCompletionRequest) -> int: ...
def count_tokens(model: str, text: str) -> int: ...
def create_client(
    api_key: str,
    base_url: str | None = None,
    timeout_secs: int | None = None,
    max_retries: int | None = None,
    model_hint: str | None = None,
) -> DefaultClient: ...

def create_client_from_json(json: str) -> DefaultClient: ...
def decode_data_url(url: str) -> DecodedDataUrl | None: ...
def encode_data_url(
    bytes: builtins.bytes,  # noqa: A002
    mime: str | None = None,
) -> str: ...

def ensure_crypto_provider() -> None: ...
def install_catalog_overlay_from_str(catalog_json: str) -> None: ...
def model_info(model: str) -> ModelInfo | None: ...
def record_cost_usd(system: str, model: str, operation: str, cost_usd: float) -> None: ...
async def refresh_catalog(config: CatalogRefreshConfig) -> RefreshOutcome: ...
def register_custom_provider(config: CustomProviderConfig) -> None: ...
def unregister_custom_provider(name: str) -> bool: ...
