# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3fb07515ba02077671946cad7f111c0c7840343537bb31d1488bc316651dca95
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Exception hierarchy (re-exported from the native module)."""

from ._internal_bindings import (
    AuthenticationError,
    BadRequestError,
    BudgetExceededError,
    ContentPolicyError,
    ContextWindowExceededError,
    EndpointNotSupportedError,
    HookRejectedError,
    IdempotencyConflictError,
    IdempotencyInFlightError,
    InternalError,
    InvalidHeaderError,
    LiterLlmError,
    LiterLlmTimeoutError,
    NotFoundError,
    OutboundForbiddenError,
    RateLimitedError,
    SerializationError,
    ServerError,
    ServiceUnavailableError,
    StreamingError,
)

__all__ = [
    "AuthenticationError",
    "BadRequestError",
    "BudgetExceededError",
    "ContentPolicyError",
    "ContextWindowExceededError",
    "EndpointNotSupportedError",
    "HookRejectedError",
    "IdempotencyConflictError",
    "IdempotencyInFlightError",
    "InternalError",
    "InvalidHeaderError",
    "LiterLlmError",
    "LiterLlmTimeoutError",
    "NotFoundError",
    "OutboundForbiddenError",
    "RateLimitedError",
    "SerializationError",
    "ServerError",
    "ServiceUnavailableError",
    "StreamingError",
]

# Re-point each exception's __module__ at the public package so tracebacks show the
# public name (e.g. "DownloadError"), not the native module name (GitHub issue #147).
_public_module = __name__.rsplit(".", 1)[0]
for _name in __all__:
    globals()[_name].__module__ = _public_module
del _name, _public_module
