# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:07df79b06f7f819edf0c1dae372b6a8759219fcce15a13259868b5ce5ffdc9b7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Exception hierarchy (re-exported from the native module)."""

from ._internal_bindings import (
    AuthenticationError,
    BadRequestError,
    BudgetExceededError,
    ContentPolicyError,
    ContextWindowExceededError,
    EndpointNotSupportedError,
    HookRejectedError,
    IdempotencyConflictError,
    IdempotencyInFlightError,
    InternalError,
    InvalidHeaderError,
    LiterLlmError,
    LiterLlmTimeoutError,
    NotFoundError,
    OutboundForbiddenError,
    RateLimitedError,
    SerializationError,
    ServerError,
    ServiceUnavailableError,
    StreamingError,
)

__all__ = [
    "AuthenticationError",
    "BadRequestError",
    "BudgetExceededError",
    "ContentPolicyError",
    "ContextWindowExceededError",
    "EndpointNotSupportedError",
    "HookRejectedError",
    "IdempotencyConflictError",
    "IdempotencyInFlightError",
    "InternalError",
    "InvalidHeaderError",
    "LiterLlmError",
    "LiterLlmTimeoutError",
    "NotFoundError",
    "OutboundForbiddenError",
    "RateLimitedError",
    "SerializationError",
    "ServerError",
    "ServiceUnavailableError",
    "StreamingError",
]
