# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:68acd6b3348cda586d078ef91ae450ad7a2cbb91acc20686ec9b3504e1d71fe2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: cache
defmodule E2e.CacheTest do
  use ExUnit.Case, async: false

  describe "cache_hit" do
    test "cache_hit" do
      {:ok, client} = LiterLlm.create_client("test-key", (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/cache_hit")
      {:ok, result} = LiterLlm.defaultclient_chat_async(client, "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
      # skipped: field 'cache_hit' not available on result type
    end
  end

  describe "cache_miss_ttl" do
    test "cache_miss_ttl" do
      {:ok, client} = LiterLlm.create_client("test-key", (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/cache_miss_ttl")
      {:ok, result} = LiterLlm.defaultclient_chat_async(client, "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
      # skipped: field 'cache_hit' not available on result type
    end
  end

  describe "cache_opendal_memory" do
    test "cache_opendal_memory" do
      {:ok, client} = LiterLlm.create_client("test-key", (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/cache_opendal_memory")
      {:ok, result} = LiterLlm.defaultclient_chat_async(client, "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"openai/gpt-4o\"}")
      # skipped: field 'cache_hit' not available on result type
    end
  end

  describe "cache_stream_bypass" do
    test "cache_stream_bypass" do
      {:ok, client} = LiterLlm.create_client("test-key", (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/cache_stream_bypass")
      {:ok, result} = LiterLlm.defaultclient_chat_stream_async(client, "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}")
      # skipped: field 'cache_bypassed' not available on result type
    end
  end
end
