# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f8379eae27ed3a6329455bc322e5e326fb64d35482ccad05e94e2fd26dee47b2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: list-models
defmodule E2e.ListModelsTest do
  use ExUnit.Case, async: false

  describe "empty_model_list" do
    test "empty_model_list" do
      {:ok, client} = LiterLlm.create_client("test-key", base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/empty_model_list")
      {:ok, result} = LiterLlm.defaultclient_list_models_async(client)
      assert length(result.data) >= 0
      assert length(result.data) == 0
    end
  end

  describe "list_models_error_401" do
    test "list_models_error_401" do
      {:ok, client} = LiterLlm.create_client("test-key", base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/list_models_error_401")
      assert {:error, _} = LiterLlm.defaultclient_list_models_async(client)
    end
  end

  describe "list_models_error_500" do
    test "list_models_error_500" do
      {:ok, client} = LiterLlm.create_client("test-key", base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/list_models_error_500")
      assert {:error, _} = LiterLlm.defaultclient_list_models_async(client)
    end
  end

  describe "list_models_filtered" do
    test "list_models_filtered" do
      {:ok, client} = LiterLlm.create_client("test-key", base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/list_models_filtered")
      {:ok, result} = LiterLlm.defaultclient_list_models_async(client)
      assert length(result.data) >= 5
      assert String.trim(Enum.at(result.data, 0).object) == "model"
    end
  end
end
