# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9ebda2bedb27bc07d8a4cfcbfadd55fd159de7f875fcb63308eaee6e1c3a895d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: parity
defmodule E2e.ParityTest do
  use ExUnit.Case, async: false

  describe "api_surface_parity" do
    test "api_surface_parity" do
      {:ok, client} = LiterLlm.create_client("test-key", base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/api_surface_parity")
      {:ok, result} = LiterLlm.defaultclient_chat_async(client, "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4o\"}")
    end
  end
end
