analyzer:
  exclude:
    - test_apps/**
    - packages/dart/lib/src/frb/**
    - packages/dart/lib/src/liter_llm_bridge_generated/**
    - packages/dart/example/**
    - packages/dart/lib/src/traits.dart
  errors:
    unchecked_use_of_nullable_value: ignore
