// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b159ec7bf40f2249b9f5696d5819688bca2310a2b26cc9acae8194e6255f8b03
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using LiterLlm;
using static LiterLlm.LiterLlmConverter;

namespace LiterLlm
{
    /// <summary>E2e tests for category: custom_provider.</summary>
    public class CustomProviderTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public async Task Test_ProviderAuth()
        {
            // Tests custom provider with custom auth header
            var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/provider_auth";
            var client = LiterLlmConverter.CreateClient("test-key", baseUrl, null, null, null);

            var result = await client.ChatAsync(ChatCompletionRequest.FromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"my-auth-model-v1\"}"));

        }

        [Fact]
        public async Task Test_RegisterProvider()
        {
            // Tests that a custom provider can be registered and routes requests
            var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/register_provider";
            var client = LiterLlmConverter.CreateClient("test-key", baseUrl, null, null, null);

            var result = await client.ChatAsync(ChatCompletionRequest.FromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"my-model-v1\"}"));

        }


    }
}
