// Generated by alef. Do not edit by hand.
// alef:hash:990a8effc943d1d0f9c7ef763981d4cd9b10eefb9c9b4f11e1222eac8fca8442
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.literllm.android

/** Embedding request. */
data class EmbeddingRequest(
    /** Model ID (e.g., `"text-embedding-3-small"`). */
    val model: String = "",
    /** Text or texts to embed. */
    @field:com.fasterxml.jackson.databind.annotation.JsonSerialize(`as` = EmbeddingInput::class)
    val input: EmbeddingInput,
    /** Output format: float (native) or base64. */
    val encodingFormat: EmbeddingFormat? = null,
    /** Requested embedding dimensions (if supported by the model). */
    val dimensions: Int? = null,
    /** User identifier for request tracking. */
    val user: String? = null,
)
