<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:52effca2513e1c5f8a9a5b90a372d645388de4b92e4f822acc38d97502c322b6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Liter\Llm\E2e;

use PHPUnit\Framework\TestCase;
use Liter\Llm\LiterLlm;
use Liter\Llm\ChatCompletionRequest;

/** E2e tests for category: error-handling. */
final class ErrorHandlingTest extends TestCase
{

    /** 401 Authentication error returned by the Anthropic API when the API key is invalid */
    public function test_anthropic_error_auth(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/anthropic_error_auth');
        $this->expectException(\Exception::class);        $request = \Liter\Llm\ChatCompletionRequest::from_json(json_encode(["messages" => [["content" => "Hello", "role" => "user"]], "model" => "anthropic/claude-3-5-sonnet-20241022"]));
        $client->chat($request);
    }


    /** 401 Unauthorized error when API key is invalid or missing */
    public function test_auth_401(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/auth_401');
        $this->expectException(\Exception::class);        $request = \Liter\Llm\ChatCompletionRequest::from_json(json_encode(["messages" => [["content" => "Hello", "role" => "user"]], "model" => "gpt-4"]));
        $client->chat($request);
    }


    /** Azure OpenAI returns a 401 Unauthorized error when the API key is missing or invalid — uses Azure's error envelope shape with code AccessDenied */
    public function test_azure_error_auth(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/azure_error_auth');
        $this->expectException(\Exception::class);        $request = \Liter\Llm\ChatCompletionRequest::from_json(json_encode(["messages" => [["content" => "Hello", "role" => "user"]], "model" => "azure/gpt-4"]));
        $client->chat($request);
    }


    /** 400 Bad Request error when a parameter value is invalid */
    public function test_bad_request_400(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/bad_request_400');
        $this->expectException(\Exception::class);        $request = \Liter\Llm\ChatCompletionRequest::from_json(json_encode(["messages" => [["content" => "Hello", "role" => "user"]], "model" => "gpt-4", "temperature" => 5.0]));
        $client->chat($request);
    }


    /** AWS Bedrock returns 403 Forbidden (not 401) when credentials are missing, expired, or the IAM role lacks bedrock:InvokeModel permission — verifies the error is mapped to Authentication */
    public function test_bedrock_error_auth(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/bedrock_error_auth');
        $this->expectException(\Exception::class);        $request = \Liter\Llm\ChatCompletionRequest::from_json(json_encode(["messages" => [["content" => "Hello", "role" => "user"]], "model" => "bedrock/anthropic.claude-3-sonnet-20240229-v1:0"]));
        $client->chat($request);
    }


    /** 400 error when a request is rejected due to content policy */
    public function test_content_policy_violation(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/content_policy_violation');
        $this->expectException(\Exception::class);        $request = \Liter\Llm\ChatCompletionRequest::from_json(json_encode(["messages" => [["content" => "Generate harmful content", "role" => "user"]], "model" => "gpt-4"]));
        $client->chat($request);
    }


    /** 400 error when the prompt exceeds the model's maximum context length */
    public function test_context_window_exceeded(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/context_window_exceeded');
        $this->expectException(\Exception::class);        $request = \Liter\Llm\ChatCompletionRequest::from_json(json_encode(["messages" => [["content" => "Very long prompt that exceeds the context window...", "role" => "user"]], "model" => "gpt-4"]));
        $client->chat($request);
    }


    /** 200 OK response with an empty JSON object body, missing required fields */
    public function test_empty_response_body(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/empty_response_body');
        $this->expectException(\Exception::class);        $request = \Liter\Llm\ChatCompletionRequest::from_json(json_encode(["messages" => [["content" => "Hello", "role" => "user"]], "model" => "gpt-4"]));
        $client->chat($request);
    }


    /** 403 Forbidden error when the API key does not have access to the requested resource */
    public function test_forbidden_403(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/forbidden_403');
        $this->expectException(\Exception::class);        $request = \Liter\Llm\ChatCompletionRequest::from_json(json_encode(["messages" => [["content" => "Hello", "role" => "user"]], "model" => "gpt-4"]));
        $client->chat($request);
    }


    /** 504 Gateway Timeout error when the upstream service times out */
    public function test_gateway_timeout_504(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/gateway_timeout_504');
        $this->expectException(\Exception::class);        $request = \Liter\Llm\ChatCompletionRequest::from_json(json_encode(["messages" => [["content" => "Hello", "role" => "user"]], "model" => "gpt-4"]));
        $client->chat($request);
    }


    /** 401 Authentication error returned by the GitHub Copilot API when the token is invalid or expired */
    public function test_github_copilot_error_auth(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/github_copilot_error_auth');
        $this->expectException(\Exception::class);        $request = \Liter\Llm\ChatCompletionRequest::from_json(json_encode(["messages" => [["content" => "Hello", "role" => "user"]], "model" => "github_copilot/gpt-4o"]));
        $client->chat($request);
    }


    /** 404 Not Found error when requesting a model that does not exist */
    public function test_not_found_404(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/not_found_404');
        $this->expectException(\Exception::class);        $request = \Liter\Llm\ChatCompletionRequest::from_json(json_encode(["messages" => [["content" => "Hello", "role" => "user"]], "model" => "gpt-99"]));
        $client->chat($request);
    }


    /** 429 Too Many Requests error when the rate limit is exceeded */
    public function test_rate_limit_429(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/rate_limit_429');
        $this->expectException(\Exception::class);        $request = \Liter\Llm\ChatCompletionRequest::from_json(json_encode(["messages" => [["content" => "Hello", "role" => "user"]], "model" => "gpt-4"]));
        $client->chat($request);
    }


    /** 500 Internal Server Error from the upstream API */
    public function test_server_error_500(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/server_error_500');
        $this->expectException(\Exception::class);        $request = \Liter\Llm\ChatCompletionRequest::from_json(json_encode(["messages" => [["content" => "Hello", "role" => "user"]], "model" => "gpt-4"]));
        $client->chat($request);
    }


    /** 502 Bad Gateway error when the upstream service is unavailable */
    public function test_service_unavailable_502(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/service_unavailable_502');
        $this->expectException(\Exception::class);        $request = \Liter\Llm\ChatCompletionRequest::from_json(json_encode(["messages" => [["content" => "Hello", "role" => "user"]], "model" => "gpt-4"]));
        $client->chat($request);
    }


    /** 408 Request Timeout error when the API request takes too long to complete */
    public function test_timeout_error(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/timeout_error');
        $this->expectException(\Exception::class);        $request = \Liter\Llm\ChatCompletionRequest::from_json(json_encode(["messages" => [["content" => "Hello", "role" => "user"]], "model" => "gpt-4"]));
        $client->chat($request);
    }


    /** Google Vertex AI returns 401 Unauthorized when the OAuth2 token is missing, expired, or the service account lacks aiplatform.endpoints.predict permission — verifies the error is mapped to Authentication */
    public function test_vertex_error_auth(): void
    {
        $client = \Liter\Llm\LiterLlm::createClient('test-key', getenv('MOCK_SERVER_URL') . '/fixtures/vertex_error_auth');
        $this->expectException(\Exception::class);        $request = \Liter\Llm\ChatCompletionRequest::from_json(json_encode(["messages" => [["content" => "Hello", "role" => "user"]], "model" => "vertex_ai/gemini-2.0-flash"]));
        $client->chat($request);
    }

}
