// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d4cbae5df7828314ec55fa6d3e0027f1ecc6423056564a812f4bb805ab154e73
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
//! E2e tests for category: configuration

use liter_llm::BatchClient;
use liter_llm::FileClient;
use liter_llm::LlmClient;
use liter_llm::ResponseClient;
mod common;
mod mock_server;
#[allow(unused_imports)]
use mock_server::{MockRoute, MockServer};

#[tokio::test]
async fn test_custom_base_url() {
    // Client configured with a custom base URL routes all requests to that endpoint
    let mock_route = MockRoute {
        path: "/chat/completions",
        method: "POST",
        status: 200,
        body: r#"{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hi there!","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-local-001","model":"local-model","object":"chat.completion","usage":{"completion_tokens":4,"prompt_tokens":3,"total_tokens":7}}"#.to_string(),
        is_streaming: false,
        stream_chunks: vec![],
        headers: vec![
        ],
        delay_ms: None,
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json: serde_json::Value =
        serde_json::from_str(r#"{"messages":[{"content":"Hello","role":"user"}],"model":"local-model"}"#).unwrap();
    let request = serde_json::from_value(request_json).unwrap();
    let client =
        liter_llm::create_client("test-key".to_string(), Some(mock_server.url.clone()), None, None, None).unwrap();
    let result = client.chat(request).await.expect("should succeed");
    let _choices_0_message_content = result.choices[0]
        .message
        .content
        .as_ref()
        .map(|v| v.to_string())
        .unwrap_or_default();
    let _choices_0_finish_reason = result.choices[0]
        .finish_reason
        .as_ref()
        .map(|v| v.to_string())
        .unwrap_or_default();
    assert_eq!(
        result.choices.len(),
        1,
        "expected exactly 1 elements, got {}",
        result.choices.len()
    );
    assert_eq!(
        _choices_0_message_content.to_string().as_str().trim(),
        r#"Hi there!"#,
        "equals assertion failed"
    );
    assert_eq!(
        _choices_0_finish_reason.to_string().as_str().trim(),
        r#"stop"#,
        "equals assertion failed"
    );
    assert_eq!(
        result.model.to_string().as_str().trim(),
        r#"local-model"#,
        "equals assertion failed"
    );
}

#[tokio::test]
async fn test_extra_headers() {
    // Client configured with extra custom headers successfully completes a chat request
    let mock_route = MockRoute {
        path: "/chat/completions",
        method: "POST",
        status: 200,
        body: r#"{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello! How can I help you?","role":"assistant"}}],"created":1711000140,"id":"chatcmpl-headers001","model":"gpt-4","object":"chat.completion","usage":{"completion_tokens":8,"prompt_tokens":8,"total_tokens":16}}"#.to_string(),
        is_streaming: false,
        stream_chunks: vec![],
        headers: vec![
        ],
        delay_ms: None,
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json: serde_json::Value =
        serde_json::from_str(r#"{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}"#).unwrap();
    let request = serde_json::from_value(request_json).unwrap();
    let client =
        liter_llm::create_client("test-key".to_string(), Some(mock_server.url.clone()), None, None, None).unwrap();
    let result = client.chat(request).await.expect("should succeed");
    let _choices_0_finish_reason = result.choices[0]
        .finish_reason
        .as_ref()
        .map(|v| v.to_string())
        .unwrap_or_default();
    assert_eq!(
        result.choices.len(),
        1,
        "expected exactly 1 elements, got {}",
        result.choices.len()
    );
    assert_eq!(
        _choices_0_finish_reason.to_string().as_str().trim(),
        r#"stop"#,
        "equals assertion failed"
    );
}

#[tokio::test]
async fn test_local_provider_llamacpp() {
    // llamacpp local provider routes requests via llamacpp/ model prefix with no auth
    let mock_route = MockRoute {
        path: "/chat/completions",
        method: "POST",
        status: 200,
        body: r#"{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hi there! I'm running locally.","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-llamacpp-001","model":"my-model","object":"chat.completion","usage":{"completion_tokens":6,"prompt_tokens":5,"total_tokens":11}}"#.to_string(),
        is_streaming: false,
        stream_chunks: vec![],
        headers: vec![
        ],
        delay_ms: None,
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json: serde_json::Value =
        serde_json::from_str(r#"{"messages":[{"content":"Hello","role":"user"}],"model":"llamacpp/my-model"}"#)
            .unwrap();
    let request = serde_json::from_value(request_json).unwrap();
    let client =
        liter_llm::create_client("test-key".to_string(), Some(mock_server.url.clone()), None, None, None).unwrap();
    let result = client.chat(request).await.expect("should succeed");
    let _choices_0_message_content = result.choices[0]
        .message
        .content
        .as_ref()
        .map(|v| v.to_string())
        .unwrap_or_default();
    let _choices_0_finish_reason = result.choices[0]
        .finish_reason
        .as_ref()
        .map(|v| v.to_string())
        .unwrap_or_default();
    assert_eq!(
        result.choices.len(),
        1,
        "expected exactly 1 elements, got {}",
        result.choices.len()
    );
    assert_eq!(
        _choices_0_message_content.to_string().as_str().trim(),
        r#"Hi there! I'm running locally."#,
        "equals assertion failed"
    );
    assert_eq!(
        _choices_0_finish_reason.to_string().as_str().trim(),
        r#"stop"#,
        "equals assertion failed"
    );
    assert_eq!(
        result.model.to_string().as_str().trim(),
        r#"my-model"#,
        "equals assertion failed"
    );
}

#[tokio::test]
async fn test_local_provider_ollama() {
    // Ollama local provider routes requests via ollama/ model prefix with no auth
    let mock_route = MockRoute {
        path: "/chat/completions",
        method: "POST",
        status: 200,
        body: r#"{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello! How can I help you today?","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-ollama-001","model":"qwen2:0.5b","object":"chat.completion","usage":{"completion_tokens":8,"prompt_tokens":5,"total_tokens":13}}"#.to_string(),
        is_streaming: false,
        stream_chunks: vec![],
        headers: vec![
        ],
        delay_ms: None,
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json: serde_json::Value =
        serde_json::from_str(r#"{"messages":[{"content":"Hello","role":"user"}],"model":"ollama/qwen2:0.5b"}"#)
            .unwrap();
    let request = serde_json::from_value(request_json).unwrap();
    let client =
        liter_llm::create_client("test-key".to_string(), Some(mock_server.url.clone()), None, None, None).unwrap();
    let result = client.chat(request).await.expect("should succeed");
    let _choices_0_message_content = result.choices[0]
        .message
        .content
        .as_ref()
        .map(|v| v.to_string())
        .unwrap_or_default();
    let _choices_0_finish_reason = result.choices[0]
        .finish_reason
        .as_ref()
        .map(|v| v.to_string())
        .unwrap_or_default();
    assert_eq!(
        result.choices.len(),
        1,
        "expected exactly 1 elements, got {}",
        result.choices.len()
    );
    assert_eq!(
        _choices_0_message_content.to_string().as_str().trim(),
        r#"Hello! How can I help you today?"#,
        "equals assertion failed"
    );
    assert_eq!(
        _choices_0_finish_reason.to_string().as_str().trim(),
        r#"stop"#,
        "equals assertion failed"
    );
    assert_eq!(
        result.model.to_string().as_str().trim(),
        r#"qwen2:0.5b"#,
        "equals assertion failed"
    );
}

#[tokio::test]
async fn test_local_provider_vllm() {
    // vLLM local provider routes requests via vllm/ model prefix with no auth
    let mock_route = MockRoute {
        path: "/chat/completions",
        method: "POST",
        status: 200,
        body: r#"{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"Hello! How may I assist you?","role":"assistant"}}],"created":1711000000,"id":"chatcmpl-vllm-001","model":"meta-llama/Llama-3.2-1B","object":"chat.completion","usage":{"completion_tokens":7,"prompt_tokens":5,"total_tokens":12}}"#.to_string(),
        is_streaming: false,
        stream_chunks: vec![],
        headers: vec![
        ],
        delay_ms: None,
    };
    let mock_server = MockServer::start(vec![mock_route]).await;
    let request_json: serde_json::Value = serde_json::from_str(
        r#"{"messages":[{"content":"Hello","role":"user"}],"model":"vllm/meta-llama/Llama-3.2-1B"}"#,
    )
    .unwrap();
    let request = serde_json::from_value(request_json).unwrap();
    let client =
        liter_llm::create_client("test-key".to_string(), Some(mock_server.url.clone()), None, None, None).unwrap();
    let result = client.chat(request).await.expect("should succeed");
    let _choices_0_message_content = result.choices[0]
        .message
        .content
        .as_ref()
        .map(|v| v.to_string())
        .unwrap_or_default();
    let _choices_0_finish_reason = result.choices[0]
        .finish_reason
        .as_ref()
        .map(|v| v.to_string())
        .unwrap_or_default();
    assert_eq!(
        result.choices.len(),
        1,
        "expected exactly 1 elements, got {}",
        result.choices.len()
    );
    assert_eq!(
        _choices_0_message_content.to_string().as_str().trim(),
        r#"Hello! How may I assist you?"#,
        "equals assertion failed"
    );
    assert_eq!(
        _choices_0_finish_reason.to_string().as_str().trim(),
        r#"stop"#,
        "equals assertion failed"
    );
    assert_eq!(
        result.model.to_string().as_str().trim(),
        r#"meta-llama/Llama-3.2-1B"#,
        "equals assertion failed"
    );
}
