<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9b5eafb0ca2501223c925331f9aff100a729336d5313915dde05604685335acc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef


declare(strict_types=1);

namespace Liter\Llm\E2e;

use PHPUnit\Framework\TestCase;
use Liter\Llm\LiterLlm;
/** E2e tests for category: search. */
final class SearchTest extends TestCase
{

    /** Basic web search request with a simple query */
    public function test_search_basic(): void
    {        $client = \Liter\Llm\LiterLlm::createClient('test-key');        $this->expectNotToPerformAssertions();        $result = $client->search(null);
    }


    /** Web search with a query that returns no results */
    public function test_search_empty_results(): void
    {        $client = \Liter\Llm\LiterLlm::createClient('test-key');        $this->expectNotToPerformAssertions();        $result = $client->search(null);
    }


    /** 400 Bad Request error when search query is empty */
    public function test_search_error_400(): void
    {        $client = \Liter\Llm\LiterLlm::createClient('test-key');        $this->expectException(\Exception::class);
        $client->search(null);    }


    /** 401 Unauthorized error on web search due to invalid API credentials */
    public function test_search_error_401(): void
    {        $client = \Liter\Llm\LiterLlm::createClient('test-key');        $this->expectException(\Exception::class);
        $client->search(null);    }


    /** Search request with max_results parameter limiting response count */
    public function test_search_with_max_results(): void
    {        $client = \Liter\Llm\LiterLlm::createClient('test-key');        $result = $client->search(null);
            $this->assertCount(2, $result->results);
    }

}
