// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4f11fc587d243af0c8451b4b98793b0b63c631a2d3bf02c20565ad211a0cf218
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import LiterLlm
import RustBridge

/// E2e tests for category: parity.
final class ParityTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _existing = ProcessInfo.processInfo.environment["SUT_URL"]
    }

    func testApiSurfaceParity() async throws {
        // Canonical API surface definition for cross-binding parity verification
        let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4o\"}")
        let _client = try createClient(apiKey: "test-key", baseUrl: AlefE2EMockServer.baseURL + "/fixtures/api_surface_parity")
        let result = try await _client.chat(_request)
    }

}
