// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5528d5d40f0aa94864b45d1800e50930265ad49915a23cb1e0b866011c733ba1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
		setupFiles: ["./setup.ts"],
	},
});
