// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e63bf505dcedc72231e2889298246c72a323b3562fdb5471edc78db8405c9130
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package com.github.kreuzberg_dev.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import CreateImageRequest

/** E2e tests for category: image-generate. */
class ImageGenerateTest {

    companion object {
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module())
    }
    @Test
    fun testEdgeImageB64Response() {
        // Image generation returning base64-encoded data instead of URL
        val request = MAPPER.readValue("{\"model\":\"dall-e-3\",\"n\":1,\"prompt\":\"A blue circle\",\"response_format\":\"b64_json\",\"size\":\"1024x1024\"}", CreateImageRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getenv("MOCK_SERVER_URL") + "/fixtures/edge_image_b64_response")
        val result = client.imageGenerate(request)
        assertEquals(1, result.data().size, "expected exactly 1 elements")
        assertFalse(result.data().first().b64Json().orEmpty().isEmpty(), "expected non-empty value")
        client.close()
    }

    @Test
    fun testEdgeImageEmptyPrompt() {
        // Image generation with an empty prompt returns 400
        val request = MAPPER.readValue("{\"model\":\"dall-e-3\",\"n\":1,\"prompt\":\"\",\"size\":\"1024x1024\"}", CreateImageRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getenv("MOCK_SERVER_URL") + "/fixtures/edge_image_empty_prompt")
        assertFailsWith<Exception> {
            client.imageGenerate(request)
        }
        client.close()
    }

    @Test
    fun testEdgeImageMultipleN() {
        // Image generation requesting multiple images with n=3
        val request = MAPPER.readValue("{\"model\":\"dall-e-3\",\"n\":3,\"prompt\":\"A cat\"}", CreateImageRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getenv("MOCK_SERVER_URL") + "/fixtures/edge_image_multiple_n")
        val result = client.imageGenerate(request)
        assertEquals(3, result.data().size, "expected exactly 3 elements")
        assertFalse(result.data().first().url().orEmpty().isEmpty(), "expected non-empty value")
        assertFalse(result.data().get(1).url().orEmpty().isEmpty(), "expected non-empty value")
        assertFalse(result.data().get(2).url().orEmpty().isEmpty(), "expected non-empty value")
        client.close()
    }

    @Test
    fun testErrorImageAuth401() {
        // 401 Unauthorized when generating images with invalid API key
        val request = MAPPER.readValue("{\"model\":\"dall-e-3\",\"n\":1,\"prompt\":\"A cat\",\"size\":\"1024x1024\"}", CreateImageRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getenv("MOCK_SERVER_URL") + "/fixtures/error_image_auth_401")
        assertFailsWith<Exception> {
            client.imageGenerate(request)
        }
        client.close()
    }

    @Test
    fun testErrorImageBadRequest() {
        // 400 Bad Request when image generation parameters are invalid
        val request = MAPPER.readValue("{\"model\":\"dall-e-3\",\"n\":1,\"prompt\":\"A cat\",\"size\":\"9999x9999\"}", CreateImageRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getenv("MOCK_SERVER_URL") + "/fixtures/error_image_bad_request")
        assertFailsWith<Exception> {
            client.imageGenerate(request)
        }
        client.close()
    }

    @Test
    fun testErrorImageRateLimit() {
        // 429 Rate limit exceeded for image generation
        val request = MAPPER.readValue("{\"model\":\"dall-e-3\",\"n\":1,\"prompt\":\"A cat\",\"size\":\"1024x1024\"}", CreateImageRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getenv("MOCK_SERVER_URL") + "/fixtures/error_image_rate_limit")
        assertFailsWith<Exception> {
            client.imageGenerate(request)
        }
        client.close()
    }

    @Test
    fun testSmokeImageBasic() {
        // Basic image generation with a text prompt
        val request = MAPPER.readValue("{\"model\":\"dall-e-3\",\"n\":1,\"prompt\":\"A white cat sitting on a windowsill\",\"size\":\"1024x1024\"}", CreateImageRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getenv("MOCK_SERVER_URL") + "/fixtures/smoke_image_basic")
        val result = client.imageGenerate(request)
        assertEquals(1, result.data().size, "expected exactly 1 elements")
        assertFalse(result.data().first().url().orEmpty().isEmpty(), "expected non-empty value")
        client.close()
    }

    @Test
    fun testSmokeImageMultiple() {
        // Image generation requesting multiple images
        val request = MAPPER.readValue("{\"model\":\"dall-e-2\",\"n\":3,\"prompt\":\"A red bicycle\",\"size\":\"256x256\"}", CreateImageRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getenv("MOCK_SERVER_URL") + "/fixtures/smoke_image_multiple")
        val result = client.imageGenerate(request)
        assertEquals(3, result.data().size, "expected exactly 3 elements")
        assertFalse(result.data().first().url().orEmpty().isEmpty(), "expected non-empty value")
        client.close()
    }

    @Test
    fun testSmokeImageWithSize() {
        // Image generation with explicit size parameter
        val request = MAPPER.readValue("{\"model\":\"dall-e-3\",\"n\":1,\"prompt\":\"A sunset over mountains\",\"size\":\"1792x1024\"}", CreateImageRequest::class.java)
        val client = LiterLlm.createClient(apiKey = "test-key", baseUrl = System.getenv("MOCK_SERVER_URL") + "/fixtures/smoke_image_with_size")
        val result = client.imageGenerate(request)
        assertEquals(1, result.data().size, "expected exactly 1 elements")
        assertFalse(result.data().first().url().orEmpty().isEmpty(), "expected non-empty value")
        client.close()
    }

}
