# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b3eda6663711187dffbf4813f31ff8d913fa461e6e735872f16c9c2d921e2ff1
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module LiterLlm
  ## The version string for this package.
  VERSION = "2.2.2"
end
