# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:de9738d1a2c1e8c5eacecbd4da06878683f3650e2b3bcc2ce0cb163d94f425f0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
# frozen_string_literal: true

module LiterLlm
  VERSION = "1.4.0.pre.rc.44"
end
