packages: []
allowBuilds:
  esbuild: true
  tree-sitter: true
minimumReleaseAgeExclude:
  - '@kreuzberg/liter-llm-node-darwin-arm64@1.4.0-rc.50'
  - '@kreuzberg/liter-llm-node-darwin-x64@1.4.0-rc.50'
  - '@kreuzberg/liter-llm-node-linux-arm64-gnu@1.4.0-rc.50'
  - '@kreuzberg/liter-llm-node-linux-x64-gnu@1.4.0-rc.50'
  - '@kreuzberg/liter-llm-node-win32-arm64-msvc@1.4.0-rc.50'
  - '@kreuzberg/liter-llm-node-win32-x64-msvc@1.4.0-rc.50'
  - '@kreuzberg/liter-llm-node@1.4.0-rc.50'
