// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a7c064e23690d6da0a7c0734d1219488b1ca34c78c93e3287518f9c69d67f638
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
	},
});
