// Generated by alef. Do not edit by hand.
// alef:hash:52effca2513e1c5f8a9a5b90a372d645388de4b92e4f822acc38d97502c322b6
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
)

package dev.kreuzberg.literllm.android

/** Query parameters for listing batches. */
data class BatchListQuery(
    /** Maximum number of results to return. Defaults to 20. */
    val limit: Int? = null,
    /** Pagination cursor: return results after this batch ID. */
    val after: String? = null,
)
