// Generated by alef. Do not edit by hand.

package dev.kreuzberg.literllm.android

data class BatchListResponse(
    val `object`: String,
    val data: List<BatchObject>,
    val hasMore: Boolean?,
    val firstId: String?,
    val lastId: String?,
)
