// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
)

package dev.kreuzberg.literllm.android

/** The lifecycle stage at which a guardrail runs. */
enum class GuardrailStage {
    /** The outgoing prompt / request, before forwarding to the upstream provider. */
    @com.fasterxml.jackson.annotation.JsonProperty("Input") INPUT,
    /** The full response from the upstream provider (non-streaming). */
    @com.fasterxml.jackson.annotation.JsonProperty("Output") OUTPUT,
    /**
     * A single chunk in a streaming response. Guardrails here are called once
     * per chunk and may block or mutate individual chunks.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("OutputChunk") OUTPUT_CHUNK;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            INPUT -> "Input"
            OUTPUT -> "Output"
            OUTPUT_CHUNK -> "OutputChunk"
        }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): GuardrailStage =
            when (value) {
                "Input",
                "input" -> INPUT
                "Output",
                "output" -> OUTPUT
                "OutputChunk",
                "outputchunk" -> OUTPUT_CHUNK
                else -> throw IllegalArgumentException("Unknown GuardrailStage value: $value")
            }
    }
}
