// Generated by alef. Do not edit by hand.

package dev.kreuzberg.literllm.android

object LiterLlmBridge {
    init {
        System.loadLibrary("literllm_jni")
    }

    external fun nativeCreateClient(apiKey: String, baseUrl: String, timeoutSecs: Long, maxRetries: Int, modelHint: String): String

    external fun nativeCreateClientFromJson(json: String): String

    external fun nativeRegisterCustomProvider(config: String): Unit

    external fun nativeUnregisterCustomProvider(name: String): Boolean

    // JNI streaming external funs — implementations are Rust JNI shims.

    // Streaming JNI externs for DefaultClient.chatStream
    external fun nativeDefaultClientChatStreamStart(clientHandle: Long, requestJson: String): Long

    external fun nativeDefaultClientChatStreamNext(streamHandle: Long): String?

    external fun nativeDefaultClientChatStreamFree(streamHandle: Long)
}
