// Generated by alef. Do not edit by hand.
// alef:hash:fec9b44a56d9714b7b12931bb48e1e8f6d57ef2d0ccaad1f9ac6046ce01a89af
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package dev.kreuzberg.literllm.android

/** Response from the moderation endpoint. */
data class ModerationResponse(
    /** Unique identifier for this moderation request. */
    val id: String,
    /** Model used for classification. */
    val model: String,
    /** Results for each input string. */
    val results: List<ModerationResult> = emptyList(),
)
