// Generated by alef. Do not edit by hand.
// alef:hash:1213a045f6c720bcab8727df8faa87409c027be1ac51394a1bf33f9c83c5d07c
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package dev.kreuzberg.literllm.android

/** Controls how much reasoning effort the model should use. */
enum class ReasoningEffort {
    @com.fasterxml.jackson.annotation.JsonProperty("low") LOW,
    @com.fasterxml.jackson.annotation.JsonProperty("medium") MEDIUM,
    @com.fasterxml.jackson.annotation.JsonProperty("high") HIGH;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            LOW -> "low"
            MEDIUM -> "medium"
            HIGH -> "high"
        }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): ReasoningEffort =
            when (value) {
                "low" -> LOW
                "medium" -> MEDIUM
                "high" -> HIGH
                else -> throw IllegalArgumentException("Unknown ReasoningEffort value: $value")
            }
    }
}
