// Generated by alef. Do not edit by hand.
// alef:hash:4685b97575f1ddb0a83554a97b65aa5936283420ed37f567b82618c4e3de7d0d
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package dev.kreuzberg.literllm.android

/** Response from a structured response request. */
data class ResponseObject(
    /** Unique response ID. */
    val id: String = "",
    /** Object type (e.g., `"response"`). */
    val `object`: String = "",
    /** Unix timestamp of response creation. */
    val createdAt: Long = 0L,
    /** Model used to generate the response. */
    val model: String = "",
    /** Status (e.g., `"succeeded"`, `"failed"`). */
    val status: String = "",
    /** Output items from the response. */
    val output: List<ResponseOutputItem> = emptyList(),
    /** Token usage. */
    val usage: ResponseUsage? = null,
    /** Error details (if status is "failed"). */
    val error: Any? = null,
)
