// Generated by alef. Do not edit by hand.
// alef:hash:718a9bb2066b4d98f177745b5c3db63c834a58163b5677360c01f624add6c233
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package dev.kreuzberg.literllm.android

/** A segment of transcribed audio with timing information. */
data class TranscriptionSegment(
    /** Segment index (0-based). */
    val id: Int = 0,
    /** Start time in seconds. */
    val start: Double = 0.0,
    /** End time in seconds. */
    val end: Double = 0.0,
    /** Transcribed text for this segment. */
    val text: String = "",
)
