// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a359572bfa836b8765aadedcf1e4d8e8f36d0d8aa2de66b4a05f0125f12b6a99
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed record AssistantMessage
{
    [JsonPropertyName("content")]
    public string? Content { get; init; } = null;

    [JsonPropertyName("name")]
    public string? Name { get; init; } = null;

    [JsonPropertyName("tool_calls")]
    public List<ToolCall>? ToolCalls { get; init; } = null;

    [JsonPropertyName("refusal")]
    public string? Refusal { get; init; } = null;

    /// <summary>
    /// Deprecated legacy function_call field; retained for API compatibility.
    /// </summary>
    [JsonPropertyName("function_call")]
    public FunctionCall? FunctionCall { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="AssistantMessage"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static AssistantMessage FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<AssistantMessage>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse AssistantMessage from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse AssistantMessage from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
