// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a7c064e23690d6da0a7c0734d1219488b1ca34c78c93e3287518f9c69d67f638
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// `status` preserves the exact HTTP status code received (401 or 403).
/// </summary>
public class AuthenticationException : LiterLlmErrorException
{
    public AuthenticationException(string message) : base(message) { }

    public AuthenticationException(string message, Exception innerException) : base(message, innerException) { }
}
