// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0ad579c4e6402a59f477d57e2df40488d9809a1a212e52fe47279587ff8c442e
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;
/// <summary>
/// How the API key is sent in the HTTP request.
/// </summary>
[JsonConverter(typeof(AuthHeaderFormatJsonConverter))]
public enum AuthHeaderFormat
{
    /// <summary>
    /// Bearer token: `Authorization: Bearer &lt;key&gt;`
    /// </summary>
    [JsonPropertyName("bearer")]
    Bearer,
    /// <summary>
    /// Custom header: e.g., `X-Api-Key: &lt;key&gt;`
    /// </summary>
    [JsonPropertyName("apikey")]
    ApiKey,
    /// <summary>
    /// No authentication required.
    /// </summary>
    [JsonPropertyName("none")]
    None,
}


/// <summary>
/// Custom JSON converter for <see cref="AuthHeaderFormat"/> that respects explicit variant names.
/// </summary>
internal sealed class AuthHeaderFormatJsonConverter : JsonConverter<AuthHeaderFormat>
{
    public override AuthHeaderFormat Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "bearer" => AuthHeaderFormat.Bearer,
            "apikey" => AuthHeaderFormat.ApiKey,
            "none" => AuthHeaderFormat.None,
            _ => throw new JsonException($"Unknown AuthHeaderFormat value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, AuthHeaderFormat value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            AuthHeaderFormat.Bearer => "bearer",
            AuthHeaderFormat.ApiKey => "apikey",
            AuthHeaderFormat.None => "none",
            _ => throw new JsonException($"Unknown AuthHeaderFormat value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
