// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7587d0d838df0bac8da1b7d6b2b4e17f1102dcc85b4a0ecadfe8cc9beb2c6c94
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// `status` preserves the exact HTTP status code received (401 or 403).
/// </summary>
public class AuthenticationException : LiterLlmErrorException
{
    public AuthenticationException(string message) : base(message) { }

    public AuthenticationException(string message, Exception innerException) : base(message, innerException) { }
}
