// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e9882a689a6daca4df0d2c4fe803319cb639d4c6852371d04800d5c48a10d7dd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Response from listing batches.
/// </summary>
public sealed record BatchListResponse
{
    /// <summary>
    /// Object type (always `"list"`).
    /// </summary>
    [JsonPropertyName("object")]
    public string Object { get; init; } = "";

    /// <summary>
    /// List of batch objects.
    /// </summary>
    [JsonPropertyName("data")]
    public List<BatchObject> Data { get; init; } = [];

    /// <summary>
    /// Whether more results are available.
    /// </summary>
    [JsonPropertyName("has_more")]
    public bool? HasMore { get; init; } = null;

    /// <summary>
    /// First batch ID in the result set (for pagination).
    /// </summary>
    [JsonPropertyName("first_id")]
    public string? FirstId { get; init; } = null;

    /// <summary>
    /// Last batch ID in the result set (for pagination).
    /// </summary>
    [JsonPropertyName("last_id")]
    public string? LastId { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="BatchListResponse"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static BatchListResponse FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<BatchListResponse>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse BatchListResponse from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse BatchListResponse from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
