// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ee34d53dd7b53bbfa1e1d683dc961e1355a375403d7bca2db0da948bbbf6d364
#nullable enable

using System;

namespace LiterLlm;

public class BudgetExceededException : LiterLlmErrorException
{
    public BudgetExceededException(string message) : base(message) { }

    public BudgetExceededException(string message, Exception innerException) : base(message, innerException) { }
}
