// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:07562382b502a5b7ab1c75b472a27ccfc096d0dfe06c87c012ca58af37b50df9
#nullable enable

using System;

namespace LiterLlm;

public class ContentPolicyException : LiterLlmErrorException
{
    public ContentPolicyException(string message) : base(message) { }

    public ContentPolicyException(string message, Exception innerException) : base(message, innerException) { }
}
