// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c892c5ad61c5b9376089e0d461b22e97ed9f5766653c5d3c2e5bf8cca5950f37
#nullable enable

using System;

namespace LiterLlm;

public class ContextWindowExceededException : LiterLlmErrorException
{
    public ContextWindowExceededException(string message) : base(message) { }

    public ContextWindowExceededException(string message, Exception innerException) : base(message, innerException) { }
}
