// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:59c495669f8ec6ad972607559abc9a61dbcc34f725deeb4c2e6dadb7b7b642aa
#nullable enable

using System;

namespace LiterLlm;

public class ContentPolicyException : LiterLlmErrorException
{
    public ContentPolicyException(string message) : base(message) { }

    public ContentPolicyException(string message, Exception innerException) : base(message, innerException) { }
}
