// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fec9b44a56d9714b7b12931bb48e1e8f6d57ef2d0ccaad1f9ac6046ce01a89af
#nullable enable

using System;

namespace LiterLlm;

public class ContentPolicyException : LiterLlmErrorException
{
    public ContentPolicyException(string message) : base(message) { }

    public ContentPolicyException(string message, Exception innerException) : base(message, innerException) { }
}
