// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3e0a63de553a5b44d0f9ed87655e92d82d366db320b3294f438fd78b284f540f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class CreateFileRequest
{
    /// <summary>
    /// Base64-encoded file data.
    /// </summary>
    [JsonPropertyName("file")]
    public string File { get; set; } = "";

    [JsonConverter(typeof(FilePurposeJsonConverter))]
    [JsonPropertyName("purpose")]
    public FilePurpose? Purpose { get; set; } = null;

    [JsonPropertyName("filename")]
    public string? Filename { get; set; } = null;


    /// <summary>
    /// Parse a <see cref="CreateFileRequest"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static CreateFileRequest FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<CreateFileRequest>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse CreateFileRequest from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse CreateFileRequest from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
