// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2883fe213ab8ec97b1af1181f3a43676aa4d2a33a9ab666ac20a1f330d85d96c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class CreateFileRequest
{
    /// <summary>
    /// Base64-encoded file data.
    /// </summary>
    [JsonPropertyName("file")]
    public string File { get; set; } = "";

    [JsonPropertyName("purpose")]
    public FilePurpose? Purpose { get; set; } = null;

    [JsonPropertyName("filename")]
    public string? Filename { get; set; } = null;

}
