// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c06267848fa940f8f6e68ce1c46d0368928b2a52fcecfb29cc3c2a8af4e08914
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Request to generate speech audio from text.
/// </summary>
public sealed class CreateSpeechRequest
{
    [JsonPropertyName("model")]
    public string Model { get; set; } = "";

    [JsonPropertyName("input")]
    public string Input { get; set; } = "";

    [JsonPropertyName("voice")]
    public string Voice { get; set; } = "";

    [JsonPropertyName("response_format")]
    public string? ResponseFormat { get; set; } = null;

    [JsonPropertyName("speed")]
    public double? Speed { get; set; } = null;

}
