// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5a8e64e48f888fa2f4e789d7199765ac512b9b1e663320af2e8db83d53d1a4dc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Response from a delete operation.
/// </summary>
public sealed record DeleteResponse
{
    /// <summary>
    /// ID of the deleted resource.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = "";

    /// <summary>
    /// Object type.
    /// </summary>
    [JsonPropertyName("object")]
    public string Object { get; init; } = "";

    /// <summary>
    /// Confirmation that the resource was deleted.
    /// </summary>
    [JsonPropertyName("deleted")]
    public bool Deleted { get; init; } = false;


    /// <summary>
    /// Parse a <see cref="DeleteResponse"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static DeleteResponse FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<DeleteResponse>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse DeleteResponse from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse DeleteResponse from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
