// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5ab53abee9ad8a282dfd709d969c3cf38af90f6c41a33626ee0612732e7f3b65
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// PDF/document content part for vision-capable models.
/// </summary>
public sealed record DocumentContent
{
    /// <summary>
    /// Base64-encoded document data or URL.
    /// </summary>
    [JsonPropertyName("data")]
    public string Data { get; init; } = "";

    /// <summary>
    /// MIME type (e.g., "application/pdf", "text/csv").
    /// </summary>
    [JsonPropertyName("media_type")]
    public string MediaType { get; init; } = "";


    /// <summary>
    /// Parse a <see cref="DocumentContent"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static DocumentContent FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<DocumentContent>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse DocumentContent from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse DocumentContent from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
