// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4317a42a5b2fe41ab0562c51318dfefb3d72f385025144daeb112fc4354d0001
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://example.invalid/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class EmbeddingResponse
{
    /// <summary>
    /// Always `"list"` from OpenAI-compatible APIs.  Stored as a plain
    /// `String` so non-standard provider values do not break deserialization.
    /// </summary>
    [JsonPropertyName("object")]
    public string Object { get; set; } = "";

    [JsonPropertyName("data")]
    public List<EmbeddingObject> Data { get; set; } = [];

    [JsonPropertyName("model")]
    public string Model { get; set; } = "";

    [JsonPropertyName("usage")]
    public Usage? Usage { get; set; } = null;


    /// <summary>
    /// Parse a <see cref="EmbeddingResponse"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static EmbeddingResponse FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<EmbeddingResponse>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse EmbeddingResponse from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse EmbeddingResponse from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
