// This file is auto-generated by alef. DO NOT EDIT.
<<<<<<< Updated upstream
// alef:hash:fe64a8a06beeb01b5344005fa07dcdfdf3e244d772ace0f89dbba84b0541ca2d
=======
// alef:hash:ff0e10ad47404c645f09678fc9db55fb107af1c70816902b56b45b49d59c3b3b
>>>>>>> Stashed changes
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;
/// <summary>
/// How budget limits are enforced.
/// </summary>
[JsonConverter(typeof(EnforcementJsonConverter))]
public enum Enforcement
{
    /// <summary>
    /// Reject requests that would exceed the budget with
    /// `LiterLlmError.BudgetExceeded`.
    /// </summary>
    [JsonPropertyName("Hard")]
    Hard,
    /// <summary>
    /// Allow requests through but emit a `tracing.warn!` when the budget is
    /// exceeded.
    /// </summary>
    [JsonPropertyName("Soft")]
    Soft,
}


/// <summary>
/// Custom JSON converter for <see cref="Enforcement"/> that respects explicit variant names.
/// </summary>
internal sealed class EnforcementJsonConverter : JsonConverter<Enforcement>
{
    public override Enforcement Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "Hard" => Enforcement.Hard,
            "Soft" => Enforcement.Soft,
            _ => throw new JsonException($"Unknown Enforcement value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, Enforcement value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            Enforcement.Hard => "Hard",
            Enforcement.Soft => "Soft",
            _ => throw new JsonException($"Unknown Enforcement value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
