// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:658954d5770e862e74a49f152d2abe2bfbfe649545187781c64e53e0a266cc7a
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

[JsonConverter(typeof(FilePurposeJsonConverter))]
public enum FilePurpose
{
    [JsonPropertyName("assistants")]
    Assistants, [JsonPropertyName("batch")]
    Batch, [JsonPropertyName("fine-tune")]
    FineTune, [JsonPropertyName("vision")]
    Vision,
}


/// <summary>Custom JSON converter for <see cref="FilePurpose"/> that respects explicit variant names.</summary>
internal sealed class FilePurposeJsonConverter : JsonConverter<FilePurpose>
{
    public override FilePurpose Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "assistants" => FilePurpose.Assistants,
            "batch" => FilePurpose.Batch,
            "fine-tune" => FilePurpose.FineTune,
            "vision" => FilePurpose.Vision,
            _ => throw new JsonException($"Unknown FilePurpose value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, FilePurpose value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            FilePurpose.Assistants => "assistants",
            FilePurpose.Batch => "batch",
            FilePurpose.FineTune => "fine-tune",
            FilePurpose.Vision => "vision",
            _ => throw new JsonException($"Unknown FilePurpose value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
