// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:89085e0432911b973a4e6d2b4e0624a3687516eca7e6521033be273fe96393a4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed record FunctionDefinition
{
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    [JsonPropertyName("description")]
    public string? Description { get; init; } = null;

    [JsonPropertyName("parameters")]
    public object? Parameters { get; init; } = null;

    [JsonPropertyName("strict")]
    public bool? Strict { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="FunctionDefinition"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static FunctionDefinition FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<FunctionDefinition>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse FunctionDefinition from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse FunctionDefinition from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
