// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b159ec7bf40f2249b9f5696d5819688bca2310a2b26cc9acae8194e6255f8b03
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;
/// <summary>
/// The result of a single health probe.
/// </summary>
[JsonConverter(typeof(HealthStatusJsonConverter))]
public enum HealthStatus
{
    /// <summary>
    /// The probe succeeded; the upstream is reachable.
    /// </summary>
    [JsonPropertyName("Healthy")]
    Healthy,
    /// <summary>
    /// The probe failed; the upstream may be down.
    /// </summary>
    [JsonPropertyName("Unhealthy")]
    Unhealthy,
}


/// <summary>
/// Custom JSON converter for <see cref="HealthStatus"/> that respects explicit variant names.
/// </summary>
internal sealed class HealthStatusJsonConverter : JsonConverter<HealthStatus>
{
    public override HealthStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "Healthy" => HealthStatus.Healthy,
            "Unhealthy" => HealthStatus.Unhealthy,
            _ => throw new JsonException($"Unknown HealthStatus value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, HealthStatus value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            HealthStatus.Healthy => "Healthy",
            HealthStatus.Unhealthy => "Unhealthy",
            _ => throw new JsonException($"Unknown HealthStatus value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
