// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7d3f624f57c1702127cb98f96fa4ef10d6301893435733f33778e73f6dcfadc8
#nullable enable

using System;

namespace LiterLlm;

public class HookRejectedException : LiterLlmErrorException
{
    public HookRejectedException(string message) : base(message) { }

    public HookRejectedException(string message, Exception innerException) : base(message, innerException) { }
}
