// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:43b77fe87feffdf58bb80f1d37f77f01c0f5bd65dc381a68cc8825f11a95ff9b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// An intent prototype: `(intent_name, prototype_embedding, target_model_id)`.
/// </summary>
public sealed record IntentPrototype
{
    /// <summary>
    /// Human-readable name for the intent (used in logs/metrics).
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// Pre-computed embedding vector for this intent.
    /// </summary>
    [JsonPropertyName("embedding")]
    public List<double> Embedding { get; init; } = [];

    /// <summary>
    /// Model to route to when this intent is detected.
    /// </summary>
    [JsonPropertyName("model")]
    public required string Model { get; init; }


    /// <summary>
    /// Parse a <see cref="IntentPrototype"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static IntentPrototype FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<IntentPrototype>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse IntentPrototype from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse IntentPrototype from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
