// This file is auto-generated by alef. DO NOT EDIT.
#nullable enable

using System;

namespace LiterLlm;

public class InvalidHeaderException : LiterLlmErrorException
{
    public InvalidHeaderException(string message) : base(message) { }

    public InvalidHeaderException(string message, Exception innerException) : base(message, innerException) { }
}
