// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9681a88ae8c306325543fa262ce090a530bd2d48a069ee7baccfdc249d75e7dd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class JsonSchemaFormat
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("description")]
    public string? Description { get; set; } = null;

    [JsonPropertyName("schema")]
    public object? Schema { get; set; } = null;

    [JsonPropertyName("strict")]
    public bool? Strict { get; set; } = null;

}
