// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f45f0223f4a76b2854aad7f67a0054ea2425535c9f7bb4b58ac8ddaf0fc221a3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://example.invalid/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class JsonSchemaFormat
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("description")]
    public string? Description { get; set; } = null;

    [JsonPropertyName("schema")]
    public object? Schema { get; set; } = null;

    [JsonPropertyName("strict")]
    public bool? Strict { get; set; } = null;


    /// <summary>
    /// Parse a <see cref="JsonSchemaFormat"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static JsonSchemaFormat FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<JsonSchemaFormat>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse JsonSchemaFormat from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse JsonSchemaFormat from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
