// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7d27ea325f01370c90a3ed4e3b6ba638c9a00e4d9cb79c611bc50720bcb24d86
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// All errors that can occur when using `liter-llm`.
///
/// Each variant carries a stable numeric `error_code` (&gt;= 100) that bindings expose
/// across the FFI boundary. Codes are append-only: never renumber or reuse a code.
/// </summary>
public class LiterLlmErrorException : LiterLlmException
{
    /// <summary>Returns the canonical HTTP status code associated with this error. Maps error variants to their originating HTTP status code as set by the private `from_status` constructor. Used by e2e assertions that check `error.status_code` against the expected HTTP status.</summary>
    public ushort StatusCode { get; private set; }
    /// <summary>Returns the server-advertised retry delay, when the error carries one. Parsed from the upstream `Retry-After` header on a 429.  Exposed as an accessor alongside `Self.status_code` and `Self.error_type` so the generated bindings can surface it: the value reached the Rust core but stopped there, leaving every binding consumer to re-derive its own backoff from nothing more than the status code.</summary>
    public TimeSpan? RetryAfter { get; private set; }
    /// <summary>Returns `true` for errors that are worth retrying on a different service or deployment (transient failures). Used by `FallbackService` and `Router` to decide whether to route to an alternative endpoint.</summary>
    public bool IsTransient { get; private set; }
    /// <summary>Return the OpenTelemetry `error.type` string for this error variant. Used by the tracing middleware to record the `error.type` span attribute on failed requests per the GenAI semantic conventions.</summary>
    public string ErrorType { get; private set; }

    public LiterLlmErrorException(string message) : base(message)
    {
        StatusCode = 0;
        RetryAfter = null;
        IsTransient = false;
        ErrorType = string.Empty;
    }

    public LiterLlmErrorException(string message, Exception innerException) : base(message, innerException)
    {
        StatusCode = 0;
        RetryAfter = null;
        IsTransient = false;
        ErrorType = string.Empty;
    }

    public LiterLlmErrorException(string message, ushort statusCode, bool isTransientFlag, string errorType) : base(message)
    {
        StatusCode = statusCode;
        RetryAfter = null;
        IsTransient = isTransientFlag;
        ErrorType = errorType;
    }

    public LiterLlmErrorException(string message, Exception innerException, ushort statusCode, bool isTransientFlag, string errorType) : base(message, innerException)
    {
        StatusCode = statusCode;
        RetryAfter = null;
        IsTransient = isTransientFlag;
        ErrorType = errorType;
    }

    public LiterLlmErrorException(string message, ushort statusCode, TimeSpan? retryAfter, bool isTransientFlag, string errorType) : base(message)
    {
        StatusCode = statusCode;
        RetryAfter = retryAfter;
        IsTransient = isTransientFlag;
        ErrorType = errorType;
    }

    public LiterLlmErrorException(string message, Exception innerException, ushort statusCode, TimeSpan? retryAfter, bool isTransientFlag, string errorType) : base(message, innerException)
    {
        StatusCode = statusCode;
        RetryAfter = retryAfter;
        IsTransient = isTransientFlag;
        ErrorType = errorType;
    }

    /// <summary>Fills the introspection properties from the native layer's last-error getters; call before any other native call.</summary>
    internal void ApplyLastError()
    {
        StatusCode = NativeMethods.LastErrorStatusCode();
        var retryAfterMillis = NativeMethods.LastErrorRetryAfter();
        RetryAfter = retryAfterMillis < 0 ? null : TimeSpan.FromMilliseconds(retryAfterMillis);
        IsTransient = NativeMethods.LastErrorIsTransient();
        var errorTypePtr = NativeMethods.LastErrorErrorType();
        ErrorType = errorTypePtr == IntPtr.Zero ? string.Empty : global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(errorTypePtr) ?? string.Empty;
    }
}
