// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5f17ebe676822cfa77ea15c5d293e0cac18cf5c5fd2e4c3c2b8974a130abfd16
#nullable enable

using System;

namespace LiterLlm;

public class LiterLlmException : Exception
{
    public int Code { get; }

    public LiterLlmException(int code, string message) : base(message)
    {
        Code = code;
    }

    public LiterLlmException(string message) : base(message)
    {
        Code = 0;
    }

    public LiterLlmException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
