// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3fb07515ba02077671946cad7f111c0c7840343537bb31d1488bc316651dca95
#nullable enable

using System;

namespace LiterLlm;

public class LiterLlmException : Exception
{
    public int Code { get; }

    public LiterLlmException(int code, string message) : base(message)
    {
        Code = code;
    }

    public LiterLlmException(string message) : base(message)
    {
        Code = 0;
    }

    public LiterLlmException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
