// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b00b755e859f902c7100312236ab99a6ba4606d64e8d1d26c06e1a0951ae6ce0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Boolean flags for each moderation category.
/// </summary>
public sealed class ModerationCategories
{
    [JsonPropertyName("sexual")]
    public bool Sexual { get; set; } = false;

    [JsonPropertyName("hate")]
    public bool Hate { get; set; } = false;

    [JsonPropertyName("harassment")]
    public bool Harassment { get; set; } = false;

    [JsonPropertyName("self-harm")]
    public bool SelfHarm { get; set; } = false;

    [JsonPropertyName("sexual/minors")]
    public bool SexualMinors { get; set; } = false;

    [JsonPropertyName("hate/threatening")]
    public bool HateThreatening { get; set; } = false;

    [JsonPropertyName("violence/graphic")]
    public bool ViolenceGraphic { get; set; } = false;

    [JsonPropertyName("self-harm/intent")]
    public bool SelfHarmIntent { get; set; } = false;

    [JsonPropertyName("self-harm/instructions")]
    public bool SelfHarmInstructions { get; set; } = false;

    [JsonPropertyName("harassment/threatening")]
    public bool HarassmentThreatening { get; set; } = false;

    [JsonPropertyName("violence")]
    public bool Violence { get; set; } = false;


    /// <summary>
    /// Parse a <see cref="ModerationCategories"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static ModerationCategories FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<ModerationCategories>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse ModerationCategories from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse ModerationCategories from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
