// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:550d3002da1c487466674fddc0bb59b1dd665819f441a08f5a1bd70fee0f8578
#nullable enable

using System;

namespace LiterLlm;

public class NotFoundException : LiterLlmErrorException
{
    public NotFoundException(string message) : base(message) { }

    public NotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
