// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:529476acf9f0d5e23344d2fbc4cbada0f43e771a411589b6d9ed3fb349af9dd6
#nullable enable

using System;

namespace LiterLlm;

public class NotFoundException : LiterLlmErrorException
{
    public NotFoundException(string message) : base(message) { }

    public NotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
