// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a893cf266c5d7883c5f9fb3f1de2b60369673c481765f5f8328cfa43608d2d06
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// An OCR response.
/// </summary>
public sealed record OcrResponse
{
    /// <summary>
    /// Extracted pages in order.
    /// </summary>
    [JsonPropertyName("pages")]
    public List<OcrPage> Pages { get; init; } = [];

    /// <summary>
    /// Model/provider used for OCR.
    /// </summary>
    [JsonPropertyName("model")]
    public required string Model { get; init; }

    /// <summary>
    /// Token usage, if reported by the provider.
    /// </summary>
    [JsonPropertyName("usage")]
    public Usage? Usage { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="OcrResponse"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static OcrResponse FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<OcrResponse>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse OcrResponse from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse OcrResponse from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
