// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:57535b21913a306c7e789e0bb192e995f3f06e6b296293a404912ccd2df753ac
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// An OCR request.
/// </summary>
public sealed class OcrRequest
{
    /// <summary>
    /// The model/provider to use (e.g. `"mistral/mistral-ocr-latest"`).
    /// </summary>
    [JsonPropertyName("model")]
    public string Model { get; set; } = "";

    /// <summary>
    /// The document to process.
    /// </summary>
    [JsonPropertyName("document")]
    public OcrDocument? Document { get; set; } = null;

    /// <summary>
    /// Specific pages to process (1-indexed). `None` means all pages.
    /// </summary>
    [JsonPropertyName("pages")]
    public List<uint>? Pages { get; set; } = null;

    /// <summary>
    /// Whether to include base64-encoded images of each page.
    /// </summary>
    [JsonPropertyName("include_image_base64")]
    public bool? IncludeImageBase64 { get; set; } = null;

}
