// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c892c5ad61c5b9376089e0d461b22e97ed9f5766653c5d3c2e5bf8cca5950f37
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// An outbound request was blocked by the active `OutboundPolicy`.
///
/// Returned when `register_custom_provider` is called with a `base_url` that
/// violates the policy (e.g. a private-range IP under `DenyPrivate`), or when
/// the per-connection DNS resolver detects a forbidden address at connect time.
/// </summary>
public class OutboundForbiddenException : LiterLlmErrorException
{
    public OutboundForbiddenException(string message) : base(message) { }

    public OutboundForbiddenException(string message, Exception innerException) : base(message, innerException) { }
}
