// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d954bd0ab4851664242c5d5bf76bcc6f4c84e06fe6cd42e3effba8a0bb5c3dcf
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// The fetched or cached catalog JSON failed to parse.
/// </summary>
public class ParseException : CatalogRefreshErrorException
{
    public ParseException(string message) : base(message) { }

    public ParseException(string message, Exception innerException) : base(message, innerException) { }
}
