// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:550e5ac23767360f2a739e82c438260552fff40447392871d66f6cc04ff70dfd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Breakdown of tokens used in the prompt portion of a request.
///
/// `cached_tokens` is included in `Usage::prompt_tokens` — it is *not* an
/// additional charge on top of the prompt token count. When pricing supports
/// a `cache_read_input_token_cost`, the cached portion is billed at the
/// discounted rate and the remainder at the regular input rate.
/// </summary>
public sealed class PromptTokensDetails
{
    /// <summary>
    /// Cached tokens present in the prompt. Defaults to 0 when absent.
    /// </summary>
    [JsonPropertyName("cached_tokens")]
    public ulong CachedTokens { get; set; } = 0;

    /// <summary>
    /// Audio input tokens present in the prompt. Defaults to 0 when absent.
    /// </summary>
    [JsonPropertyName("audio_tokens")]
    public ulong AudioTokens { get; set; } = 0;

}
