// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8cdd7cabb93c91d13af838cf7a6a1b242341baa6c1a09f1eb18392963289ae45
#nullable enable

using System;

namespace LiterLlm;

public class RateLimitedException : LiterLlmErrorException
{
    public RateLimitedException(string message) : base(message) { }

    public RateLimitedException(string message, Exception innerException) : base(message, innerException) { }
}
