// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b6355085e7b98b10684f1227fa160306752f5716a5fbb991e253cdd8d3551a05
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;
/// <summary>/// Controls how much reasoning effort the model should use./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ReasoningEffort
{
    [JsonPropertyName("low")]
    Low, [JsonPropertyName("medium")]
    Medium, [JsonPropertyName("high")]
    High,
}
