// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f6823f4ec8be5dec6fbcb2874e0191f4b5fc1dd9b048a27a6288e7fc397cd156
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;
/// <summary>
/// Controls how much reasoning effort the model should use.
/// </summary>
[JsonConverter(typeof(ReasoningEffortJsonConverter))]
public enum ReasoningEffort
{
    [JsonPropertyName("low")]
    Low,
    [JsonPropertyName("medium")]
    Medium,
    [JsonPropertyName("high")]
    High,
}


/// <summary>
/// Custom JSON converter for <see cref="ReasoningEffort"/> that respects explicit variant names.
/// </summary>
internal sealed class ReasoningEffortJsonConverter : JsonConverter<ReasoningEffort>
{
    public override ReasoningEffort Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "low" => ReasoningEffort.Low,
            "medium" => ReasoningEffort.Medium,
            "high" => ReasoningEffort.High,
            _ => throw new JsonException($"Unknown ReasoningEffort value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, ReasoningEffort value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            ReasoningEffort.Low => "low",
            ReasoningEffort.Medium => "medium",
            ReasoningEffort.High => "high",
            _ => throw new JsonException($"Unknown ReasoningEffort value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
