// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7218e91889b02bbe9d4a7ab8e74fac54841c898b09ba671a9304b2e1a382bffb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Response from the rerank endpoint.
/// </summary>
public sealed class RerankResponse
{
    [JsonPropertyName("id")]
    public string? Id { get; set; } = null;

    [JsonPropertyName("results")]
    public List<RerankResult> Results { get; set; } = [];

    [JsonPropertyName("meta")]
    public object? Meta { get; set; } = null;


    /// <summary>
    /// Parse a <see cref="RerankResponse"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static RerankResponse FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<RerankResponse>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse RerankResponse from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse RerankResponse from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
