// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:803d2ec0d8e76af6c29582857249ab13803bc8bb5c8248d48fd0c90cb59d3930
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed class ResponseOutputItem
{
    [JsonPropertyName("item_type")]
    public string ItemType { get; set; } = "";

    [JsonPropertyName("content")]
    public object? Content { get; set; } = null;

}
