// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fc743456ebdc7c3fc994dfce751039108a62783bc7d53763375ceddb2453b241
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// A search response.
/// </summary>
public sealed class SearchResponse
{
    /// <summary>
    /// The search results.
    /// </summary>
    [JsonPropertyName("results")]
    public List<SearchResult> Results { get; set; } = [];

    /// <summary>
    /// The model used.
    /// </summary>
    [JsonPropertyName("model")]
    public string Model { get; set; } = "";


    /// <summary>
    /// Parse a <see cref="SearchResponse"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static SearchResponse FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<SearchResponse>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse SearchResponse from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse SearchResponse from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
