// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5ab53abee9ad8a282dfd709d969c3cf38af90f6c41a33626ee0612732e7f3b65
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// `status` preserves the exact HTTP status code received (502, 503, or 504).
/// </summary>
public class ServiceUnavailableException : LiterLlmErrorException
{
    public ServiceUnavailableException(string message) : base(message) { }

    public ServiceUnavailableException(string message, Exception innerException) : base(message, innerException) { }
}
