// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9e1a415a680c008d534bad6aeee812fa0ddca31b26473018627001b4ea928ebc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Name of the specific function to invoke.
/// </summary>
public sealed record SpecificFunction
{
    /// <summary>
    /// Function name.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = "";


    /// <summary>
    /// Parse a <see cref="SpecificFunction"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static SpecificFunction FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<SpecificFunction>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse SpecificFunction from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse SpecificFunction from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
