// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e361a309851a09155e92d972d9657041809f104f46397a75c52bb02df7b7154d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// A streaming choice with incremental delta.
/// </summary>
public sealed record StreamChoice
{
    /// <summary>
    /// Index of this choice in the choices array.
    /// </summary>
    [JsonPropertyName("index")]
    public uint Index { get; init; } = 0;

    /// <summary>
    /// Incremental update to the message (content, tool calls, etc.).
    /// </summary>
    [JsonPropertyName("delta")]
    public StreamDelta Delta { get; init; } = default!;

    /// <summary>
    /// Why the stream ended (present only in final chunk).
    /// </summary>
    [JsonPropertyName("finish_reason")]
    public FinishReason? FinishReason { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="StreamChoice"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static StreamChoice FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<StreamChoice>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse StreamChoice from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse StreamChoice from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
