// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3caa835f45527468672afda0f0854d47d13495e4c2f7e8f452b238fce6248e5e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public sealed record StreamDelta
{
    [JsonPropertyName("role")]
    public string? Role { get; init; } = null;

    [JsonPropertyName("content")]
    public string? Content { get; init; } = null;

    [JsonPropertyName("tool_calls")]
    public List<StreamToolCall>? ToolCalls { get; init; } = null;

    /// <summary>
    /// Deprecated legacy function_call delta; retained for API compatibility.
    /// </summary>
    [JsonPropertyName("function_call")]
    public StreamFunctionCall? FunctionCall { get; init; } = null;

    [JsonPropertyName("refusal")]
    public string? Refusal { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="StreamDelta"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static StreamDelta FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<StreamDelta>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse StreamDelta from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse StreamDelta from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
