// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c870ffb6360fa8ee012dd734a8947259204c782bafd6a10132b91989c036422d
#nullable enable

using System;

namespace LiterLlm;

/// <summary>
/// A catch-all for errors that occur during streaming response processing.
///
/// This variant covers multiple sub-conditions including UTF-8 decoding
/// failures, CRC/checksum mismatches (AWS EventStream), JSON parse errors
/// in individual SSE chunks, and buffer overflow conditions.  The `message`
/// field contains a human-readable description of the specific failure.
/// </summary>
public class StreamingException : LiterLlmErrorException
{
    public StreamingException(string message) : base(message) { }

    public StreamingException(string message, Exception innerException) : base(message, innerException) { }
}
