// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e580eb2555b8284442efbeb0d09f84d9cca556be936a4a3659ea74b5f1840715
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// System message guiding model behavior for the entire conversation.
/// </summary>
public sealed record SystemMessage
{
    /// <summary>
    /// Instructions or context that apply throughout the conversation.
    /// </summary>
    [JsonPropertyName("content")]
    public string Content { get; init; } = "";

    /// <summary>
    /// Optional name for the system message source.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="SystemMessage"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static SystemMessage FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<SystemMessage>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse SystemMessage from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse SystemMessage from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
