// This file is auto-generated by alef. DO NOT EDIT.
<<<<<<< Updated upstream
// alef:hash:fe64a8a06beeb01b5344005fa07dcdfdf3e244d772ace0f89dbba84b0541ca2d
=======
// alef:hash:ff0e10ad47404c645f09678fc9db55fb107af1c70816902b56b45b49d59c3b3b
>>>>>>> Stashed changes
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;
/// <summary>
/// Tool choice mode.
/// </summary>
[JsonConverter(typeof(ToolChoiceModeJsonConverter))]
public enum ToolChoiceMode
{
    /// <summary>
    /// Model may or may not call tools; default behavior.
    /// </summary>
    [JsonPropertyName("auto")]
    Auto,
    /// <summary>
    /// Model must call at least one tool.
    /// </summary>
    [JsonPropertyName("required")]
    Required,
    /// <summary>
    /// Model must not call any tools.
    /// </summary>
    [JsonPropertyName("none")]
    None,
}


/// <summary>
/// Custom JSON converter for <see cref="ToolChoiceMode"/> that respects explicit variant names.
/// </summary>
internal sealed class ToolChoiceModeJsonConverter : JsonConverter<ToolChoiceMode>
{
    public override ToolChoiceMode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "auto" => ToolChoiceMode.Auto,
            "required" => ToolChoiceMode.Required,
            "none" => ToolChoiceMode.None,
            _ => throw new JsonException($"Unknown ToolChoiceMode value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, ToolChoiceMode value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            ToolChoiceMode.Auto => "auto",
            ToolChoiceMode.Required => "required",
            ToolChoiceMode.None => "none",
            _ => throw new JsonException($"Unknown ToolChoiceMode value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
