// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f6823f4ec8be5dec6fbcb2874e0191f4b5fc1dd9b048a27a6288e7fc397cd156
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

/// <summary>
/// Response from a transcription request.
/// </summary>
public sealed record TranscriptionResponse
{
    /// <summary>
    /// The transcribed text.
    /// </summary>
    [JsonPropertyName("text")]
    public string Text { get; init; } = "";

    /// <summary>
    /// Detected language (ISO-639-1 code).
    /// </summary>
    [JsonPropertyName("language")]
    public string? Language { get; init; } = null;

    /// <summary>
    /// Total audio duration in seconds.
    /// </summary>
    [JsonPropertyName("duration")]
    public double? Duration { get; init; } = null;

    /// <summary>
    /// Detailed segment-level transcription (if response_format is "verbose_json").
    /// </summary>
    [JsonPropertyName("segments")]
    public List<TranscriptionSegment>? Segments { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="TranscriptionResponse"/> from a JSON string.
    /// </summary>
    /// <exception cref="LiterLlmException">When the JSON cannot be deserialised.</exception>
    public static TranscriptionResponse FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<TranscriptionResponse>(json, JsonOptions)
                ?? throw new LiterLlmException($"Failed to parse TranscriptionResponse from JSON: deserializer returned null");
        }
        catch (LiterLlmException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new LiterLlmException($"Failed to parse TranscriptionResponse from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
