// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7125a4bf510ce723844118b99ea2479df5d26809e1a72cd159946da51a331939
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace LiterLlm;

public enum UserContent
{[JsonPropertyName("text")]
    Text,[JsonPropertyName("parts")]
    Parts,}
