version: "3"

vars:
  BUILD_PROFILE: '{{.BUILD_PROFILE | default "release"}}'
  VERSION:
    sh: python3 -c "import tomllib; print(tomllib.load(open('Cargo.toml','rb'))['workspace']['package']['version'])"
  PROJECT_ROOT:
    sh: pwd
