# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:415b69af574cb5e57be1161c3cbdd5737db605fb1c1686db693e01f35a41a6fb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

"""E2e tests for category: ocr."""

import os
import pytest  # noqa: F401
from liter_llm import create_client
from liter_llm._internal_bindings import OcrRequest


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = (
        " ".join(str(value) for value in raw_items)
        if isinstance(raw_items, list)
        else ""
    )
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


@pytest.mark.asyncio
async def test_ocr_error_400() -> None:
    """400 Bad Request error when OCR input has an invalid image format."""
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/ocr_error_400",
    )
    request = OcrRequest.from_json(
        '{"document":{"type":"document_url","url":"invalid://url"},"model":"mistral/mistral-ocr-latest"}'
    )

    with pytest.raises(Exception) as exc_info:  # noqa: B017
        await client.ocr(request)
    assert "BadRequest" in type(exc_info.value).__name__  # noqa: S101


@pytest.mark.asyncio
async def test_ocr_error_401() -> None:
    """401 Unauthorized error on OCR request due to invalid API credentials."""
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/ocr_error_401",
    )
    request = OcrRequest.from_json(
        '{"document":{"type":"document_url","url":"https://example.com/doc.pdf"},"model":"mistral/mistral-ocr-latest"}'
    )

    with pytest.raises(Exception) as exc_info:  # noqa: B017
        await client.ocr(request)
    assert "Authentication" in type(exc_info.value).__name__  # noqa: S101


@pytest.mark.asyncio
async def test_ocr_multi_page() -> None:
    """OCR request returning multiple pages of document content."""
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/ocr_multi_page",
    )
    request = OcrRequest.from_json(
        '{"document":{"type":"document_url","url":"https://example.com/multipage.pdf"},"model":"mistral/mistral-ocr-latest"}'
    )

    result = await client.ocr(request)
    assert len(result.pages) == 2  # noqa: S101
    assert result.pages[0].index == 0  # noqa: S101
    assert result.pages[1].index == 1  # noqa: S101


@pytest.mark.asyncio
async def test_ocr_url_document() -> None:
    """OCR request with a document URL input."""
    client = create_client(
        api_key="test-key",
        base_url=os.environ["MOCK_SERVER_URL"] + "/fixtures/ocr_url_document",
    )
    request = OcrRequest.from_json(
        '{"document":{"type":"document_url","url":"https://example.com/doc.pdf"},"model":"mistral/mistral-ocr-latest"}'
    )

    _ = await client.ocr(request)
