// Generated by alef. Do not edit by hand.

const std = @import("std");
pub const c = @cImport(@cInclude("liter_llm.h"));

/// Free a string allocated by the FFI layer.
/// Free a string allocated by the FFI layer.
/// The pointer must have been returned by a `literllm_*` C function.
/// Do NOT call this twice on the same pointer.
pub fn _free_string(ptr: [*c]u8) void {
    c.literllm_free_string(ptr);
}

/// Retrieve the last error set by the FFI layer, if any.
/// Returns a slice into thread-local storage valid until the next FFI call.
pub fn _last_error() ?[]const u8 {
    const _code = c.literllm_last_error_code();
    if (_code == 0) return null;
    const _ctx = c.literllm_last_error_context();
    if (_ctx == null) return null;
    return std.mem.sliceTo(_ctx, 0);
}

/// Map the last FFI error to a typed error from the given error set.
/// Coarse fallback: returns the first declared variant. Per-code dispatch
/// will replace this once the IR exposes per-variant numeric codes.
inline fn _first_error(comptime E: type) E {
    const fields = @typeInfo(E).error_set orelse return @as(E, error.Unknown);
    if (fields.len == 0) unreachable;
    return @field(E, fields[0].name);
}

/// All errors that can occur when using `liter-llm`.
pub const LiterLlmError = error{
    Authentication,
    RateLimited,
    BadRequest,
    ContextWindowExceeded,
    ContentPolicy,
    NotFound,
    ServerError,
    ServiceUnavailable,
    Timeout,
    Streaming,
    EndpointNotSupported,
    InvalidHeader,
    Serialization,
    BudgetExceeded,
    HookRejected,
    InternalError,
    OutOfMemory,
};

pub const SystemMessage = struct {
    content: []const u8,
    name: ?[]const u8,
};

pub const UserMessage = struct {
    content: UserContent,
    name: ?[]const u8,
};

pub const ImageUrl = struct {
    url: []const u8,
    detail: ?ImageDetail,
};

pub const DocumentContent = struct {
    /// Base64-encoded document data or URL.
    data: []const u8,
    /// MIME type (e.g., "application/pdf", "text/csv").
    media_type: []const u8,
};

pub const AudioContent = struct {
    /// Base64-encoded audio data.
    data: []const u8,
    /// Audio format (e.g., "wav", "mp3", "ogg").
    format: []const u8,
};

pub const AssistantMessage = struct {
    content: ?[]const u8,
    name: ?[]const u8,
    tool_calls: ?[]const ToolCall,
    refusal: ?[]const u8,
    /// Deprecated legacy function_call field; retained for API compatibility.
    function_call: ?FunctionCall,
};

pub const ToolMessage = struct {
    content: []const u8,
    tool_call_id: []const u8,
    name: ?[]const u8,
};

pub const DeveloperMessage = struct {
    content: []const u8,
    name: ?[]const u8,
};

/// Deprecated legacy function-role message body.
pub const FunctionMessage = struct {
    content: []const u8,
    name: []const u8,
};

pub const ChatCompletionTool = struct {
    tool_type: ToolType,
    function: FunctionDefinition,
};

pub const FunctionDefinition = struct {
    name: []const u8,
    description: ?[]const u8,
    parameters: ?[]const u8,
    strict: ?bool,
};

pub const ToolCall = struct {
    id: []const u8,
    call_type: ToolType,
    function: FunctionCall,
};

pub const FunctionCall = struct {
    name: []const u8,
    arguments: []const u8,
};

pub const SpecificToolChoice = struct {
    choice_type: ToolType,
    function: SpecificFunction,
};

pub const SpecificFunction = struct {
    name: []const u8,
};

pub const JsonSchemaFormat = struct {
    name: []const u8,
    description: ?[]const u8,
    schema: []const u8,
    strict: ?bool,
};

pub const Usage = struct {
    /// Prompt tokens used. Defaults to 0 when absent (some providers omit this).
    prompt_tokens: u64,
    /// Completion tokens used. Defaults to 0 when absent (e.g. embedding responses).
    completion_tokens: u64,
    /// Total tokens used. Defaults to 0 when absent (some providers omit this).
    total_tokens: u64,
    /// Breakdown of tokens used in the prompt, including cached tokens served
    /// at the provider's discounted cache-read rate. Absent when the provider
    /// does not return prompt-token details.
    prompt_tokens_details: ?PromptTokensDetails,
};

/// Breakdown of tokens used in the prompt portion of a request.
///
/// `cached_tokens` is included in `Usage.prompt_tokens` — it is *not* an
/// additional charge on top of the prompt token count. When pricing supports
/// a `cache_read_input_token_cost`, the cached portion is billed at the
/// discounted rate and the remainder at the regular input rate.
pub const PromptTokensDetails = struct {
    /// Cached tokens present in the prompt. Defaults to 0 when absent.
    cached_tokens: u64,
    /// Audio input tokens present in the prompt. Defaults to 0 when absent.
    audio_tokens: u64,
};

pub const ChatCompletionRequest = struct {
    model: []const u8,
    messages: []const Message,
    temperature: ?f64,
    top_p: ?f64,
    n: ?u32,
    /// Whether to stream the response.
    ///
    /// Managed by the client layer — do not set directly.
    stream: ?bool,
    stop: ?StopSequence,
    max_tokens: ?u64,
    presence_penalty: ?f64,
    frequency_penalty: ?f64,
    /// Token bias map.  Uses `BTreeMap` (sorted keys) for deterministic
    /// serialization order — important when hashing or signing requests.
    logit_bias: ?std.StringHashMap(f64),
    user: ?[]const u8,
    tools: ?[]const ChatCompletionTool,
    tool_choice: ?ToolChoice,
    parallel_tool_calls: ?bool,
    response_format: ?ResponseFormat,
    stream_options: ?StreamOptions,
    seed: ?i64,
    reasoning_effort: ?ReasoningEffort,
    /// Provider-specific extra parameters merged into the request body.
    /// Use for guardrails, safety settings, grounding config, etc.
    extra_body: ?[]const u8,
};

pub const StreamOptions = struct {
    include_usage: ?bool,
};

pub const ChatCompletionResponse = struct {
    id: []const u8,
    /// Always `"chat.completion"` from OpenAI-compatible APIs.  Stored as a
    /// plain `String` so non-standard provider values do not break deserialization.
    object: []const u8,
    created: u64,
    model: []const u8,
    choices: []const Choice,
    usage: ?Usage,
    system_fingerprint: ?[]const u8,
    service_tier: ?[]const u8,
};

pub const Choice = struct {
    index: u32,
    message: AssistantMessage,
    finish_reason: ?FinishReason,
};

pub const ChatCompletionChunk = struct {
    id: []const u8,
    /// Always `"chat.completion.chunk"` from OpenAI-compatible APIs.  Stored
    /// as a plain `String` so non-standard provider values do not fail parsing.
    object: []const u8,
    created: u64,
    model: []const u8,
    choices: []const StreamChoice,
    usage: ?Usage,
    system_fingerprint: ?[]const u8,
    service_tier: ?[]const u8,
};

pub const StreamChoice = struct {
    index: u32,
    delta: StreamDelta,
    finish_reason: ?FinishReason,
};

pub const StreamDelta = struct {
    role: ?[]const u8,
    content: ?[]const u8,
    tool_calls: ?[]const StreamToolCall,
    /// Deprecated legacy function_call delta; retained for API compatibility.
    function_call: ?StreamFunctionCall,
    refusal: ?[]const u8,
};

pub const StreamToolCall = struct {
    index: u32,
    id: ?[]const u8,
    call_type: ?ToolType,
    function: ?StreamFunctionCall,
};

pub const StreamFunctionCall = struct {
    name: ?[]const u8,
    arguments: ?[]const u8,
};

pub const EmbeddingRequest = struct {
    model: []const u8,
    input: EmbeddingInput,
    encoding_format: ?EmbeddingFormat,
    dimensions: ?u32,
    user: ?[]const u8,
};

pub const EmbeddingResponse = struct {
    /// Always `"list"` from OpenAI-compatible APIs.  Stored as a plain
    /// `String` so non-standard provider values do not break deserialization.
    object: []const u8,
    data: []const EmbeddingObject,
    model: []const u8,
    usage: ?Usage,
};

pub const EmbeddingObject = struct {
    /// Always `"embedding"` from OpenAI-compatible APIs.  Stored as a plain
    /// `String` so non-standard provider values do not break deserialization.
    object: []const u8,
    embedding: []const f64,
    index: u32,
};

/// Request to create images from a text prompt.
pub const CreateImageRequest = struct {
    prompt: []const u8,
    model: ?[]const u8,
    n: ?u32,
    size: ?[]const u8,
    quality: ?[]const u8,
    style: ?[]const u8,
    response_format: ?[]const u8,
    user: ?[]const u8,
};

/// Response containing generated images.
pub const ImagesResponse = struct {
    created: u64,
    data: []const Image,
};

/// A single generated image, returned as either a URL or base64 data.
pub const Image = struct {
    url: ?[]const u8,
    b64_json: ?[]const u8,
    revised_prompt: ?[]const u8,
};

/// Request to generate speech audio from text.
pub const CreateSpeechRequest = struct {
    model: []const u8,
    input: []const u8,
    voice: []const u8,
    response_format: ?[]const u8,
    speed: ?f64,
};

/// Request to transcribe audio into text.
pub const CreateTranscriptionRequest = struct {
    model: []const u8,
    /// Base64-encoded audio file data.
    file: []const u8,
    language: ?[]const u8,
    prompt: ?[]const u8,
    response_format: ?[]const u8,
    temperature: ?f64,
};

/// Response from a transcription request.
pub const TranscriptionResponse = struct {
    text: []const u8,
    language: ?[]const u8,
    duration: ?f64,
    segments: ?[]const TranscriptionSegment,
};

/// A segment of transcribed audio with timing information.
pub const TranscriptionSegment = struct {
    id: u32,
    start: f64,
    end: f64,
    text: []const u8,
};

/// Request to classify content for policy violations.
pub const ModerationRequest = struct {
    input: ModerationInput,
    model: ?[]const u8,
};

/// Response from the moderation endpoint.
pub const ModerationResponse = struct {
    id: []const u8,
    model: []const u8,
    results: []const ModerationResult,
};

/// A single moderation classification result.
pub const ModerationResult = struct {
    flagged: bool,
    categories: ModerationCategories,
    category_scores: ModerationCategoryScores,
};

/// Boolean flags for each moderation category.
pub const ModerationCategories = struct {
    sexual: bool,
    hate: bool,
    harassment: bool,
    self_harm: bool,
    sexual_minors: bool,
    hate_threatening: bool,
    violence_graphic: bool,
    self_harm_intent: bool,
    self_harm_instructions: bool,
    harassment_threatening: bool,
    violence: bool,
};

/// Confidence scores for each moderation category.
pub const ModerationCategoryScores = struct {
    sexual: f64,
    hate: f64,
    harassment: f64,
    self_harm: f64,
    sexual_minors: f64,
    hate_threatening: f64,
    violence_graphic: f64,
    self_harm_intent: f64,
    self_harm_instructions: f64,
    harassment_threatening: f64,
    violence: f64,
};

/// Request to rerank documents by relevance to a query.
pub const RerankRequest = struct {
    model: []const u8,
    query: []const u8,
    documents: []const RerankDocument,
    top_n: ?u32,
    return_documents: ?bool,
};

/// Response from the rerank endpoint.
pub const RerankResponse = struct {
    id: ?[]const u8,
    results: []const RerankResult,
    meta: ?[]const u8,
};

/// A single reranked document with its relevance score.
pub const RerankResult = struct {
    index: u32,
    relevance_score: f64,
    document: ?RerankResultDocument,
};

/// The text content of a reranked document, returned when `return_documents` is true.
pub const RerankResultDocument = struct {
    text: []const u8,
};

/// A search request.
pub const SearchRequest = struct {
    /// The model/provider to use (e.g. `"brave/web-search"`, `"tavily/search"`).
    model: []const u8,
    /// The search query.
    query: []const u8,
    /// Maximum number of results to return.
    max_results: ?u32,
    /// Domain filter — restrict results to specific domains.
    search_domain_filter: ?[]const []const u8,
    /// Country code for localized results (ISO 3166-1 alpha-2).
    country: ?[]const u8,
};

/// A search response.
pub const SearchResponse = struct {
    /// The search results.
    results: []const SearchResult,
    /// The model used.
    model: []const u8,
};

/// An individual search result.
pub const SearchResult = struct {
    /// Title of the result.
    title: []const u8,
    /// URL of the result.
    url: []const u8,
    /// Text snippet / excerpt.
    snippet: []const u8,
    /// Publication or last-updated date, if available.
    date: ?[]const u8,
};

/// An OCR request.
pub const OcrRequest = struct {
    /// The model/provider to use (e.g. `"mistral/mistral-ocr-latest"`).
    model: []const u8,
    /// The document to process.
    document: OcrDocument,
    /// Specific pages to process (1-indexed). `null` means all pages.
    pages: ?[]const u32,
    /// Whether to include base64-encoded images of each page.
    include_image_base64: ?bool,
};

/// An OCR response.
pub const OcrResponse = struct {
    /// Extracted pages.
    pages: []const OcrPage,
    /// The model used.
    model: []const u8,
    /// Token usage, if reported by the provider.
    usage: ?Usage,
};

/// A single page of OCR output.
pub const OcrPage = struct {
    /// Page index (0-based).
    index: u32,
    /// Extracted content as Markdown.
    markdown: []const u8,
    /// Extracted images, if `include_image_base64` was set.
    images: ?[]const OcrImage,
    /// Page dimensions in pixels, if available.
    dimensions: ?PageDimensions,
};

/// An image extracted from an OCR page.
pub const OcrImage = struct {
    /// Unique image identifier.
    id: []const u8,
    /// Base64-encoded image data.
    image_base64: ?[]const u8,
};

/// Page dimensions in pixels.
pub const PageDimensions = struct {
    /// Width in pixels.
    width: u32,
    /// Height in pixels.
    height: u32,
};

pub const ModelsListResponse = struct {
    /// Always `"list"` from OpenAI-compatible APIs.  Stored as a plain
    /// `String` so non-standard provider values do not break deserialization.
    object: []const u8,
    data: []const ModelObject,
};

pub const ModelObject = struct {
    id: []const u8,
    /// Always `"model"` from OpenAI-compatible APIs.  Stored as a plain
    /// `String` so non-standard provider values do not break deserialization.
    object: []const u8,
    created: u64,
    owned_by: []const u8,
};

pub const CreateFileRequest = struct {
    /// Base64-encoded file data.
    file: []const u8,
    purpose: FilePurpose,
    filename: ?[]const u8,
};

pub const FileObject = struct {
    id: []const u8,
    object: []const u8,
    bytes: u64,
    created_at: u64,
    filename: []const u8,
    purpose: []const u8,
    status: ?[]const u8,
};

pub const FileListResponse = struct {
    object: []const u8,
    data: []const FileObject,
    has_more: ?bool,
};

pub const FileListQuery = struct {
    purpose: ?[]const u8,
    limit: ?u32,
    after: ?[]const u8,
};

pub const DeleteResponse = struct {
    id: []const u8,
    object: []const u8,
    deleted: bool,
};

pub const CreateBatchRequest = struct {
    input_file_id: []const u8,
    endpoint: []const u8,
    completion_window: []const u8,
    metadata: ?[]const u8,
};

pub const BatchObject = struct {
    id: []const u8,
    object: []const u8,
    endpoint: []const u8,
    input_file_id: []const u8,
    completion_window: []const u8,
    status: BatchStatus,
    output_file_id: ?[]const u8,
    error_file_id: ?[]const u8,
    created_at: u64,
    completed_at: ?u64,
    failed_at: ?u64,
    expired_at: ?u64,
    request_counts: ?BatchRequestCounts,
    metadata: ?[]const u8,
};

pub const BatchRequestCounts = struct {
    total: u64,
    completed: u64,
    failed: u64,
};

pub const BatchListResponse = struct {
    object: []const u8,
    data: []const BatchObject,
    has_more: ?bool,
    first_id: ?[]const u8,
    last_id: ?[]const u8,
};

pub const BatchListQuery = struct {
    limit: ?u32,
    after: ?[]const u8,
};

pub const CreateResponseRequest = struct {
    model: []const u8,
    input: []const u8,
    instructions: ?[]const u8,
    tools: ?[]const ResponseTool,
    temperature: ?f64,
    max_output_tokens: ?u64,
    metadata: ?[]const u8,
};

pub const ResponseTool = struct {
    tool_type: []const u8,
    config: []const u8,
};

pub const ResponseObject = struct {
    id: []const u8,
    object: []const u8,
    created_at: u64,
    model: []const u8,
    status: []const u8,
    output: []const ResponseOutputItem,
    usage: ?ResponseUsage,
    error_: ?[]const u8,
};

pub const ResponseOutputItem = struct {
    item_type: []const u8,
    content: []const u8,
};

pub const ResponseUsage = struct {
    input_tokens: u64,
    output_tokens: u64,
    total_tokens: u64,
};

/// Configuration for registering a custom LLM provider at runtime.
pub const CustomProviderConfig = struct {
    /// Unique name for this provider (e.g., "my-provider").
    name: []const u8,
    /// Base URL for the provider's API (e.g., "https://api.my-provider.com/v1").
    base_url: []const u8,
    /// Authentication header format.
    auth_header: AuthHeaderFormat,
    /// Model name prefixes that route to this provider (e.g., ["my-"]).
    model_prefixes: []const []const u8,
};

/// A chat message in a conversation.
pub const Message = union(enum) {
    system: SystemMessage,
    user: UserMessage,
    assistant: AssistantMessage,
    tool: ToolMessage,
    developer: DeveloperMessage,
    /// Deprecated legacy function-role message; retained for API compatibility.
    function: FunctionMessage,
};

pub const UserContent = union(enum) {
    text: []const u8,
    parts: []const ContentPart,
};

pub const ContentPart = union(enum) {
    text: []const u8,
    image_url: ImageUrl,
    document: DocumentContent,
    input_audio: AudioContent,
};

pub const ImageDetail = enum {
    low,
    high,
    auto,
};

/// The type discriminator for tool/tool-call objects.
///
/// Per the OpenAI spec this is always `"function"`. Using an enum enforces
/// that constraint at the type level and rejects any other value on
/// deserialization.
pub const ToolType = enum {
    function,
};

pub const ToolChoice = union(enum) {
    mode: ToolChoiceMode,
    specific: SpecificToolChoice,
};

pub const ToolChoiceMode = enum {
    auto,
    required,
    none,
};

pub const ResponseFormat = union(enum) {
    text: void,
    json_object: void,
    json_schema: JsonSchemaFormat,
};

pub const StopSequence = union(enum) {
    single: []const u8,
    multiple: []const []const u8,
};

/// Why a choice stopped generating tokens.
pub const FinishReason = enum {
    stop,
    length,
    tool_calls,
    content_filter,
    /// Deprecated legacy finish reason; retained for API compatibility.
    function_call,
    /// Catch-all for unknown finish reasons returned by non-OpenAI providers.
    ///
    /// Note: this intentionally does **not** carry the original string (e.g.
    /// `Other(String)`).  Using `#[serde(other)]` requires a unit variant, and
    /// switching to `#[serde(untagged)]` would change deserialization semantics
    /// for all variants.  The original value can be recovered by inspecting the
    /// raw JSON if needed.
    other,
};

/// Controls how much reasoning effort the model should use.
pub const ReasoningEffort = enum {
    low,
    medium,
    high,
};

/// The format in which the embedding vectors are returned.
pub const EmbeddingFormat = enum {
    /// 32-bit floating-point numbers (default).
    float,
    /// Base64-encoded string representation of the floats.
    base64,
};

pub const EmbeddingInput = union(enum) {
    single: []const u8,
    multiple: []const []const u8,
};

/// Input to the moderation endpoint — a single string or multiple strings.
pub const ModerationInput = union(enum) {
    single: []const u8,
    multiple: []const []const u8,
};

/// A document to be reranked — either a plain string or an object with a text field.
pub const RerankDocument = union(enum) {
    text: []const u8,
    object: []const u8,
};

/// Document input for OCR — either a URL or inline base64 data.
pub const OcrDocument = union(enum) {
    /// A publicly accessible document URL.
    document_url: []const u8,
    /// Inline base64-encoded document data.
    base64: struct {
        data: []const u8,
        media_type: []const u8,
    },
};

pub const FilePurpose = enum {
    assistants,
    batch,
    fine_tune,
    vision,
};

pub const BatchStatus = enum {
    validating,
    failed,
    in_progress,
    finalizing,
    completed,
    expired,
    cancelling,
    cancelled,
};

/// How the API key is sent in the HTTP request.
pub const AuthHeaderFormat = union(enum) {
    /// Bearer token: `Authorization: Bearer <key>`
    bearer: void,
    /// Custom header: e.g., `X-Api-Key: <key>`
    api_key: []const u8,
    /// No authentication required.
    none: void,
};

/// Create a new LLM client with simple scalar configuration.
///
/// This is the primary binding entry-point. All parameters except `api_key`
/// are optional — omitting them uses the same defaults as
/// `ClientConfigBuilder`.
///
/// **Errors:**
///
/// Returns `LiterLlmError` if the underlying HTTP client cannot be
/// constructed, or if the resolved provider configuration is invalid.
pub fn create_client(api_key: []const u8, base_url: ?[]const u8, timeout_secs: ?u64, max_retries: ?u32, model_hint: ?[]const u8) LiterLlmError!DefaultClient {
    const api_key_z = try std.fmt.allocPrintSentinel(std.heap.c_allocator, "{s}", .{api_key}, 0);
    defer std.heap.c_allocator.free(api_key_z);
    const base_url_z: ?[:0]u8 = if (base_url) |v| try std.fmt.allocPrintSentinel(std.heap.c_allocator, "{s}", .{v}, 0) else null;
    defer if (base_url_z) |z| std.heap.c_allocator.free(z);
    const model_hint_z: ?[:0]u8 = if (model_hint) |v| try std.fmt.allocPrintSentinel(std.heap.c_allocator, "{s}", .{v}, 0) else null;
    defer if (model_hint_z) |z| std.heap.c_allocator.free(z);
    const _result = c.literllm_create_client(api_key_z, if (base_url_z) |z| z.ptr else null, if (timeout_secs) |v| v else std.math.maxInt(u64), if (max_retries) |v| v else std.math.maxInt(u32), if (model_hint_z) |z| z.ptr else null);
    if (c.literllm_last_error_code() != 0) {
        return _first_error(LiterLlmError);
    }
    return DefaultClient{ ._handle = _result.? };
}

/// Create a new LLM client from a JSON string.
///
/// The JSON object accepts the same fields as `liter-llm.toml` (snake_case).
///
/// **Errors:**
///
/// Returns `LiterLlmError.BadRequest` if `json` is not valid JSON or
/// contains unknown fields.
pub fn create_client_from_json(json: []const u8) LiterLlmError!DefaultClient {
    const json_z = try std.fmt.allocPrintSentinel(std.heap.c_allocator, "{s}", .{json}, 0);
    defer std.heap.c_allocator.free(json_z);
    const _result = c.literllm_create_client_from_json(json_z);
    if (c.literllm_last_error_code() != 0) {
        return _first_error(LiterLlmError);
    }
    return DefaultClient{ ._handle = _result.? };
}

/// Default client implementation backed by `reqwest`.
///
/// Sends requests to 140+ LLM providers with automatic provider detection
/// and per-request routing. The provider is resolved at construction time
/// from `model_hint` (or defaults to OpenAI), but individual requests can
/// override the provider via model name prefix (e.g. `"anthropic/claude-3-5-sonnet"`
/// routes to Anthropic regardless of construction-time setting).
///
/// When the model prefix does not match any known provider, the construction-time
/// provider is used as the fallback. This enables seamless migration between
/// providers by changing only the model name.
///
/// The provider is stored behind an `Arc` so it can be shared cheaply into
/// async closures and streaming tasks. Pre-computed auth headers and extra
/// headers are cached at construction to avoid redundant encoding on every request.
pub const DefaultClient = struct {
    _handle: *anyopaque,

    pub fn chat(self: *DefaultClient, req: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const req_z = try std.heap.c_allocator.dupeZ(u8, req);
        defer std.heap.c_allocator.free(req_z);
        const req_handle = c.literllm_chat_completion_request_from_json(req_z.ptr);
        const _result = c.literllm_default_client_chat(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), req_handle);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        c.literllm_chat_completion_request_free(req_handle);
        return blk: {
            const _json_ptr = c.literllm_chat_completion_response_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_chat_completion_response_free(_result);
            break :blk owned;
        };
    }

    pub fn chat_stream(self: *DefaultClient, req: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const req_z = try std.heap.c_allocator.dupeZ(u8, req);
        const req_handle = c.literllm_chat_completion_request_from_json(req_z.ptr);
        std.heap.c_allocator.free(req_z);
        if (req_handle == null) {
            return _first_error(LiterLlmError);
        }
        defer c.literllm_chat_completion_request_free(req_handle);
        const _stream_handle = c.literllm_default_client_chat_stream_start(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), req_handle);
        if (_stream_handle == null) {
            return _first_error(LiterLlmError);
        }
        defer c.literllm_default_client_chat_stream_free(_stream_handle);
        var _last_json: ?[]u8 = null;
        while (true) {
            const _chunk = c.literllm_default_client_chat_stream_next(_stream_handle);
            if (_chunk == null) break;
            if (_last_json) |j| std.heap.c_allocator.free(j);
            const _chunk_json_ptr = c.literllm_chat_completion_chunk_to_json(_chunk);
            c.literllm_chat_completion_chunk_free(_chunk);
            if (_chunk_json_ptr == null) continue;
            const _chunk_slice = std.mem.span(_chunk_json_ptr);
            _last_json = try std.heap.c_allocator.dupe(u8, _chunk_slice);
            c.literllm_free_string(_chunk_json_ptr);
        }
        return _last_json orelse try std.heap.c_allocator.dupe(u8, "{}");
    }

    pub fn embed(self: *DefaultClient, req: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const req_z = try std.heap.c_allocator.dupeZ(u8, req);
        defer std.heap.c_allocator.free(req_z);
        const req_handle = c.literllm_embedding_request_from_json(req_z.ptr);
        const _result = c.literllm_default_client_embed(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), req_handle);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        c.literllm_embedding_request_free(req_handle);
        return blk: {
            const _json_ptr = c.literllm_embedding_response_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_embedding_response_free(_result);
            break :blk owned;
        };
    }

    pub fn list_models(self: *DefaultClient) (LiterLlmError || error{OutOfMemory})![]u8 {
        const _result = c.literllm_default_client_list_models(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)));
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        return blk: {
            const _json_ptr = c.literllm_models_list_response_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_models_list_response_free(_result);
            break :blk owned;
        };
    }

    pub fn image_generate(self: *DefaultClient, req: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const req_z = try std.heap.c_allocator.dupeZ(u8, req);
        defer std.heap.c_allocator.free(req_z);
        const req_handle = c.literllm_create_image_request_from_json(req_z.ptr);
        const _result = c.literllm_default_client_image_generate(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), req_handle);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        c.literllm_create_image_request_free(req_handle);
        return blk: {
            const _json_ptr = c.literllm_images_response_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_images_response_free(_result);
            break :blk owned;
        };
    }

    pub fn speech(self: *DefaultClient, req: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const req_z = try std.heap.c_allocator.dupeZ(u8, req);
        defer std.heap.c_allocator.free(req_z);
        const req_handle = c.literllm_create_speech_request_from_json(req_z.ptr);
        var _out_ptr: [*c]u8 = undefined;
        var _out_len: usize = 0;
        var _out_cap: usize = 0;
        _ = c.literllm_default_client_speech(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), req_handle, &_out_ptr, &_out_len, &_out_cap);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        c.literllm_create_speech_request_free(req_handle);
        const _owned = try std.heap.c_allocator.dupe(u8, _out_ptr[0.._out_len]);
        c.literllm_free_bytes(_out_ptr, _out_len, _out_cap);
        return _owned;
    }

    pub fn transcribe(self: *DefaultClient, req: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const req_z = try std.heap.c_allocator.dupeZ(u8, req);
        defer std.heap.c_allocator.free(req_z);
        const req_handle = c.literllm_create_transcription_request_from_json(req_z.ptr);
        const _result = c.literllm_default_client_transcribe(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), req_handle);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        c.literllm_create_transcription_request_free(req_handle);
        return blk: {
            const _json_ptr = c.literllm_transcription_response_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_transcription_response_free(_result);
            break :blk owned;
        };
    }

    pub fn moderate(self: *DefaultClient, req: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const req_z = try std.heap.c_allocator.dupeZ(u8, req);
        defer std.heap.c_allocator.free(req_z);
        const req_handle = c.literllm_moderation_request_from_json(req_z.ptr);
        const _result = c.literllm_default_client_moderate(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), req_handle);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        c.literllm_moderation_request_free(req_handle);
        return blk: {
            const _json_ptr = c.literllm_moderation_response_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_moderation_response_free(_result);
            break :blk owned;
        };
    }

    pub fn rerank(self: *DefaultClient, req: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const req_z = try std.heap.c_allocator.dupeZ(u8, req);
        defer std.heap.c_allocator.free(req_z);
        const req_handle = c.literllm_rerank_request_from_json(req_z.ptr);
        const _result = c.literllm_default_client_rerank(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), req_handle);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        c.literllm_rerank_request_free(req_handle);
        return blk: {
            const _json_ptr = c.literllm_rerank_response_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_rerank_response_free(_result);
            break :blk owned;
        };
    }

    pub fn search(self: *DefaultClient, req: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const req_z = try std.heap.c_allocator.dupeZ(u8, req);
        defer std.heap.c_allocator.free(req_z);
        const req_handle = c.literllm_search_request_from_json(req_z.ptr);
        const _result = c.literllm_default_client_search(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), req_handle);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        c.literllm_search_request_free(req_handle);
        return blk: {
            const _json_ptr = c.literllm_search_response_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_search_response_free(_result);
            break :blk owned;
        };
    }

    pub fn ocr(self: *DefaultClient, req: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const req_z = try std.heap.c_allocator.dupeZ(u8, req);
        defer std.heap.c_allocator.free(req_z);
        const req_handle = c.literllm_ocr_request_from_json(req_z.ptr);
        const _result = c.literllm_default_client_ocr(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), req_handle);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        c.literllm_ocr_request_free(req_handle);
        return blk: {
            const _json_ptr = c.literllm_ocr_response_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_ocr_response_free(_result);
            break :blk owned;
        };
    }

    pub fn create_file(self: *DefaultClient, req: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const req_z = try std.heap.c_allocator.dupeZ(u8, req);
        defer std.heap.c_allocator.free(req_z);
        const req_handle = c.literllm_create_file_request_from_json(req_z.ptr);
        const _result = c.literllm_default_client_create_file(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), req_handle);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        c.literllm_create_file_request_free(req_handle);
        return blk: {
            const _json_ptr = c.literllm_file_object_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_file_object_free(_result);
            break :blk owned;
        };
    }

    pub fn retrieve_file(self: *DefaultClient, file_id: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const file_id_z = try std.heap.c_allocator.dupeZ(u8, file_id);
        defer std.heap.c_allocator.free(file_id_z);
        const _result = c.literllm_default_client_retrieve_file(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), file_id_z);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        return blk: {
            const _json_ptr = c.literllm_file_object_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_file_object_free(_result);
            break :blk owned;
        };
    }

    pub fn delete_file(self: *DefaultClient, file_id: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const file_id_z = try std.heap.c_allocator.dupeZ(u8, file_id);
        defer std.heap.c_allocator.free(file_id_z);
        const _result = c.literllm_default_client_delete_file(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), file_id_z);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        return blk: {
            const _json_ptr = c.literllm_delete_response_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_delete_response_free(_result);
            break :blk owned;
        };
    }

    pub fn list_files(self: *DefaultClient, query: ?[]const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const query_z: ?[:0]u8 = if (query) |v| try std.heap.c_allocator.dupeZ(u8, v) else null;
        defer if (query_z) |z| std.heap.c_allocator.free(z);
        const query_handle = if (query_z) |z| c.literllm_file_list_query_from_json(z.ptr) else null;
        const _result = c.literllm_default_client_list_files(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), query_handle);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        if (query_handle != null) c.literllm_file_list_query_free(query_handle);
        return blk: {
            const _json_ptr = c.literllm_file_list_response_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_file_list_response_free(_result);
            break :blk owned;
        };
    }

    pub fn file_content(self: *DefaultClient, file_id: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const file_id_z = try std.heap.c_allocator.dupeZ(u8, file_id);
        defer std.heap.c_allocator.free(file_id_z);
        var _out_ptr: [*c]u8 = undefined;
        var _out_len: usize = 0;
        var _out_cap: usize = 0;
        _ = c.literllm_default_client_file_content(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), file_id_z, &_out_ptr, &_out_len, &_out_cap);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        const _owned = try std.heap.c_allocator.dupe(u8, _out_ptr[0.._out_len]);
        c.literllm_free_bytes(_out_ptr, _out_len, _out_cap);
        return _owned;
    }

    pub fn create_batch(self: *DefaultClient, req: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const req_z = try std.heap.c_allocator.dupeZ(u8, req);
        defer std.heap.c_allocator.free(req_z);
        const req_handle = c.literllm_create_batch_request_from_json(req_z.ptr);
        const _result = c.literllm_default_client_create_batch(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), req_handle);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        c.literllm_create_batch_request_free(req_handle);
        return blk: {
            const _json_ptr = c.literllm_batch_object_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_batch_object_free(_result);
            break :blk owned;
        };
    }

    pub fn retrieve_batch(self: *DefaultClient, batch_id: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const batch_id_z = try std.heap.c_allocator.dupeZ(u8, batch_id);
        defer std.heap.c_allocator.free(batch_id_z);
        const _result = c.literllm_default_client_retrieve_batch(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), batch_id_z);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        return blk: {
            const _json_ptr = c.literllm_batch_object_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_batch_object_free(_result);
            break :blk owned;
        };
    }

    pub fn list_batches(self: *DefaultClient, query: ?[]const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const query_z: ?[:0]u8 = if (query) |v| try std.heap.c_allocator.dupeZ(u8, v) else null;
        defer if (query_z) |z| std.heap.c_allocator.free(z);
        const query_handle = if (query_z) |z| c.literllm_batch_list_query_from_json(z.ptr) else null;
        const _result = c.literllm_default_client_list_batches(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), query_handle);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        if (query_handle != null) c.literllm_batch_list_query_free(query_handle);
        return blk: {
            const _json_ptr = c.literllm_batch_list_response_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_batch_list_response_free(_result);
            break :blk owned;
        };
    }

    pub fn cancel_batch(self: *DefaultClient, batch_id: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const batch_id_z = try std.heap.c_allocator.dupeZ(u8, batch_id);
        defer std.heap.c_allocator.free(batch_id_z);
        const _result = c.literllm_default_client_cancel_batch(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), batch_id_z);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        return blk: {
            const _json_ptr = c.literllm_batch_object_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_batch_object_free(_result);
            break :blk owned;
        };
    }

    pub fn create_response(self: *DefaultClient, req: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const req_z = try std.heap.c_allocator.dupeZ(u8, req);
        defer std.heap.c_allocator.free(req_z);
        const req_handle = c.literllm_create_response_request_from_json(req_z.ptr);
        const _result = c.literllm_default_client_create_response(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), req_handle);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        c.literllm_create_response_request_free(req_handle);
        return blk: {
            const _json_ptr = c.literllm_response_object_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_response_object_free(_result);
            break :blk owned;
        };
    }

    pub fn retrieve_response(self: *DefaultClient, id: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const id_z = try std.heap.c_allocator.dupeZ(u8, id);
        defer std.heap.c_allocator.free(id_z);
        const _result = c.literllm_default_client_retrieve_response(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), id_z);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        return blk: {
            const _json_ptr = c.literllm_response_object_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_response_object_free(_result);
            break :blk owned;
        };
    }

    pub fn cancel_response(self: *DefaultClient, id: []const u8) (LiterLlmError || error{OutOfMemory})![]u8 {
        const id_z = try std.heap.c_allocator.dupeZ(u8, id);
        defer std.heap.c_allocator.free(id_z);
        const _result = c.literllm_default_client_cancel_response(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)), id_z);
        if (c.literllm_last_error_code() != 0) {
            return _first_error(LiterLlmError);
        }
        return blk: {
            const _json_ptr = c.literllm_response_object_to_json(_result);
            const _json_slice = std.mem.span(_json_ptr);
            const owned = try std.heap.c_allocator.dupe(u8, _json_slice);
            c.literllm_free_string(_json_ptr);
            c.literllm_response_object_free(_result);
            break :blk owned;
        };
    }

    /// Release the underlying FFI handle. Safe to call once per instance.
    pub fn free(self: *DefaultClient) void {
        c.literllm_default_client_free(@as(*c.LITERLLMDefaultClient, @ptrCast(self._handle)));
    }
};
