// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ce225afb0f073b0dc207b280d72a6696beaaa495bc3898fb2fa9cec185a20d8d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'dart:io';
import 'package:liter_llm/liter_llm.dart';
import 'package:liter_llm/src/liter_llm_bridge_generated/frb_generated.dart' show RustLib;

// E2e tests for category: parity
void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test('Canonical API surface definition for cross-binding parity verification', () async {
    final _request = await createChatCompletionRequestFromJson(json: '{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4o"}');
    final _mockUrl = "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/api_surface_parity";
        final _client = await LiterLlmBridge.createClient('test-key', baseUrl: _mockUrl);
    final result = await _client.chat(req: _request);
  });

}
