// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:60f17cf2c7cb97e8467b8630ebec33b40afaf8a67ccafbeaac46907e27082a85
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'dart:io';
import 'package:liter_llm/liter_llm.dart';
import 'package:liter_llm/src/liter_llm_bridge_generated/frb_generated.dart' show RustLib;

// E2e tests for category: responses
void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test('Response completes with empty output items', () async {
    final result = await LiterLlmBridge.createResponse();
  });

  test('Response created with a very large input text', () async {
    final result = await LiterLlmBridge.createResponse();
  });

  test('401 Unauthorized when creating a response with invalid API key', () async {
    await expectLater(LiterLlmBridge.createResponse(), throwsA(anything));
  });

  test('400 Bad Request when creating response with invalid model', () async {
    await expectLater(LiterLlmBridge.createResponse(), throwsA(anything));
  });

  test('404 Not Found when retrieving a nonexistent response', () async {
    await expectLater(LiterLlmBridge.retrieveResponse(), throwsA(anything));
  });

  test('Cancel an in-progress response', () async {
    final result = await LiterLlmBridge.cancelResponse();
  });

  test('Create a basic response using the Responses API', () async {
    final result = await LiterLlmBridge.createResponse();
  });

  test('Response that includes tool call output items', () async {
    final result = await LiterLlmBridge.createResponse();
  });

  test('Retrieve a previously created response', () async {
    final result = await LiterLlmBridge.retrieveResponse();
  });

}
