// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1fb630160ba90fa8c8e6102452e9b668002a6f6734abf00e69914c2ba8e4ab4d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import LiterLlm
import RustBridge

/// E2e tests for category: parity.
final class ParityTests: XCTestCase {
    func testApiSurfaceParity() async throws {
        // Canonical API surface definition for cross-binding parity verification
        let _request = try LiterLlm.chatCompletionRequestFromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4o\"}")
        let _client = try DefaultClient(apiKey: "test-key", baseUrl: ProcessInfo.processInfo.environment["MOCK_SERVER_URL"]! + "/fixtures/api_surface_parity")
        let result = try await _client.chat(_request)
    }

}
