# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4f25a8b7b3dfd89a506245762ff0a9c88ee0f1210dca8ef7077492f4c0f2854b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.AssistantMessage do
  @moduledoc "Assistant's response to a user message."

  @typedoc "Assistant's response to a user message."
  @type t :: %__MODULE__{
          content: String.t() | nil | nil,
          name: String.t() | nil,
          tool_calls: [map()] | nil,
          refusal: String.t() | nil,
          function_call: map() | nil
        }

  defstruct content: nil,
            name: nil,
            tool_calls: nil,
            refusal: nil,
            function_call: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
