# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4221ca28eaa258330e61a602c200691717d45fa5617b2c511006884d8ec182c1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.AudioContent do
  @moduledoc false

  @type t :: %__MODULE__{
          data: String.t() | nil,
          format: String.t() | nil
        }

  defstruct data: nil,
            format: nil
end
