# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:42ff4b72b86fd768510795a839236a4864fd4fd61614343e2ac6d94e4aa9f9b1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.AuthHeaderFormat do
  @moduledoc "How the API key is sent in the HTTP request."

  @typedoc "How the API key is sent in the HTTP request."
  @type t :: term()

  @typedoc "Bearer token: `Authorization: Bearer <key>`"
  @type bearer :: :bearer
  @typedoc "Custom header: e.g., `X-Api-Key: <key>`"
  @type api_key :: %{type: :api_key, value: String.t()}
  @typedoc "No authentication required."
  @type none_variant :: :none
end
