# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:718a9bb2066b4d98f177745b5c3db63c834a58163b5677360c01f624add6c233
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.AuthHeaderFormat do
  @moduledoc "How the API key is sent in the HTTP request."

  @typedoc "How the API key is sent in the HTTP request."
  @type t :: term()

  @typedoc "Bearer token: `Authorization: Bearer <key>`"
  @type bearer :: :bearer
  @typedoc "Custom header: e.g., `X-Api-Key: <key>`"
  @type api_key :: %{type: :api_key, value: String.t()}
  @typedoc "No authentication required."
  @type none_variant :: :none
end
