# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0c694843abf5c6a9fc8b410dfa73aea7c94ee538a40dc746dd72c50e7c986f97
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.AuthHeaderFormat do
  @moduledoc "How the API key is sent in the HTTP request."

  @typedoc "How the API key is sent in the HTTP request."
  @type t :: term()

  @typedoc "Bearer token: `Authorization: Bearer <key>`"
  @type bearer :: :bearer
  @typedoc "Custom header: e.g., `X-Api-Key: <key>`"
  @type api_key :: %{type: :api_key, value: String.t()}
  @typedoc "No authentication required."
  @type none_variant :: :none
end
