# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4d8aec952231935aba5be3de00c8a64c38116e6b1edbbd302c8d5fdb1159eb44
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.BatchStatus do
  @moduledoc false

  @type t :: :validating | :failed | :in_progress | :finalizing | :completed | :expired | :cancelling | :cancelled

  @validating :validating
  @failed :failed
  @in_progress :in_progress
  @finalizing :finalizing
  @completed :completed
  @expired :expired
  @cancelling :cancelling
  @cancelled :cancelled

  @spec validating() :: t()
  def validating, do: @validating
  @spec failed() :: t()
  def failed, do: @failed
  @spec in_progress() :: t()
  def in_progress, do: @in_progress
  @spec finalizing() :: t()
  def finalizing, do: @finalizing
  @spec completed() :: t()
  def completed, do: @completed
  @spec expired() :: t()
  def expired, do: @expired
  @spec cancelling() :: t()
  def cancelling, do: @cancelling
  @spec cancelled() :: t()
  def cancelled, do: @cancelled
end
