# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:990a8effc943d1d0f9c7ef763981d4cd9b10eefb9c9b4f11e1222eac8fca8442
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.BatchListQuery do
  @moduledoc "Query parameters for listing batches."

  @typedoc "Query parameters for listing batches."
  @type t :: %__MODULE__{
          limit: non_neg_integer() | nil,
          after: String.t() | nil
        }

  defstruct limit: nil,
            after: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
