# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b20f171c2445ca22a09313238ab4e2924e6dfab116139d44c26fda57bfe8feb4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.BudgetConfig do
  @moduledoc "Configuration for budget enforcement."

  @typedoc "Configuration for budget enforcement."
  @type t :: %__MODULE__{
          global_limit: float() | nil,
          model_limits: map(),
          enforcement: String.t() | nil
        }

  defstruct global_limit: nil,
            model_limits: %{},
            enforcement: :hard
  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
        |> Map.from_struct()
        |> Jason.Encoder.encode(opts)
    end
  end

end
