# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0c694843abf5c6a9fc8b410dfa73aea7c94ee538a40dc746dd72c50e7c986f97
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.CacheBackend do
  @moduledoc "Storage backend for the response cache."

  @typedoc "Storage backend for the response cache."
  @type t :: term()

  @typedoc "In-memory LRU cache (default). No external dependencies."
  @type memory :: :memory
  @typedoc "OpenDAL-backed storage. Supports 40+ backends (S3, Redis, GCS, local FS, etc.)."
  @type open_dal :: %{type: :open_dal, scheme: String.t(), config: map()}
end
