# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:318c58a133a4b0cf29ba0b9369fa09fc9239a2be870dbe6de9d73eef61fda91d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule LiterLlm.CacheBackend do
  @moduledoc "Storage backend for the response cache."

  @typedoc "Storage backend for the response cache."
  @type t :: term()

  @typedoc "In-memory LRU cache (default). No external dependencies."
  @type memory :: :memory
  @typedoc "OpenDAL-backed storage. Supports 40+ backends (S3, Redis, GCS, local FS, etc.)."
  @type open_dal :: %{type: :open_dal, scheme: String.t(), config: map()}
end
