# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a0bd1f28c70bf315b13bee1d6ae182c64eb60697fe5b47d86276a89c13093fe2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.ChatCompletionResponse do
  @moduledoc "Chat completion response from the API."

  @typedoc "Chat completion response from the API."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          object: String.t() | nil,
          created: non_neg_integer(),
          model: String.t() | nil,
          choices: [map()],
          usage: map() | nil,
          system_fingerprint: String.t() | nil,
          service_tier: String.t() | nil
        }

  defstruct id: nil,
            object: nil,
            created: 0,
            model: nil,
            choices: [],
            usage: nil,
            system_fingerprint: nil,
            service_tier: nil
end
