# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c7947a41084f71e69944233535fbeda5cd13b37144078f1895b6b57a7802d3fe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ChatCompletionChunk do
  @moduledoc "A streamed chunk of a chat completion response."

  @typedoc "A streamed chunk of a chat completion response."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          object: String.t() | nil,
          created: non_neg_integer(),
          model: String.t() | nil,
          choices: [LiterLlm.StreamChoice.t()],
          usage: LiterLlm.Usage.t() | nil,
          system_fingerprint: String.t() | nil,
          service_tier: String.t() | nil
        }

  defstruct id: nil,
            object: nil,
            created: 0,
            model: nil,
            choices: [],
            usage: nil,
            system_fingerprint: nil,
            service_tier: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
