# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c892c5ad61c5b9376089e0d461b22e97ed9f5766653c5d3c2e5bf8cca5950f37
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ChatCompletionTool do
  @moduledoc "A tool the model can invoke (currently, all tools are functions)."

  @typedoc "A tool the model can invoke (currently, all tools are functions)."
  @type t :: %__MODULE__{
          tool_type: String.t() | nil,
          function: map()
        }

  defstruct tool_type: :function,
            function: nil
end
