# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c892c5ad61c5b9376089e0d461b22e97ed9f5766653c5d3c2e5bf8cca5950f37
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.Choice do
  @moduledoc "A single completion choice."

  @typedoc "A single completion choice."
  @type t :: %__MODULE__{
          index: non_neg_integer(),
          message: map(),
          finish_reason: String.t() | nil | nil
        }

  defstruct index: 0,
            message: nil,
            finish_reason: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
