# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8b73f985140a2c4e1013dd872f515fd8cd9a03bd3110d30efc3d06c1b2dbca01
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.Choice do
  @moduledoc false

  defstruct index: 0,
            message: nil,
            finish_reason: :stop
end
