# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1c1a4f40437bd3664405b1b60a53b4dc867f8b6f298baac7d0bf32a63ff9e517
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.CircuitState do
  @moduledoc "Observable state of a circuit breaker."

  @typedoc "Observable state of a circuit breaker."
  @type t :: :closed | :open | :half_open

  @closed :closed
  @open :open
  @half_open :half_open

  @doc "Requests flow through normally."
  @spec closed() :: t()
  def closed, do: @closed
  @doc "All requests are rejected; the circuit is waiting for the backoff to elapse."
  @spec open() :: t()
  def open, do: @open
  @doc "One probe request is allowed through to test service health."
  @spec half_open() :: t()
  def half_open, do: @half_open
end
