# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0ad579c4e6402a59f477d57e2df40488d9809a1a212e52fe47279587ff8c442e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule LiterLlm.ContentPart do
  @moduledoc "A single content part in a user message — text, image, document, or audio."

  @typedoc "A single content part in a user message — text, image, document, or audio."
  @type t :: term()

  @typedoc "Plain text."
  @type text :: %{type: :text, text: String.t()}
  @typedoc "Image identified by URL (with optional detail level)."
  @type image_url :: %{type: :image_url, image_url: LiterLlm.ImageUrl.t()}
  @typedoc "Document file (PDF, CSV, etc.) as base64 or URL."
  @type document :: %{type: :document, document: LiterLlm.DocumentContent.t()}
  @typedoc "Audio input as base64."
  @type input_audio :: %{type: :input_audio, input_audio: LiterLlm.AudioContent.t()}
end
