# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:383ce0fe9a713159e907549723c530a8df38c82a3231691af9c95d14d7b37620
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.CreateTranscriptionRequest do
  @moduledoc "Request to transcribe audio into text."

  @typedoc "Request to transcribe audio into text."
  @type t :: %__MODULE__{
          model: String.t() | nil,
          file: String.t() | nil,
          language: String.t() | nil,
          prompt: String.t() | nil,
          response_format: String.t() | nil,
          temperature: float() | nil
        }

  defstruct model: nil,
            file: nil,
            language: nil,
            prompt: nil,
            response_format: nil,
            temperature: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Jason.Encoder.encode(opts)
    end
  end
end
