# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5f17ebe676822cfa77ea15c5d293e0cac18cf5c5fd2e4c3c2b8974a130abfd16
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.CreateTranscriptionRequest do
  @moduledoc "Request to transcribe audio into text."

  @typedoc "Request to transcribe audio into text."
  @type t :: %__MODULE__{
          model: String.t() | nil,
          file: String.t() | nil,
          language: String.t() | nil,
          prompt: String.t() | nil,
          response_format: String.t() | nil,
          temperature: float() | nil
        }

  defstruct model: nil,
            file: nil,
            language: nil,
            prompt: nil,
            response_format: nil,
            temperature: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
