# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:338653fa421580c3070776c34f1f5a34b26937aa1b3e588c2cab60685b1f2c26
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.CreateImageRequest do
  @moduledoc "Request to create images from a text prompt."

  defstruct prompt: "",
            model: "",
            n: 0,
            size: "",
            quality: "",
            style: "",
            response_format: "",
            user: ""
end
