# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:264cc40be433d4a3b6743f3dee93a34517b309fcaad325bce5e7a2e79dc3703f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.DocumentContent do
  @moduledoc false

  @type t :: %__MODULE__{
          data: String.t() | nil,
          media_type: String.t() | nil
        }

  defstruct data: nil,
            media_type: nil
end
