# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:52effca2513e1c5f8a9a5b90a372d645388de4b92e4f822acc38d97502c322b6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.DocumentContent do
  @moduledoc "PDF/document content part for vision-capable models."

  @typedoc "PDF/document content part for vision-capable models."
  @type t :: %__MODULE__{
          data: String.t() | nil,
          media_type: String.t() | nil
        }

  defstruct data: nil,
            media_type: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
