# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:af68153e3768e9662950ef62685f2d0247c81d45f8079ee40d9c5e27467e64aa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.EmbeddingResponse do
  @moduledoc "Embedding response."

  @typedoc "Embedding response."
  @type t :: %__MODULE__{
          object: String.t() | nil,
          data: [map()],
          model: String.t() | nil,
          usage: map() | nil
        }

  defstruct object: nil,
            data: [],
            model: nil,
            usage: nil
end
