# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:797e09398ae0b95dd0e3de94d7374eedafcd20d08532c7cf378cbcd09e3083a7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.EmbeddingInput do
  @moduledoc "Text or texts to embed."

  @typedoc "Text or texts to embed."
  @type t :: term()

  @typedoc "Single text string."
  @type single :: %{type: :single, value: String.t()}
  @typedoc "Multiple text strings (batch embedding)."
  @type multiple :: %{type: :multiple, value: [String.t()]}
end
