# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4fe8d3411dc9c937765211959f3ac9d4fc3049ccb38d0826d86e3bdb98f705cf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.EmbeddingObject do
  @moduledoc "A single embedding vector."

  @typedoc "A single embedding vector."
  @type t :: %__MODULE__{
          object: String.t() | nil,
          embedding: [float()],
          index: non_neg_integer()
        }

  defstruct object: nil,
            embedding: [],
            index: 0
end
