# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:65c252a3185b482ec17c4a553a31246b06919f03df72fdceb8d41439a4e2591d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.EmbeddingInput do
  @moduledoc false

  @type t :: term()

  @type single :: %{type: :single, value_0: term()}
  @type multiple :: %{type: :multiple, value_0: term()}
end
