# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a893cf266c5d7883c5f9fb3f1de2b60369673c481765f5f8328cfa43608d2d06
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.EmbeddingInput do
  @moduledoc "Text or texts to embed."

  @typedoc "Text or texts to embed."
  @type t :: term()

  @typedoc "Single text string."
  @type single :: %{type: :single, value: String.t()}
  @typedoc "Multiple text strings (batch embedding)."
  @type multiple :: %{type: :multiple, value: [String.t()]}
end
