# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3fb07515ba02077671946cad7f111c0c7840343537bb31d1488bc316651dca95
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.Enforcement do
  @moduledoc "How budget limits are enforced."

  @typedoc "How budget limits are enforced."
  @type t :: :hard | :soft

  @hard :hard
  @soft :soft

  @doc "Reject requests that would exceed the budget with [`LiterLlmError::BudgetExceeded`]."
  @spec hard() :: t()
  def hard, do: @hard
  @doc "Allow requests through but emit a `tracing::warn!` when the budget is exceeded."
  @spec soft() :: t()
  def soft, do: @soft
end
