# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1c1a4f40437bd3664405b1b60a53b4dc867f8b6f298baac7d0bf32a63ff9e517
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.FilePurpose do
  @moduledoc "Purpose of an uploaded file."

  @typedoc "Purpose of an uploaded file."
  @type t :: :assistants | :batch | :fine_tune | :vision

  @assistants :assistants
  @batch :batch
  @fine_tune :fine_tune
  @vision :vision

  @doc "File for use with Assistants API."
  @spec assistants() :: t()
  def assistants, do: @assistants
  @doc "File for batch processing."
  @spec batch() :: t()
  def batch, do: @batch
  @doc "File for fine-tuning."
  @spec fine_tune() :: t()
  def fine_tune, do: @fine_tune
  @doc "File for vision/image tasks."
  @spec vision() :: t()
  def vision, do: @vision
end
