# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.FinishReason do
  @moduledoc "Why a choice stopped generating tokens."

  @type t :: :stop | :length | :tool_calls | :content_filter | :function_call | :other

  @stop :stop
  @length :length
  @tool_calls :tool_calls
  @content_filter :content_filter
  @function_call :function_call
  @other :other

  @spec stop() :: t()
  def stop, do: @stop
  @spec length() :: t()
  def length, do: @length
  @spec tool_calls() :: t()
  def tool_calls, do: @tool_calls
  @spec content_filter() :: t()
  def content_filter, do: @content_filter
  @spec function_call() :: t()
  def function_call, do: @function_call
  @spec other() :: t()
  def other, do: @other
end
