# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:990a8effc943d1d0f9c7ef763981d4cd9b10eefb9c9b4f11e1222eac8fca8442
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.HealthStatus do
  @moduledoc "The result of a single health probe."

  @typedoc "The result of a single health probe."
  @type t :: :healthy | :unhealthy

  @healthy :healthy
  @unhealthy :unhealthy

  @doc "The probe succeeded; the upstream is reachable."
  @spec healthy() :: t()
  def healthy, do: @healthy
  @doc "The probe failed; the upstream may be down."
  @spec unhealthy() :: t()
  def unhealthy, do: @unhealthy
end
