# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9ebda2bedb27bc07d8a4cfcbfadd55fd159de7f875fcb63308eaee6e1c3a895d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.HealthStatus do
  @moduledoc "The result of a single health probe."

  @typedoc "The result of a single health probe."
  @type t :: :healthy | :unhealthy

  @healthy :healthy
  @unhealthy :unhealthy

  @doc "The probe succeeded; the upstream is reachable."
  @spec healthy() :: t()
  def healthy, do: @healthy
  @doc "The probe failed; the upstream may be down."
  @spec unhealthy() :: t()
  def unhealthy, do: @unhealthy
end
