# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9a6e94386d8a58656779a53565013dd1754ed706a423955d86280140a736bb05
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ImagesResponse do
  @moduledoc "Response containing generated images."

  @typedoc "Response containing generated images."
  @type t :: %__MODULE__{
          created: non_neg_integer(),
          data: [map()]
        }

  defstruct created: 0,
            data: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
