# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.ImageDetail do
  @moduledoc false

  @type t :: :low | :high | :auto

  @low :low
  @high :high
  @auto :auto

  @spec low() :: t()
  def low, do: @low
  @spec high() :: t()
  def high, do: @high
  @spec auto() :: t()
  def auto, do: @auto
end
