# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ee34d53dd7b53bbfa1e1d683dc961e1355a375403d7bca2db0da948bbbf6d364
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.IntentPrototype do
  @moduledoc "An intent prototype: `(intent_name, prototype_embedding, target_model_id)`."

  @typedoc "An intent prototype: `(intent_name, prototype_embedding, target_model_id)`."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          embedding: [float()],
          model: String.t() | nil
        }

  defstruct name: nil,
            embedding: [],
            model: nil
end
