# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b159ec7bf40f2249b9f5696d5819688bca2310a2b26cc9acae8194e6255f8b03
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.JsonSchemaFormat do
  @moduledoc "JSON Schema specification for constrained output."

  @typedoc "JSON Schema specification for constrained output."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          description: String.t() | nil,
          schema: String.t() | nil,
          strict: boolean() | nil
        }

  defstruct name: nil,
            description: nil,
            schema: nil,
            strict: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
