# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d4c3009a398398e22a9010c38eb2326cc342cab0fe4882a9d58aede0621e7701
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.ModerationRequest do
  @moduledoc "Request to classify content for policy violations."

  defstruct input: :single,
            model: ""
end
