# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1213a045f6c720bcab8727df8faa87409c027be1ac51394a1bf33f9c83c5d07c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ModelsListResponse do
  @moduledoc "Response listing available models."

  @typedoc "Response listing available models."
  @type t :: %__MODULE__{
          object: String.t() | nil,
          data: [map()]
        }

  defstruct object: nil,
            data: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
