# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4bc8f95b938ffbb1d79348e920e0593aabc8edea88fcae3430283d2711d55ddf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.OcrRequest do
  @moduledoc "An OCR request."

  @typedoc "An OCR request."
  @type t :: %__MODULE__{
          model: String.t() | nil,
          document: String.t() | nil,
          pages: [non_neg_integer()] | nil,
          include_image_base64: boolean() | nil
        }

  defstruct model: nil,
            document: :url,
            pages: nil,
            include_image_base64: nil
end
