# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2056fea64bf6b2c8a4850aaade9cf52a7d3d9ba731594e4cc276f6f5dc460e32
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.OcrDocument do
  @moduledoc "Document input for OCR — either a URL or inline base64 data."

  @typedoc "Document input for OCR — either a URL or inline base64 data."
  @type t :: term()

  @typedoc "A publicly accessible document URL."
  @type url :: %{type: :url, url: String.t()}
  @typedoc "Inline base64-encoded document data."
  @type base64 :: %{type: :base64, data: String.t(), media_type: String.t()}
end
