# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.OcrResponse do
  @moduledoc "An OCR response."

  defstruct pages: [],
            model: "",
            usage: nil
end
