# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:db8ac67abdecfd52551c8d470bfdb9844d9a71193d593fd3f91985daf1bdc4bc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.OcrResponse do
  @moduledoc "An OCR response."

  @typedoc "An OCR response."
  @type t :: %__MODULE__{
          pages: [map()],
          model: String.t() | nil,
          usage: map() | nil
        }

  defstruct pages: [],
            model: nil,
            usage: nil
end
