# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dc4a57e83bd2bf7170994f03a95e8e40d68454a352751f89dbb7a64bbb245537
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.OcrDocument do
  @moduledoc "Document input for OCR — either a URL or inline base64 data."

  @type t :: term()

  @type url :: %{type: :url, url: String.t()}
  @type base64 :: %{type: :base64, data: String.t(), media_type: String.t()}
end
