# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fe64a8a06beeb01b5344005fa07dcdfdf3e244d772ace0f89dbba84b0541ca2d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.OcrImage do
  @moduledoc "An image extracted from an OCR page."

  @typedoc "An image extracted from an OCR page."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          image_base64: String.t() | nil
        }

  defstruct id: nil,
            image_base64: nil
end
