# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c044febf376aed475b4851f0d3929acdad38b0b425fff3a5a60938c4bdfb0cde
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.OcrResponse do
  @moduledoc "An OCR response."

  @typedoc "An OCR response."
  @type t :: %__MODULE__{
          pages: [map()],
          model: String.t() | nil,
          usage: map() | nil
        }

  defstruct pages: [],
            model: nil,
            usage: nil
end
