# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:561e842050a4e0df6de070b0fde43848f2789ddf3578ad6a364633032c565b61
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.PromptTokensDetails do
  @moduledoc """
  Breakdown of tokens used in the prompt portion of a request.

  `cached_tokens` is included in `Usage::prompt_tokens` — it is *not* an
  additional charge on top of the prompt token count. When pricing supports
  a `cache_read_input_token_cost`, the cached portion is billed at the
  discounted rate and the remainder at the regular input rate.
  """

  @typedoc "Breakdown of tokens used in the prompt portion of a request."
  @type t :: %__MODULE__{
          cached_tokens: non_neg_integer(),
          audio_tokens: non_neg_integer()
        }

  defstruct cached_tokens: 0,
            audio_tokens: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
