# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a2643c3023f0f24a705285bb57661b14e33e1ff0fc1ec27e229d40f9b7d39691
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ProviderConfig do
  @moduledoc """
  Static configuration for a single provider entry in providers.json.

  This struct deliberately does not include capability flags or streaming
  format, which are accessed via the [`capabilities`] function.
  """

  @typedoc "Static configuration for a single provider entry in providers.json."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          display_name: String.t() | nil,
          base_url: String.t() | nil,
          auth: LiterLlm.AuthConfig.t() | nil,
          endpoints: [String.t()] | nil,
          model_prefixes: [String.t()] | nil,
          param_mappings: map() | nil
        }

  defstruct name: nil,
            display_name: nil,
            base_url: nil,
            auth: nil,
            endpoints: nil,
            model_prefixes: nil,
            param_mappings: nil
end
