# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9ebda2bedb27bc07d8a4cfcbfadd55fd159de7f875fcb63308eaee6e1c3a895d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ProviderConfig do
  @moduledoc """
  Static configuration for a single provider entry in providers.json.

  This struct deliberately does not include capability flags or streaming
  format, which are accessed via the [`capabilities`] function.  Keeping
  these fields separate preserves backward compatibility with all generated
  binding code that constructs `ProviderConfig` using struct literal syntax.
  """

  @typedoc "Static configuration for a single provider entry in providers.json."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          display_name: String.t() | nil,
          base_url: String.t() | nil,
          auth: map() | nil,
          endpoints: [String.t()] | nil,
          model_prefixes: [String.t()] | nil,
          param_mappings: map() | nil
        }

  defstruct name: nil,
            display_name: nil,
            base_url: nil,
            auth: nil,
            endpoints: nil,
            model_prefixes: nil,
            param_mappings: nil
end
