# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5ab53abee9ad8a282dfd709d969c3cf38af90f6c41a33626ee0612732e7f3b65
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule LiterLlm.ReasoningEffort do
  @moduledoc "Controls how much reasoning effort the model should use."

  @typedoc "Controls how much reasoning effort the model should use."
  @type t :: :low | :medium | :high

  @low :low
  @medium :medium
  @high :high

  @spec low() :: t()
  def low, do: @low
  @spec medium() :: t()
  def medium, do: @medium
  @spec high() :: t()
  def high, do: @high
end
