# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:78e5a94b16211ba93bc0e296e2ab2f7cf71bdf590a0cee0d82270d63ad38403c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.ReasoningEffort do
  @moduledoc "Controls how much reasoning effort the model should use."

  @type t :: :low | :medium | :high

  @low :low
  @medium :medium
  @high :high

  @spec low() :: t()
  def low, do: @low
  @spec medium() :: t()
  def medium, do: @medium
  @spec high() :: t()
  def high, do: @high
end
