# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:07562382b502a5b7ab1c75b472a27ccfc096d0dfe06c87c012ca58af37b50df9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule LiterLlm.ReasoningEffort do
  @moduledoc "Controls how much reasoning effort the model should use."

  @typedoc "Controls how much reasoning effort the model should use."
  @type t :: :low | :medium | :high

  @low :low
  @medium :medium
  @high :high

  @spec low() :: t()
  def low, do: @low
  @spec medium() :: t()
  def medium, do: @medium
  @spec high() :: t()
  def high, do: @high
end
