# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.RerankResponse do
  @moduledoc "Response from the rerank endpoint."

  defstruct id: nil,
            results: [],
            meta: nil
end
