# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4fe8d3411dc9c937765211959f3ac9d4fc3049ccb38d0826d86e3bdb98f705cf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.RerankDocument do
  @moduledoc "A document to be reranked — either a plain string or an object with a text field."

  @typedoc "A document to be reranked — either a plain string or an object with a text field."
  @type t :: term()

  @typedoc "Plain text document content."
  @type text :: %{type: :text, value: String.t()}
  @typedoc "Document with explicit text field (may include metadata)."
  @type object :: %{type: :object, text: String.t()}

  def object(text), do: {:object, %{text: text}}
end
