# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:990a8effc943d1d0f9c7ef763981d4cd9b10eefb9c9b4f11e1222eac8fca8442
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.RerankDocument do
  @moduledoc "A document to be reranked — either a plain string or an object with a text field."

  @typedoc "A document to be reranked — either a plain string or an object with a text field."
  @type t :: term()

  @typedoc "Plain text document content."
  @type text :: %{type: :text, value: String.t()}
  @typedoc "Document with explicit text field (may include metadata)."
  @type object :: %{type: :object, text: String.t()}

  def object(text), do: {:object, %{text: text}}
end
