# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b34f5dac0a6af082b71cab3b75e126050fd38402a73d6d3ff06130b6fe7d8875
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.RerankResponse do
  @moduledoc "Response from the rerank endpoint."

  @typedoc "Response from the rerank endpoint."
  @type t :: %__MODULE__{
  id: String.t() | nil,
  results: [LiterLlm.RerankResult.t()],
  meta: String.t() | nil
  }

  defstruct id: nil,
  results: [],
  meta: nil
end
