# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6b9bd4b565756e1f7dbaf542124f33d20f2fbf9bae785a1ebbe698ae983f1892
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.RerankResponse do
  @moduledoc "Response from the rerank endpoint."

  @typedoc "Response from the rerank endpoint."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          results: [map()],
          meta: String.t() | nil
        }

  defstruct id: nil,
            results: [],
            meta: nil
end
