# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9a6e94386d8a58656779a53565013dd1754ed706a423955d86280140a736bb05
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ResponseOutputItem do
  @moduledoc "A single output item from the response."

  @typedoc "A single output item from the response."
  @type t :: %__MODULE__{
          item_type: String.t() | nil,
          content: String.t() | nil
        }

  defstruct item_type: nil,
            content: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
