# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:176739fe9d6ce30853f573d13284bbdb7c76b077d2ec8c89d5bbed21a7f34380
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://example.invalid/alef
defmodule LiterLlm.ResponseUsage do
  @moduledoc false

  defstruct input_tokens: 0,
            output_tokens: 0,
            total_tokens: 0
end
