# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2056fea64bf6b2c8a4850aaade9cf52a7d3d9ba731594e4cc276f6f5dc460e32
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ResponseFormat do
  @moduledoc "Response format constraint."

  @typedoc "Response format constraint."
  @type t :: term()

  @typedoc "Plain text output (default)."
  @type text :: :text
  @typedoc "Output must be valid JSON object (no schema validation)."
  @type json_object :: :json_object
  @typedoc "Output must conform to the specified JSON schema."
  @type json_schema :: %{type: :json_schema, json_schema: LiterLlm.JsonSchemaFormat.t()}
end
