# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e9f65b8f28b2745420bea14218de9fe0b9fe24f0818b0451bda5ba79f520bdf3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.ResponseOutputItem do
  @moduledoc "A single output item from the response."

  @typedoc "A single output item from the response."
  @type t :: %__MODULE__{
          item_type: String.t() | nil,
          content: String.t() | nil
        }

  defstruct item_type: nil,
            content: nil
  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
        |> Map.from_struct()
        |> Jason.Encoder.encode(opts)
    end
  end

end
