# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a7c064e23690d6da0a7c0734d1219488b1ca34c78c93e3287518f9c69d67f638
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ResponseFormat do
  @moduledoc "Response format constraint."

  @typedoc "Response format constraint."
  @type t :: term()

  @typedoc "Plain text output (default)."
  @type text :: :text
  @typedoc "Output must be valid JSON object (no schema validation)."
  @type json_object :: :json_object
  @typedoc "Output must conform to the specified JSON schema."
  @type json_schema :: %{type: :json_schema, json_schema: LiterLlm.JsonSchemaFormat.t()}
end
