# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fdc311f15b9d758ef6975e6a1251783a8e073b3c13d75062d28bd4726bb1c6a2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.SpecificFunction do
  @moduledoc "Name of the specific function to invoke."

  @typedoc "Name of the specific function to invoke."
  @type t :: %__MODULE__{
          name: String.t() | nil
        }

  defstruct name: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
