# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:633c6ca3d945229d202d1cc5029bc08f1583a5cc88cc0aaa95286a909df9c771
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.SpecificToolChoice do
  @moduledoc "Directive to call a specific tool."

  @typedoc "Directive to call a specific tool."
  @type t :: %__MODULE__{
          choice_type: String.t() | nil,
          function: map()
        }

  defstruct choice_type: :function,
            function: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
