# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7944d9976ed5e784d58bb60b20a64df43c6faa98460b1282aa94dfadc636b045
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.SpecificFunction do
  @moduledoc "Name of the specific function to invoke."

  @typedoc "Name of the specific function to invoke."
  @type t :: %__MODULE__{
          name: String.t() | nil
        }

  defstruct name: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
