# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1c2da475a93d435187a14de8098d1aaee2346f1e3199d84696805e5f6265736b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.StreamOptions do
  @moduledoc "Options for streaming responses."

  @typedoc "Options for streaming responses."
  @type t :: %__MODULE__{
          include_usage: boolean() | nil
        }

  defstruct include_usage: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
