# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:62c469a06c4323b14a369facae074d1ae15d9e07a5080dad5756fe5e9eab3f0c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.StreamDelta do
  @moduledoc "Incremental delta in a stream chunk."

  @typedoc "Incremental delta in a stream chunk."
  @type t :: %__MODULE__{
          role: String.t() | nil,
          content: String.t() | nil,
          tool_calls: [map()] | nil,
          function_call: map() | nil,
          refusal: String.t() | nil
        }

  defstruct role: nil,
            content: nil,
            tool_calls: nil,
            function_call: nil,
            refusal: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
