# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f2be24356f224d7cafb965a88977ab27840a65ecb9a9ba6cce1110d593455279
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule LiterLlm.StreamOptions do
  @moduledoc "Options for streaming responses."

  @typedoc "Options for streaming responses."
  @type t :: %__MODULE__{
          include_usage: boolean() | nil
        }

  defstruct include_usage: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
