# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:74b52fa196f14df9210b1bd628353a523f716b379110791654db54b61e150f49
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ToolChoice do
  @moduledoc "Tool usage mode or a specific tool to call."

  @typedoc "Tool usage mode or a specific tool to call."
  @type t :: term()

  @typedoc "Predefined mode: auto, required, or none."
  @type mode :: %{type: :mode, value: map()}
  @typedoc "Force a specific tool to be called."
  @type specific :: %{type: :specific, tool_choice: LiterLlm.SpecificToolChoice.t()}
end
