# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9a6e94386d8a58656779a53565013dd1754ed706a423955d86280140a736bb05
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ToolChoiceMode do
  @moduledoc "Tool choice mode."

  @typedoc "Tool choice mode."
  @type t :: :auto | :required | :none

  @auto :auto
  @required :required
  @none :none

  @doc "Model may or may not call tools; default behavior."
  @spec auto() :: t()
  def auto, do: @auto
  @doc "Model must call at least one tool."
  @spec required() :: t()
  def required, do: @required
  @doc "Model must not call any tools."
  @spec none() :: t()
  def none, do: @none
end
