# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c892c5ad61c5b9376089e0d461b22e97ed9f5766653c5d3c2e5bf8cca5950f37
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ToolType do
  @moduledoc """
  The type discriminator for tool/tool-call objects.

  Per the OpenAI spec this is always `"function"`. Using an enum enforces
  that constraint at the type level and rejects any other value on
  deserialization.
  """

  @typedoc "The type discriminator for tool/tool-call objects."
  @type t :: :function

  @function :function

  @spec function() :: t()
  def function, do: @function
end
