# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d954bd0ab4851664242c5d5bf76bcc6f4c84e06fe6cd42e3effba8a0bb5c3dcf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ToolChoice do
  @moduledoc "Tool usage mode or a specific tool to call."

  @typedoc "Tool usage mode or a specific tool to call."
  @type t :: term()

  @typedoc "Predefined mode: auto, required, or none."
  @type mode :: %{type: :mode, value: map()}
  @typedoc "Force a specific tool to be called."
  @type specific :: %{type: :specific, tool_choice: LiterLlm.SpecificToolChoice.t()}
end
