# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:52effca2513e1c5f8a9a5b90a372d645388de4b92e4f822acc38d97502c322b6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.ToolChoiceMode do
  @moduledoc "Tool choice mode."

  @typedoc "Tool choice mode."
  @type t :: :auto | :required | :none

  @auto :auto
  @required :required
  @none :none

  @doc "Model may or may not call tools; default behavior."
  @spec auto() :: t()
  def auto, do: @auto
  @doc "Model must call at least one tool."
  @spec required() :: t()
  def required, do: @required
  @doc "Model must not call any tools."
  @spec none() :: t()
  def none, do: @none
end
