# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:620080f740c9a9fd439dcdd361edf2be7b9d7a29443c4fb5e1f3aeaee9e4b67c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.ToolType do
  @moduledoc """
  The type discriminator for tool/tool-call objects.

  Per the OpenAI spec this is always `"function"`. Using an enum enforces
  that constraint at the type level and rejects any other value on
  deserialization.
  """

  @typedoc "The type discriminator for tool/tool-call objects."
  @type t :: :function

  @function :function

  @spec function() :: t()
  def function, do: @function
end
