# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8eac0267a7c84310b2cf7f8e6bc84b23de9f2dc29642b471b8bee9225f5c748a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.TranscriptionSegment do
  @moduledoc "A segment of transcribed audio with timing information."

  @typedoc "A segment of transcribed audio with timing information."
  @type t :: %__MODULE__{
          id: non_neg_integer(),
          start: float(),
          end: float(),
          text: String.t() | nil
        }

  defstruct id: 0,
            start: 0.0,
            end: 0.0,
            text: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
