# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:419204b66f16f0a46756e52ee2a70660e87d41eea851478a78189354fad3dc5d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule LiterLlm.TranscriptionResponse do
  @moduledoc "Response from a transcription request."

  @typedoc "Response from a transcription request."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          language: String.t() | nil,
          duration: float() | nil,
          segments: [map()] | nil
        }

  defstruct text: nil,
            language: nil,
            duration: nil,
            segments: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
