# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2655d4d8248bf6c574e802ce76430a9f8d3c0ab6a3b1e2d4c5445d59a18d75f7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule LiterLlm.TranscriptionSegment do
  @moduledoc "A segment of transcribed audio with timing information."

  @typedoc "A segment of transcribed audio with timing information."
  @type t :: %__MODULE__{
          id: non_neg_integer(),
          start: float(),
          end: float(),
          text: String.t() | nil
        }

  defstruct id: 0,
            start: 0.0,
            end: 0.0,
            text: nil
end
