# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:77063898f58ec52d842e4a09b0a1369b7345aeafae7b09befc8525ded390ea34
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.Usage do
  @moduledoc "Token-usage accounting returned by the provider on each completion / embedding call."

  @typedoc "Token-usage accounting returned by the provider on each completion / embedding call."
  @type t :: %__MODULE__{
          prompt_tokens: non_neg_integer(),
          completion_tokens: non_neg_integer(),
          total_tokens: non_neg_integer(),
          prompt_tokens_details: map() | nil
        }

  defstruct prompt_tokens: 0,
            completion_tokens: 0,
            total_tokens: 0,
            prompt_tokens_details: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
