# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:561e842050a4e0df6de070b0fde43848f2789ddf3578ad6a364633032c565b61
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule LiterLlm.UserContent do
  @moduledoc "User message content as either plain text or a list of multimodal parts."

  @typedoc "User message content as either plain text or a list of multimodal parts."
  @type t :: term()

  @typedoc "Plain text content."
  @type text :: %{type: :text, value: String.t()}
  @typedoc "Array of content parts (text, images, documents, audio)."
  @type parts :: %{type: :parts, value: [map()]}
end
