// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:90c916ed5403686374c478cb4c8f53203ae22f29bc7eb29024635c245e863838
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using LiterLlm;
using static LiterLlm.LiterLlmLib;

namespace LiterLlm
{
    /// <summary>E2e tests for category: configuration.</summary>
    public class ConfigurationTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public async Task Test_CustomBaseUrl()
        {
            // Client configured with a custom base URL routes all requests to that endpoint
            var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/custom_base_url";
            var client = LiterLlmLib.CreateClient("test-key", baseUrl, null, null, null);

            var result = await client.Chat(ChatCompletionRequest.FromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"local-model\"}"));
    Assert.Equal(1, result.Choices.Count);
    Assert.Equal("Hi there!", result.Choices[0].Message.Content!.Trim());
            Assert.Equal("stop", result.Choices[0].FinishReason == null ? null : JsonNamingPolicy.SnakeCaseLower.ConvertName(result.Choices[0].FinishReason.ToString()!));
    Assert.Equal("local-model", result.Model!.Trim());

        }

        [Fact]
        public async Task Test_ExtraHeaders()
        {
            // Client configured with extra custom headers successfully completes a chat request
            var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/extra_headers";
            var client = LiterLlmLib.CreateClient("test-key", baseUrl, null, null, null);

            var result = await client.Chat(ChatCompletionRequest.FromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}"));
    Assert.Equal(1, result.Choices.Count);
            Assert.Equal("stop", result.Choices[0].FinishReason == null ? null : JsonNamingPolicy.SnakeCaseLower.ConvertName(result.Choices[0].FinishReason.ToString()!));

        }

        [Fact]
        public async Task Test_LocalProviderLlamacpp()
        {
            // llamacpp local provider routes requests via llamacpp/ model prefix with no auth
            var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/local_provider_llamacpp";
            var client = LiterLlmLib.CreateClient("test-key", baseUrl, null, null, null);

            var result = await client.Chat(ChatCompletionRequest.FromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"llamacpp/my-model\"}"));
    Assert.Equal(1, result.Choices.Count);
    Assert.Equal("Hi there! I'm running locally.", result.Choices[0].Message.Content!.Trim());
            Assert.Equal("stop", result.Choices[0].FinishReason == null ? null : JsonNamingPolicy.SnakeCaseLower.ConvertName(result.Choices[0].FinishReason.ToString()!));
    Assert.Equal("my-model", result.Model!.Trim());

        }

        [Fact]
        public async Task Test_LocalProviderOllama()
        {
            // Ollama local provider routes requests via ollama/ model prefix with no auth
            var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/local_provider_ollama";
            var client = LiterLlmLib.CreateClient("test-key", baseUrl, null, null, null);

            var result = await client.Chat(ChatCompletionRequest.FromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"ollama/qwen2:0.5b\"}"));
    Assert.Equal(1, result.Choices.Count);
    Assert.Equal("Hello! How can I help you today?", result.Choices[0].Message.Content!.Trim());
            Assert.Equal("stop", result.Choices[0].FinishReason == null ? null : JsonNamingPolicy.SnakeCaseLower.ConvertName(result.Choices[0].FinishReason.ToString()!));
    Assert.Equal("qwen2:0.5b", result.Model!.Trim());

        }

        [Fact]
        public async Task Test_LocalProviderVllm()
        {
            // vLLM local provider routes requests via vllm/ model prefix with no auth
            var baseUrl = (System.Environment.GetEnvironmentVariable("MOCK_SERVER_URL") ?? string.Empty) + "/fixtures/local_provider_vllm";
            var client = LiterLlmLib.CreateClient("test-key", baseUrl, null, null, null);

            var result = await client.Chat(ChatCompletionRequest.FromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"vllm/meta-llama/Llama-3.2-1B\"}"));
    Assert.Equal(1, result.Choices.Count);
    Assert.Equal("Hello! How may I assist you?", result.Choices[0].Message.Content!.Trim());
            Assert.Equal("stop", result.Choices[0].FinishReason == null ? null : JsonNamingPolicy.SnakeCaseLower.ConvertName(result.Choices[0].FinishReason.ToString()!));
    Assert.Equal("meta-llama/Llama-3.2-1B", result.Model!.Trim());

        }


    }
}
