# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:614a9a228c315e2e022431f3529f2dc8acdbb8c9b89123fe631385dfe0d5ad5f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require_relative "liter_llm/version"
require_relative "liter_llm/native"

# Top-level namespace for the LiterLlm Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "liter_llm/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module LiterLlm
  # Re-export all types and functions from native extension
end

# Bring top-level LiterLlm classes into the global namespace so callers
# (and the generated e2e suite) can reference them unqualified. The native
# extension has already been required above, so every type constant is defined
# under LiterLlm by this point.
LiterLlm.constants.each do |const_name|
  value = LiterLlm.const_get(const_name)
  ::Object.const_set(const_name, value) if value.is_a?(Module) && !::Object.const_defined?(const_name)
end
