// Generated by alef. Do not edit by hand.
// alef:hash:ee34d53dd7b53bbfa1e1d683dc961e1355a375403d7bca2db0da948bbbf6d364

// Traits module (empty in Dart as Dart does not have trait systems like Rust).
// This file is kept for API surface consistency across language bindings.
