// DO NOT EDIT - auto-generated by alef
// alef:hash:9a6e94386d8a58656779a53565013dd1754ed706a423955d86280140a736bb05
package dev.kreuzberg.literllm;

/**
 * `status` preserves the exact HTTP status code received (401 or 403).
 */
public class AuthenticationException extends LiterLlmErrorException {
    /** Creates a new AuthenticationException with the given message. */
    public AuthenticationException(final String message) {
        super(message);
    }

    /** Creates a new AuthenticationException with the given message and cause. */
    public AuthenticationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
