// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f8379eae27ed3a6329455bc322e5e326fb64d35482ccad05e94e2fd26dee47b2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Auth configuration block.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AuthConfig.Builder.class)
public record AuthConfig(
    /**
     * Auth scheme classification.
     */
    @JsonProperty("type") AuthType authType,
    /**
     * Name of the environment variable that holds the API key (e.g. {@code "OPENAI_API_KEY"}).
     * Holds the variable name, never the secret value.
     */
    @Nullable @JsonProperty("env_var") String envVar
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("type")
private AuthType authType = null;
        @JsonProperty("env_var")
private String envVar = null;

        /** Sets the authType field. */
        @JsonProperty("type")
        public Builder withAuthType(final AuthType value) {
            this.authType = value;
            return this;
        }

        /** Sets the envVar field. */
        @JsonProperty("env_var")
        public Builder withEnvVar(final @Nullable String value) {
            this.envVar = value;
            return this;
        }

        /** Builds the AuthConfig instance. */
        public AuthConfig build() {
            return new AuthConfig(
                authType,
                envVar
            );
        }
    }
    // CPD-ON
}
