// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8146ae9f5f4d39967cc3f3f31b7931b268b44e539a36ee2dc13aaf9e3e761a66
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * How the API key is sent in the HTTP request.
 */
public enum AuthHeaderFormat {
    /**
     * Bearer token: {@code Authorization: Bearer &lt;key&gt;}
     */
    Bearer("bearer"),
    /**
     * Custom header: e.g., {@code X-Api-Key: &lt;key&gt;}
     */
    ApiKey("apikey"),
    /**
     * No authentication required.
     */
    None("none");

    /** The string value. */
    private final String value;

    AuthHeaderFormat(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static AuthHeaderFormat fromValue(final String value) {
        for (AuthHeaderFormat e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
