// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6890bb94263aa98b74fe3bbbf5681c591bfb2cb1f0d10c03ac015c85f722890d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Auth configuration block.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record AuthConfig(
    /**
     * Auth scheme classification.
     */
    @JsonProperty("type") AuthType authType,
    /**
     * Name of the environment variable that holds the API key (e.g. {@code "OPENAI_API_KEY"}).
     * Holds the variable name, never the secret value.
     */
    @Nullable @JsonProperty("env_var") String envVar
) {
}
