// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:20ffd35e08c4c42e557dc50e91ff27e1ee33256544dc20420f1565da79ee24ea
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Configuration for budget enforcement.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record BudgetConfig(
    /**
     * Maximum total spend across all models, in USD.  {@code None} means unlimited.
     */
    @Nullable @JsonProperty("global_limit") Double globalLimit,
    /**
     * Per-model spending limits in USD.  Models not listed here are only
     * constrained by {@code global_limit}.
     */
    @JsonProperty("model_limits") Map<String, Double> modelLimits,
    /**
     * Whether to reject requests or merely warn when a limit is exceeded.
     */
    Enforcement enforcement
) {
    public static BudgetConfig defaultInstance() {
        throw new UnsupportedOperationException("defaultInstance is not yet bridged via JNI; use the Builder instead.");
    }
}
