// DO NOT EDIT - auto-generated by alef
// alef:hash:de9738d1a2c1e8c5eacecbd4da06878683f3650e2b3bcc2ce0cb163d94f425f0
package dev.kreuzberg.literllm;

public class ContextWindowExceededException extends LiterLlmErrorException {
    /** Creates a new ContextWindowExceededException with the given message. */
    public ContextWindowExceededException(final String message) {
        super(message);
    }

    /** Creates a new ContextWindowExceededException with the given message and cause. */
    public ContextWindowExceededException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
