// DO NOT EDIT - auto-generated by alef
// alef:hash:2f8bf6d8baa22da7777c4dc6d7e1bdefbc5a4cf0734b7c989894279b660d76e1
package dev.kreuzberg.literllm;

public class ContextWindowExceededException extends LiterLlmErrorException {
    /** Creates a new ContextWindowExceededException with the given message. */
    public ContextWindowExceededException(final String message) {
        super(message);
    }

    /** Creates a new ContextWindowExceededException with the given message and cause. */
    public ContextWindowExceededException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
