// DO NOT EDIT - auto-generated by alef
// alef:hash:ba657952768c5f5d5944344aa80ee8eea5ebdd71e9ac890aa89428c3de49085b
package dev.kreuzberg.literllm;

public class ContextWindowExceededException extends LiterLlmErrorException {
    /** Creates a new ContextWindowExceededException with the given message. */
    public ContextWindowExceededException(final String message) {
        super(message);
    }

    /** Creates a new ContextWindowExceededException with the given message and cause. */
    public ContextWindowExceededException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
