// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:65c64fec67a74a881cba99c32574ceecbff3c0842a39379ad6c6d8a34c0699c9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Configuration for registering a custom LLM provider at runtime.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CustomProviderConfig.Builder.class)
public record CustomProviderConfig(
    /**
     * Unique name for this provider (e.g., "my-provider").
     */
    String name,
    /**
     * Base URL for the provider's API (e.g., "https://api.my-provider.com/v1").
     */
    @JsonProperty("base_url") String baseUrl,
    /**
     * Authentication header format.
     */
    @JsonProperty("auth_header") AuthHeaderFormat authHeader,
    /**
     * Model name prefixes that route to this provider (e.g., ["my-"]).
     */
    @JsonProperty("model_prefixes") List<String> modelPrefixes
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        @JsonProperty("name")
        private String name = "";
        @JsonProperty("base_url")
        private String baseUrl = "";
        @JsonProperty("auth_header")
        private AuthHeaderFormat authHeader = null;
        @JsonProperty("model_prefixes")
        private List<String> modelPrefixes = List.of();

        /** Sets the name field. */
        @JsonProperty("name")
        public Builder withName(final String value) {
            this.name = value;
            return this;
        }

        /** Sets the baseUrl field. */
        @JsonProperty("base_url")
        public Builder withBaseUrl(final String value) {
            this.baseUrl = value;
            return this;
        }

        /** Sets the authHeader field. */
        @JsonProperty("auth_header")
        public Builder withAuthHeader(final AuthHeaderFormat value) {
            this.authHeader = value;
            return this;
        }

        /** Sets the modelPrefixes field. */
        @JsonProperty("model_prefixes")
        public Builder withModelPrefixes(final List<String> value) {
            this.modelPrefixes = value;
            return this;
        }

        /** Builds the CustomProviderConfig instance. */
        public CustomProviderConfig build() {
            return new CustomProviderConfig(
                name,
                baseUrl,
                authHeader,
                modelPrefixes
            );
        }
    }
    // CPD-ON
}
