// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6bdb87283bb8993886040f56b152c6173b8077214603cec4f992d1d6f36d4516
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Response from a delete operation.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DeleteResponse.Builder.class)
public record DeleteResponse(
    /**
     * ID of the deleted resource.
     */
    @JsonProperty("id") String id,
    /**
     * Object type.
     */
    @JsonProperty("object") String object,
    /**
     * Confirmation that the resource was deleted.
     */
    @JsonProperty("deleted") boolean deleted
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private String id = "";
private String object = "";
private boolean deleted = false;

        /** Sets the id field. */
        @JsonProperty("id")
        public Builder withId(final String value) {
            this.id = value;
            return this;
        }

        /** Sets the object field. */
        @JsonProperty("object")
        public Builder withObject(final String value) {
            this.object = value;
            return this;
        }

        /** Sets the deleted field. */
        @JsonProperty("deleted")
        public Builder withDeleted(final boolean value) {
            this.deleted = value;
            return this;
        }

        /** Builds the DeleteResponse instance. */
        public DeleteResponse build() {
            return new DeleteResponse(
                id,
                object,
                deleted
            );
        }
    }
    // CPD-ON
}
