// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6a87da5514fa718777caf4bdaedec556e97b2c2d71adb0feebddf1b0250f982d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FileObjectBuilder.class)
public record FileObject(
    String id,
    String object,
    long bytes,
    @JsonProperty("created_at") long createdAt,
    String filename,
    String purpose,
    @Nullable String status
) {
    public static FileObjectBuilder builder() {
        return new FileObjectBuilder();
    }
}
