// DO NOT EDIT - auto-generated by alef
// alef:hash:2f143786fb36dce5760aa0a4f7119856f493160ef8abf8968a00dc65759b2283
package dev.kreuzberg.literllm;

public class HookRejectedException extends LiterLlmErrorException {
    /** Creates a new HookRejectedException with the given message. */
    public HookRejectedException(final String message) {
        super(message);
    }

    /** Creates a new HookRejectedException with the given message and cause. */
    public HookRejectedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
