// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8fe3c6ba10e9333556ed2c06816a84390edd9dcbb99d3498f707bc00f7a64f10
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum ImageDetail {
    Low("low"),
    High("high"),
    Auto("auto");

    /** The string value. */
    private final String value;

    ImageDetail(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ImageDetail fromValue(final String value) {
        for (ImageDetail e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
