// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2223c51cdcf09772b0d2fd689d22d4b21b08ccdb334a1b3e9386e52a9a932097
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A single generated image, returned as either a URL or base64 data.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class ImageBuilder {

    private Optional<String> url = Optional.empty();
    @JsonProperty("b64_json")
    private Optional<String> b64Json = Optional.empty();
    @JsonProperty("revised_prompt")
    private Optional<String> revisedPrompt = Optional.empty();

    /** Sets the url field. */
    public ImageBuilder withUrl(final Optional<String> value) {
        this.url = value;
        return this;
    }

    /** Sets the b64Json field. */
    public ImageBuilder withB64Json(final Optional<String> value) {
        this.b64Json = value;
        return this;
    }

    /** Sets the revisedPrompt field. */
    public ImageBuilder withRevisedPrompt(final Optional<String> value) {
        this.revisedPrompt = value;
        return this;
    }

    /** Builds the Image instance. */
    public Image build() {
        return new Image(
            url.orElse(null),
            b64Json.orElse(null),
            revisedPrompt.orElse(null)
        );
    }
}
