// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:77063898f58ec52d842e4a09b0a1369b7345aeafae7b09befc8525ded390ea34
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.literllm;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * An intent prototype: {@code (intent_name, prototype_embedding, target_model_id)}.
 */
@SuppressWarnings("PMD")
public record IntentPrototype(
    String name,
    @JsonInclude(JsonInclude.Include.NON_NULL) List<Double> embedding,
    String model
) {
}
