// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:797e09398ae0b95dd0e3de94d7374eedafcd20d08532c7cf378cbcd09e3083a7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.literllm;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * An intent prototype: {@code (intent_name, prototype_embedding, target_model_id)}.
 */
@SuppressWarnings("PMD")
public record IntentPrototype(
    String name,
    @JsonInclude(JsonInclude.Include.NON_NULL) List<Double> embedding,
    String model
) {
}
