// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:718a9bb2066b4d98f177745b5c3db63c834a58163b5677360c01f624add6c233
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.literllm;

/** Exception thrown by LiterLlmRs. */
public class LiterLlmRsException extends Exception {
  private static final long serialVersionUID = 1L;
  /** The error code. */
  private final int code;

  /** Creates a new LiterLlmRsException. */
  public LiterLlmRsException(final int code, final String message) {
    super(message);
    this.code = code;
  }

  /** Creates a new LiterLlmRsException with a cause. */
  public LiterLlmRsException(final String message, final Throwable cause) {
    super(message, cause);
    this.code = -1;
  }

  /** Returns the error code. */
  public int getCode() {
    return code;
  }
}
