// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6541a112cdbd1e3b52d9b5a4e6ce002b725e1c1b695391d6b352ef649c276103
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A single moderation classification result.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ModerationResult(
    boolean flagged,
    ModerationCategories categories,
    @JsonProperty("category_scores") ModerationCategoryScores categoryScores
) {

    /**
     * Parse a {@code ModerationResult} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws RuntimeException if the JSON cannot be deserialised.
     */
    public static ModerationResult fromJson(String json) {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, ModerationResult.class);
        } catch (Exception e) {
            throw new RuntimeException("Failed to parse ModerationResult from JSON", e);
        }
    }
}
