// DO NOT EDIT - auto-generated by alef
// alef:hash:1c2da475a93d435187a14de8098d1aaee2346f1e3199d84696805e5f6265736b
package dev.kreuzberg.literllm;

public class NotFoundException extends LiterLlmErrorException {
    /** Creates a new NotFoundException with the given message. */
    public NotFoundException(final String message) {
        super(message);
    }

    /** Creates a new NotFoundException with the given message and cause. */
    public NotFoundException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
