// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:792513825fb361b2553c7df96b87007f5d0af7ff95f74efd2b9dbb0eea644bf1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * An OCR request.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OcrRequest.Builder.class)
public record OcrRequest(
    String model,
    OcrDocument document,
    @Nullable List<Integer> pages,
    @Nullable @JsonProperty("include_image_base64") Boolean includeImageBase64
) {
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Parse a {@code OcrRequest} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws LiterLlmRsException if the JSON cannot be deserialised.
     */
    public static OcrRequest fromJson(String json) throws LiterLlmRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, OcrRequest.class);
        } catch (Exception e) {
            throw new LiterLlmRsException("Failed to parse OcrRequest from JSON: " + e.getMessage(), e);
        }
    }

    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        @JsonProperty("model")
        private String model = "";
        @JsonProperty("document")
        private OcrDocument document = null;
        @JsonProperty("pages")
        private Optional<List<Integer>> pages = Optional.empty();
        @JsonProperty("include_image_base64")
        private Optional<Boolean> includeImageBase64 = Optional.empty();

        /** Sets the model field. */
        @JsonProperty("model")
        public Builder withModel(final String value) {
            this.model = value;
            return this;
        }

        /** Sets the document field. */
        @JsonProperty("document")
        public Builder withDocument(final OcrDocument value) {
            this.document = value;
            return this;
        }

        /** Sets the pages field. */
        @JsonProperty("pages")
        public Builder withPages(final Optional<List<Integer>> value) {
            this.pages = value;
            return this;
        }

        /** Sets the includeImageBase64 field. */
        @JsonProperty("include_image_base64")
        public Builder withIncludeImageBase64(final Optional<Boolean> value) {
            this.includeImageBase64 = value;
            return this;
        }

        /** Builds the OcrRequest instance. */
        public OcrRequest build() {
            return new OcrRequest(
                model,
                document,
                pages.orElse(null),
                includeImageBase64.orElse(null)
            );
        }
    }
}
