// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0411559aec0b632f20c6afc60410dc36547c2500cb4f2b504a446f5ef91fb255
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * An OCR request.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OcrRequestBuilder.class)
public record OcrRequest(
    String model,
    OcrDocument document,
    @Nullable List<Integer> pages,
    @Nullable @JsonProperty("include_image_base64") Boolean includeImageBase64
) {
    public static OcrRequestBuilder builder() {
        return new OcrRequestBuilder();
    }
}
