// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Action taken when a RegexGuardrail finds a match.
 */
@SuppressWarnings("PMD")
public enum OnMatch {
  /**
   * Block the request/response with the given error code and reason prefix.
   */
  Block("block"),
  /**
   * Replace the matched portion with the given replacement string.
   */
  Redact("redact");

  /** The string value. */
  private final String value;

  OnMatch(final String value) {
    this.value = value;
  }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static OnMatch fromValue(final String value) {
    for (OnMatch e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown OnMatch value: " + value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
