// DO NOT EDIT - auto-generated by alef
// alef:hash:718a9bb2066b4d98f177745b5c3db63c834a58163b5677360c01f624add6c233
package dev.kreuzberg.literllm;

/** Exception for RateLimitedException. */
public class RateLimitedException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new RateLimitedException with the given message. */
  public RateLimitedException(final String message) {
    super(message);
  }

  /** Creates a new RateLimitedException with the given message and cause. */
  public RateLimitedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
