// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f65c6560b6c567db64ea4a47c46737da5b3a7326438fd8188f494f1dac201829
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Configuration for per-model rate limits.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record RateLimitConfig(@Nullable Integer rpm, @Nullable Long tpm, Long window) {
    public RateLimitConfig{
        if (window == null) window = 60000L;
    }
    public static RateLimitConfig defaultInstance() {
        throw new UnsupportedOperationException("defaultInstance is not yet bridged via JNI; use the Builder instead.");
    }
}
