// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5df471d5ded8bbaa51bd271adf7db4939dccbe1ec22ea61e8cbfe5882777ad22
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * The text content of a reranked document, returned when {@code return_documents} is true.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record RerankResultDocument(String text) {

    /**
     * Parse a {@code RerankResultDocument} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws RuntimeException if the JSON cannot be deserialised.
     */
    public static RerankResultDocument fromJson(String json) {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, RerankResultDocument.class);
        } catch (Exception e) {
            throw new RuntimeException("Failed to parse RerankResultDocument from JSON", e);
        }
    }
}
