// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8146ae9f5f4d39967cc3f3f31b7931b268b44e539a36ee2dc13aaf9e3e761a66
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * Response format constraint.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = false)
@JsonSubTypes({
    @JsonSubTypes.Type(value = ResponseFormat.Text.class, name = "text"),
    @JsonSubTypes.Type(value = ResponseFormat.JsonObject.class, name = "json_object"),
    @JsonSubTypes.Type(value = ResponseFormat.JsonSchema.class, name = "json_schema")
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
public sealed interface ResponseFormat {

    /**
     * Plain text output (default).
     */
    record Text() implements ResponseFormat {
    }

    /**
     * Output must be valid JSON object (no schema validation).
     */
    record JsonObject() implements ResponseFormat {
    }

    /**
     * Output must conform to the specified JSON schema.
     */
    record JsonSchema(@JsonProperty("json_schema") JsonSchemaFormat jsonSchema) implements ResponseFormat { }
}
