// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1729419cf2b391c61ab4e652fe43d76ab2f8eafed4bc4fabc38017bd66964e5e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ResponseOutputItemBuilder.class)
public record ResponseOutputItem(@JsonProperty("type") String itemType, Object content) {
    public static ResponseOutputItemBuilder builder() {
        return new ResponseOutputItemBuilder();
    }

    /**
     * Parse a {@code ResponseOutputItem} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws RuntimeException if the JSON cannot be deserialised.
     */
    public static ResponseOutputItem fromJson(String json) {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, ResponseOutputItem.class);
        } catch (Exception e) {
            throw new RuntimeException("Failed to parse ResponseOutputItem from JSON", e);
        }
    }
}
