// DO NOT EDIT - auto-generated by alef
// alef:hash:9f6b5b71659847233e2928ecd95346957e6da47b2c6f0a92fc774b6103873c7e
package dev.kreuzberg.literllm;

/**
 * `status` preserves the exact HTTP status code received (502, 503, or 504).
 */
public class ServiceUnavailableException extends LiterLlmErrorException {
    /** Creates a new ServiceUnavailableException with the given message. */
    public ServiceUnavailableException(final String message) {
        super(message);
    }

    /** Creates a new ServiceUnavailableException with the given message and cause. */
    public ServiceUnavailableException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
