// DO NOT EDIT - auto-generated by alef
// alef:hash:ee69fea3fd6a9e3f1cceaf16d9317d8287d234eeae3745ffabfd532bdbe6a37a
package dev.kreuzberg.literllm;

/**
 * `status` preserves the exact HTTP status code received (500, or other 5xx not covered
 * by `ServiceUnavailable`).
 */
public class ServerErrorException extends LiterLlmErrorException {
    /** Creates a new ServerErrorException with the given message. */
    public ServerErrorException(final String message) {
        super(message);
    }

    /** Creates a new ServerErrorException with the given message and cause. */
    public ServerErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
