// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:82d1ab387126509ed4cdd35a5479b0150622bc4a5b3924e74f5ac1c0d823ee55
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

@JsonPOJOBuilder(withPrefix = "with")
public class SpecificFunctionBuilder {

    private String name = "";

    /** Sets the name field. */
    public SpecificFunctionBuilder withName(final String value) {
        this.name = value;
        return this;
    }

    /** Builds the SpecificFunction instance. */
    public SpecificFunction build() {
        return new SpecificFunction(
            name
        );
    }
}
