// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3bff2ea9e29f6400c87e3cae5b5cd7f820955a3a8ea65b6d78eb81b10d6962a0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.literllm;

import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

@JsonPOJOBuilder(withPrefix = "with")
public class SystemMessageBuilder {

    private String content = "";
    private Optional<String> name = Optional.empty();

    /** Sets the content field. */
    public SystemMessageBuilder withContent(final String value) {
        this.content = value;
        return this;
    }

    /** Sets the name field. */
    public SystemMessageBuilder withName(final Optional<String> value) {
        this.name = value;
        return this;
    }

    /** Builds the SystemMessage instance. */
    public SystemMessage build() {
        return new SystemMessage(
            content,
            name.orElse(null)
        );
    }
}
