// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c436bc5de8a8a4acf6030e7ce2a58333abcb6fae63d29673091f3731bac9598b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import gleeunit
import gleeunit/should
import liter_llm
import e2e_gleam

import gleam/list
import gleam/option

// Embedding request with multiple input strings returns one embedding object per input
pub fn batch_embed_test() {
  let assert Ok(client) = liter_llm.create_client("test-key", "")
    let _ = client
  let result = liter_llm.embed(client, ["Hello", "World"])
  result |> should.be_ok()
  let assert Ok(r) = result
  r.data |> list.length |> should.equal(2)
  // skipped: array element field 'data[0].embedding' not yet supported in Gleam e2e
}

// Embedding request with multiple inputs returns multiple embedding objects
pub fn edge_embed_batch_input_test() {
  let assert Ok(client) = liter_llm.create_client("test-key", "")
    let _ = client
  let result = liter_llm.embed(client, ["Hello world", "Goodbye world"])
  result |> should.be_ok()
  let assert Ok(r) = result
  r.data |> list.length |> should.equal(2)
  // skipped: array element field 'data[0].index' not yet supported in Gleam e2e
  r.data[1].index |> should.equal(1)
}

// Embedding request with empty string input returns empty data array
pub fn edge_embed_empty_input_test() {
  let assert Ok(client) = liter_llm.create_client("test-key", "")
    let _ = client
  let result = liter_llm.embed(client, "")
  result |> should.be_ok()
  let assert Ok(r) = result
  r.data |> list.length |> should.equal(0)
}

// Embedding request with explicit encoding_format of float returns float array embeddings
pub fn embed_encoding_format_test() {
  let assert Ok(client) = liter_llm.create_client("test-key", "")
    let _ = client
  let result = liter_llm.embed(client, "Test input")
  result |> should.be_ok()
  let assert Ok(r) = result
  r.data |> list.length |> should.equal(1)
  // skipped: array element field 'data[0].embedding' not yet supported in Gleam e2e
}

// 401 Unauthorized error on embedding request when API key is invalid
pub fn embed_error_401_test() {
  let assert Ok(client) = liter_llm.create_client("test-key", "")
    let _ = client
  liter_llm.embed(client, "Hello world") |> should.be_error()
}

// Embedding request with explicit dimensions parameter returns embeddings of the requested size
pub fn embed_with_dimensions_test() {
  let assert Ok(client) = liter_llm.create_client("test-key", "")
    let _ = client
  let result = liter_llm.embed(client, "Hello world")
  result |> should.be_ok()
  let assert Ok(r) = result
  r.data |> list.length |> should.equal(1)
  // skipped: array element field 'data[0].embedding' not yet supported in Gleam e2e
}

// Embedding request via Ollama local provider with all-minilm model
pub fn local_embed_ollama_test() {
  let assert Ok(client) = liter_llm.create_client("test-key", "")
    let _ = client
  let result = liter_llm.embed(client, "The quick brown fox jumps over the lazy dog")
  result |> should.be_ok()
  let assert Ok(r) = result
  r.data |> list.length |> should.equal(1)
  // skipped: array element field 'data[0].embedding' not yet supported in Gleam e2e
}
