// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0bf6df993a6aad4209b28518245f314f4139fe094c9d1326e6e405798a3e929e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import gleeunit
import gleeunit/should
import liter_llm
import e2e_gleam

import gleam/list
import gleam/option
import gleam/string

// List files when no files have been uploaded
pub fn edge_file_empty_list_test() {
  let assert Ok(client) = liter_llm.create_client("test-key", "")
    let _ = client
  let result = liter_llm.list_files(client)
  result |> should.be_ok()
  let assert Ok(r) = result
  r.data |> list.length |> should.equal(0)
}

// Upload a large file successfully
pub fn edge_file_large_upload_test() {
  let assert Ok(client) = liter_llm.create_client("test-key", "")
    let _ = client
  let result = liter_llm.create_file(client, "{}")
  result |> should.be_ok()
  let assert Ok(r) = result
  r.id |> string.is_empty |> should.equal(False)
}

// 401 Unauthorized when listing files with invalid API key
pub fn error_file_auth_401_test() {
  let assert Ok(client) = liter_llm.create_client("test-key", "")
    let _ = client
  liter_llm.list_files(client) |> should.be_error()
}

// 400 Bad Request when uploading a file with invalid purpose
pub fn error_file_bad_purpose_test() {
  let assert Ok(client) = liter_llm.create_client("test-key", "")
    let _ = client
  liter_llm.create_file(client, "{}") |> should.be_error()
}

// 404 Not Found when retrieving a nonexistent file
pub fn error_file_not_found_test() {
  let assert Ok(client) = liter_llm.create_client("test-key", "")
    let _ = client
  liter_llm.retrieve_file(client, "file-nonexistent") |> should.be_error()
}

// Upload a file for use with the API
pub fn smoke_create_file_test() {
  let assert Ok(client) = liter_llm.create_client("test-key", "")
    let _ = client
  let result = liter_llm.create_file(client, "{}")
  result |> should.be_ok()
  let assert Ok(r) = result
  r.id |> string.is_empty |> should.equal(False)
}

// Delete an uploaded file
pub fn smoke_delete_file_test() {
  let assert Ok(client) = liter_llm.create_client("test-key", "")
    let _ = client
  let result = liter_llm.delete_file(client, "file-abc123")
  result |> should.be_ok()
  let assert Ok(r) = result
  r.id |> string.is_empty |> should.equal(False)
  r.deleted |> should.equal(True)
}

// Retrieve the content of an uploaded file
pub fn smoke_file_content_test() {
  let assert Ok(client) = liter_llm.create_client("test-key", "")
    let _ = client
  let result = liter_llm.file_content(client, "file-abc123")
  result |> should.be_ok()
  let assert Ok(r) = result
  r.content |> string.is_empty |> should.equal(False)
}

// List all uploaded files
pub fn smoke_list_files_test() {
  let assert Ok(client) = liter_llm.create_client("test-key", "")
    let _ = client
  let result = liter_llm.list_files(client)
  result |> should.be_ok()
  let assert Ok(r) = result
  r.data |> list.length |> should.equal(2)
}

// Retrieve metadata for an uploaded file
pub fn smoke_retrieve_file_test() {
  let assert Ok(client) = liter_llm.create_client("test-key", "")
    let _ = client
  let result = liter_llm.retrieve_file(client, "file-abc123")
  result |> should.be_ok()
  let assert Ok(r) = result
  r.id |> string.is_empty |> should.equal(False)
}
