# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:114fb84ee59520033b02dd77a740188f53446cd1a2030cd3893a97b223278433
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: custom_provider
defmodule E2e.CustomProviderTest do
  use ExUnit.Case, async: false

  describe "provider_auth" do
    test "provider_auth" do
      {:ok, client} = LiterLlm.create_client("test-key", (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/provider_auth")
      {:ok, result} = LiterLlm.defaultclient_chat_async(client, "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"my-auth-model-v1\"}")
    end
  end

  describe "register_provider" do
    test "register_provider" do
      {:ok, client} = LiterLlm.create_client("test-key", (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/register_provider")
      {:ok, result} = LiterLlm.defaultclient_chat_async(client, "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"my-model-v1\"}")
    end
  end
end
