# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0ad579c4e6402a59f477d57e2df40488d9809a1a212e52fe47279587ff8c442e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
# E2e tests for category: parity
defmodule E2e.ParityTest do
  use ExUnit.Case, async: false

  describe "api_surface_parity" do
    test "api_surface_parity" do
      {:ok, client} = LiterLlm.create_client("test-key", base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/api_surface_parity")
      {:ok, result} = LiterLlm.defaultclient_chat_async(client, "{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4o\"}")
    end
  end
end
