# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f2d02d39ed23b63568387f22c991c70fd7b0d5c8f2f92cc028dcbaff825ca583
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: types
defmodule E2e.TypesTest do
  use ExUnit.Case, async: false

  describe "all_message_types" do
    test "all_message_types" do
      {:ok, client} = LiterLlm.create_client("test-key", base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/all_message_types")
      {:ok, result} = LiterLlm.defaultclient_chat_async(client, "{\"messages\":[{\"content\":\"You are a helpful assistant.\",\"role\":\"system\"},{\"content\":\"What is the weather in Paris?\",\"role\":\"user\"},{\"content\":null,\"role\":\"assistant\",\"tool_calls\":[{\"function\":{\"arguments\":\"{\\\"location\\\": \\\"Paris, France\\\"}\",\"name\":\"get_weather\"},\"id\":\"call_xyz789\",\"type\":\"function\"}]},{\"content\":\"{\\\"temperature\\\": 18, \\\"unit\\\": \\\"celsius\\\", \\\"description\\\": \\\"Partly cloudy\\\"}\",\"role\":\"tool\",\"tool_call_id\":\"call_xyz789\"}],\"model\":\"gpt-4\"}")
      assert length(result.choices) == 1
      assert String.trim(to_string(Enum.at(result.choices, 0).finish_reason)) == "stop"
    end
  end

  describe "multimodal_content" do
    test "multimodal_content" do
      {:ok, client} = LiterLlm.create_client("test-key", base_url: (System.get_env("MOCK_SERVER_URL") || "") <> "/fixtures/multimodal_content")
      {:ok, result} = LiterLlm.defaultclient_chat_async(client, "{\"max_tokens\":100,\"messages\":[{\"content\":[{\"text\":\"What is in this image?\",\"type\":\"text\"},{\"image_url\":{\"detail\":\"low\",\"url\":\"https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/PNG_transparency_demonstration_1.png/280px-PNG_transparency_demonstration_1.png\"},\"type\":\"image_url\"}],\"role\":\"user\"}],\"model\":\"gpt-4o\"}")
      assert length(result.choices) == 1
      assert String.trim(to_string(Enum.at(result.choices, 0).finish_reason)) == "stop"
    end
  end
end
