// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:35a11d55adaef4a810094d7e75475c4a8cdc882ae309078328acd06df51a2e26
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

import { describe, expect, it } from "vitest";
import {
  createClient,
  WasmChatCompletionRequest,
  WasmCreateImageRequest,
  WasmResponseFormat,
  WasmChatCompletionTool,
  WasmToolChoice,
  WasmStopSequence,
  WasmStreamOptions,
  WasmReasoningEffort,
  WasmMessage,
} from "liter_llm";
function _alefE2eText(value: unknown): string {
  return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
  if (item == null || typeof item !== "object") {
    return [_alefE2eText(item)];
  }
  const record = item as Record<string, unknown>;
  const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
  return [
    _alefE2eText(item),
    _alefE2eText(record.kind),
    _alefE2eText(record.name),
    _alefE2eText(record.source),
    _alefE2eText(record.alias),
    _alefE2eText(record.text),
    _alefE2eText(record.signature),
    itemsText,
  ];
}

describe("image-generate", () => {
  it("edge_image_b64_response: Image generation returning base64-encoded data instead of URL", async () => {
    const client = createClient(
      "test-key",
      `${process.env.MOCK_SERVER_URL}/fixtures/edge_image_b64_response`,
    );
    const result = await client.imageGenerate(
      (() => {
        const _u = new WasmCreateImageRequest();
        _u.model = "dall-e-3";
        _u.n = 1;
        _u.prompt = "A blue circle";
        _u.responseFormat = "b64_json";
        _u.size = "1024x1024";
        return _u;
      })(),
    );
    expect(result.data.length).toBe(1);
    expect((result.data[0].b64Json ?? "").length).toBeGreaterThan(0);
  });
  it("edge_image_empty_prompt: Image generation with an empty prompt returns 400", async () => {
    const client = createClient(
      "test-key",
      `${process.env.MOCK_SERVER_URL}/fixtures/edge_image_empty_prompt`,
    );
    await expect(async () => {
      await client.imageGenerate(
        (() => {
          const _u = new WasmCreateImageRequest();
          _u.model = "dall-e-3";
          _u.n = 1;
          _u.prompt = "";
          _u.size = "1024x1024";
          return _u;
        })(),
      );
    }).rejects.toThrow();
  });
  it("edge_image_multiple_n: Image generation requesting multiple images with n=3", async () => {
    const client = createClient(
      "test-key",
      `${process.env.MOCK_SERVER_URL}/fixtures/edge_image_multiple_n`,
    );
    const result = await client.imageGenerate(
      (() => {
        const _u = new WasmCreateImageRequest();
        _u.model = "dall-e-3";
        _u.n = 3;
        _u.prompt = "A cat";
        return _u;
      })(),
    );
    expect(result.data.length).toBe(3);
    expect((result.data[0].url ?? "").length).toBeGreaterThan(0);
    expect((result.data[1].url ?? "").length).toBeGreaterThan(0);
    expect((result.data[2].url ?? "").length).toBeGreaterThan(0);
  });
  it("error_image_auth_401: 401 Unauthorized when generating images with invalid API key", async () => {
    const client = createClient(
      "test-key",
      `${process.env.MOCK_SERVER_URL}/fixtures/error_image_auth_401`,
    );
    await expect(async () => {
      await client.imageGenerate(
        (() => {
          const _u = new WasmCreateImageRequest();
          _u.model = "dall-e-3";
          _u.n = 1;
          _u.prompt = "A cat";
          _u.size = "1024x1024";
          return _u;
        })(),
      );
    }).rejects.toThrow();
  });
  it("error_image_bad_request: 400 Bad Request when image generation parameters are invalid", async () => {
    const client = createClient(
      "test-key",
      `${process.env.MOCK_SERVER_URL}/fixtures/error_image_bad_request`,
    );
    await expect(async () => {
      await client.imageGenerate(
        (() => {
          const _u = new WasmCreateImageRequest();
          _u.model = "dall-e-3";
          _u.n = 1;
          _u.prompt = "A cat";
          _u.size = "9999x9999";
          return _u;
        })(),
      );
    }).rejects.toThrow();
  });
  it("error_image_rate_limit: 429 Rate limit exceeded for image generation", async () => {
    const client = createClient(
      "test-key",
      `${process.env.MOCK_SERVER_URL}/fixtures/error_image_rate_limit`,
    );
    await expect(async () => {
      await client.imageGenerate(
        (() => {
          const _u = new WasmCreateImageRequest();
          _u.model = "dall-e-3";
          _u.n = 1;
          _u.prompt = "A cat";
          _u.size = "1024x1024";
          return _u;
        })(),
      );
    }).rejects.toThrow();
  });
  it("smoke_image_basic: Basic image generation with a text prompt", async () => {
    const client = createClient(
      "test-key",
      `${process.env.MOCK_SERVER_URL}/fixtures/smoke_image_basic`,
    );
    const result = await client.imageGenerate(
      (() => {
        const _u = new WasmCreateImageRequest();
        _u.model = "dall-e-3";
        _u.n = 1;
        _u.prompt = "A white cat sitting on a windowsill";
        _u.size = "1024x1024";
        return _u;
      })(),
    );
    expect(result.data.length).toBe(1);
    expect((result.data[0].url ?? "").length).toBeGreaterThan(0);
  });
  it("smoke_image_multiple: Image generation requesting multiple images", async () => {
    const client = createClient(
      "test-key",
      `${process.env.MOCK_SERVER_URL}/fixtures/smoke_image_multiple`,
    );
    const result = await client.imageGenerate(
      (() => {
        const _u = new WasmCreateImageRequest();
        _u.model = "dall-e-2";
        _u.n = 3;
        _u.prompt = "A red bicycle";
        _u.size = "256x256";
        return _u;
      })(),
    );
    expect(result.data.length).toBe(3);
    expect((result.data[0].url ?? "").length).toBeGreaterThan(0);
  });
  it("smoke_image_with_size: Image generation with explicit size parameter", async () => {
    const client = createClient(
      "test-key",
      `${process.env.MOCK_SERVER_URL}/fixtures/smoke_image_with_size`,
    );
    const result = await client.imageGenerate(
      (() => {
        const _u = new WasmCreateImageRequest();
        _u.model = "dall-e-3";
        _u.n = 1;
        _u.prompt = "A sunset over mountains";
        _u.size = "1792x1024";
        return _u;
      })(),
    );
    expect(result.data.length).toBe(1);
    expect((result.data[0].url ?? "").length).toBeGreaterThan(0);
  });
});
