/*
 * This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:27f9938495cbdddb13fdc28a32fa926f7f612f3dc2039b856e0798339b2596af
 * To regenerate: alef generate
 * To verify freshness: alef verify --exit-code
 * Issues & docs: https://github.com/kreuzberg-dev/alef
 */
/* E2e tests for category: rerank */

#include <assert.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "liter_llm.h"
#include "test_runner.h"

void test_edge_rerank_empty_query(void) {
    /* Reranking with an empty query string */
    LITERLLMRerankRequest* rerank_request_handle = literllm_rerank_request_from_json("{\"documents\":[\"Some document\",\"Another document\"],\"model\":\"rerank-v3.5\",\"query\":\"\"}");
    assert(rerank_request_handle != NULL && "failed to build request");
    const char* mock_base = getenv("MOCK_SERVER_URL");
    assert(mock_base != NULL && "MOCK_SERVER_URL must be set");
    char base_url[1024];
    snprintf(base_url, sizeof(base_url), "%s/fixtures/edge_rerank_empty_query", mock_base);
    LITERLLMDefaultClient* client = literllm_create_client("test-key", base_url, 0, 0, NULL);
    assert(client != NULL && "failed to create client");
    LITERLLMRerankResponse* result = literllm_default_client_rerank(client, rerank_request_handle);
    assert(result != NULL && "expected call to succeed");
    char* results = literllm_rerank_response_results(result);
    {
        /* count_equals: count elements in array */
        assert(results != NULL && "expected non-null collection JSON");
        int elem_count = alef_json_array_count(results);
        assert(elem_count == 2 && "expected 2 elements");
    }
    literllm_free_string(results);
    literllm_rerank_response_free(result);
    literllm_rerank_request_free(rerank_request_handle);
    literllm_default_client_free(client);
}

void test_edge_rerank_single_doc(void) {
    /* Reranking with only a single document */
    LITERLLMRerankRequest* rerank_request_handle = literllm_rerank_request_from_json("{\"documents\":[\"Artificial intelligence is the simulation of human intelligence.\"],\"model\":\"rerank-v3.5\",\"query\":\"What is AI?\"}");
    assert(rerank_request_handle != NULL && "failed to build request");
    const char* mock_base = getenv("MOCK_SERVER_URL");
    assert(mock_base != NULL && "MOCK_SERVER_URL must be set");
    char base_url[1024];
    snprintf(base_url, sizeof(base_url), "%s/fixtures/edge_rerank_single_doc", mock_base);
    LITERLLMDefaultClient* client = literllm_create_client("test-key", base_url, 0, 0, NULL);
    assert(client != NULL && "failed to create client");
    LITERLLMRerankResponse* result = literllm_default_client_rerank(client, rerank_request_handle);
    assert(result != NULL && "expected call to succeed");
    char* results = literllm_rerank_response_results(result);
    char* results_json = literllm_rerank_response_results(result);
    assert(results_json != NULL);
    char* results_0_relevance_score = alef_json_get_string(results_json, "0");
    {
        /* count_equals: count elements in array */
        assert(results != NULL && "expected non-null collection JSON");
        int elem_count = alef_json_array_count(results);
        assert(elem_count == 1 && "expected 1 elements");
    }
    assert(results_0_relevance_score != NULL && atof(results_0_relevance_score) > 0.9 && "expected greater than");
    literllm_free_string(results);
    free(results_0_relevance_score);
    literllm_free_string(results_json);
    literllm_rerank_response_free(result);
    literllm_rerank_request_free(rerank_request_handle);
    literllm_default_client_free(client);
}

void test_error_rerank_auth_401(void) {
    /* 401 Unauthorized for reranking with invalid API key */
    LITERLLMRerankRequest* rerank_request_handle = literllm_rerank_request_from_json("{\"documents\":[\"doc1\"],\"model\":\"rerank-v3.5\",\"query\":\"test\"}");
    assert(rerank_request_handle != NULL && "failed to build request");
    const char* mock_base = getenv("MOCK_SERVER_URL");
    assert(mock_base != NULL && "MOCK_SERVER_URL must be set");
    char base_url[1024];
    snprintf(base_url, sizeof(base_url), "%s/fixtures/error_rerank_auth_401", mock_base);
    LITERLLMDefaultClient* client = literllm_create_client("test-key", base_url, 0, 0, NULL);
    assert(client != NULL && "failed to create client");
    LITERLLMRerankResponse* result = literllm_default_client_rerank(client, rerank_request_handle);
    literllm_rerank_request_free(rerank_request_handle);
    literllm_default_client_free(client);
    assert(result == NULL && "expected call to fail");
}

void test_error_rerank_bad_request(void) {
    /* 400 Bad Request for reranking with invalid model */
    LITERLLMRerankRequest* rerank_request_handle = literllm_rerank_request_from_json("{\"documents\":[\"doc1\"],\"model\":\"nonexistent-rerank\",\"query\":\"test\"}");
    assert(rerank_request_handle != NULL && "failed to build request");
    const char* mock_base = getenv("MOCK_SERVER_URL");
    assert(mock_base != NULL && "MOCK_SERVER_URL must be set");
    char base_url[1024];
    snprintf(base_url, sizeof(base_url), "%s/fixtures/error_rerank_bad_request", mock_base);
    LITERLLMDefaultClient* client = literllm_create_client("test-key", base_url, 0, 0, NULL);
    assert(client != NULL && "failed to create client");
    LITERLLMRerankResponse* result = literllm_default_client_rerank(client, rerank_request_handle);
    literllm_rerank_request_free(rerank_request_handle);
    literllm_default_client_free(client);
    assert(result == NULL && "expected call to fail");
}

void test_smoke_rerank_basic(void) {
    /* Basic reranking of documents against a query */
    LITERLLMRerankRequest* rerank_request_handle = literllm_rerank_request_from_json("{\"documents\":[\"Machine learning is a subset of AI.\",\"The weather is sunny today.\",\"Deep learning uses neural networks.\"],\"model\":\"rerank-v3.5\",\"query\":\"What is machine learning?\"}");
    assert(rerank_request_handle != NULL && "failed to build request");
    const char* mock_base = getenv("MOCK_SERVER_URL");
    assert(mock_base != NULL && "MOCK_SERVER_URL must be set");
    char base_url[1024];
    snprintf(base_url, sizeof(base_url), "%s/fixtures/smoke_rerank_basic", mock_base);
    LITERLLMDefaultClient* client = literllm_create_client("test-key", base_url, 0, 0, NULL);
    assert(client != NULL && "failed to create client");
    LITERLLMRerankResponse* result = literllm_default_client_rerank(client, rerank_request_handle);
    assert(result != NULL && "expected call to succeed");
    char* results = literllm_rerank_response_results(result);
    char* results_json = literllm_rerank_response_results(result);
    assert(results_json != NULL);
    char* results_0_relevance_score = alef_json_get_string(results_json, "0");
    {
        /* count_equals: count elements in array */
        assert(results != NULL && "expected non-null collection JSON");
        int elem_count = alef_json_array_count(results);
        assert(elem_count == 3 && "expected 3 elements");
    }
    assert(results_0_relevance_score != NULL && atof(results_0_relevance_score) > 0.9 && "expected greater than");
    literllm_free_string(results);
    free(results_0_relevance_score);
    literllm_free_string(results_json);
    literllm_rerank_response_free(result);
    literllm_rerank_request_free(rerank_request_handle);
    literllm_default_client_free(client);
}

void test_smoke_rerank_return_docs(void) {
    /* Reranking with return_documents flag to include document text */
    LITERLLMRerankRequest* rerank_request_handle = literllm_rerank_request_from_json("{\"documents\":[\"Rust is a systems programming language.\",\"Iron rusts when exposed to water.\"],\"model\":\"rerank-v3.5\",\"query\":\"What is Rust?\",\"return_documents\":true}");
    assert(rerank_request_handle != NULL && "failed to build request");
    const char* mock_base = getenv("MOCK_SERVER_URL");
    assert(mock_base != NULL && "MOCK_SERVER_URL must be set");
    char base_url[1024];
    snprintf(base_url, sizeof(base_url), "%s/fixtures/smoke_rerank_return_docs", mock_base);
    LITERLLMDefaultClient* client = literllm_create_client("test-key", base_url, 0, 0, NULL);
    assert(client != NULL && "failed to create client");
    LITERLLMRerankResponse* result = literllm_default_client_rerank(client, rerank_request_handle);
    assert(result != NULL && "expected call to succeed");
    char* results = literllm_rerank_response_results(result);
    char* results_json = literllm_rerank_response_results(result);
    assert(results_json != NULL);
    char* results_0_document = alef_json_get_string(results_json, "0");
    char* results_0_relevance_score = alef_json_get_string(results_json, "0");
    {
        /* count_equals: count elements in array */
        assert(results != NULL && "expected non-null collection JSON");
        int elem_count = alef_json_array_count(results);
        assert(elem_count == 2 && "expected 2 elements");
    }
    assert(results_0_document != NULL && strlen(results_0_document) > 0 && "expected non-empty value");
    assert(results_0_relevance_score != NULL && atof(results_0_relevance_score) > 0.9 && "expected greater than");
    literllm_free_string(results);
    free(results_0_document);
    free(results_0_relevance_score);
    literllm_free_string(results_json);
    literllm_rerank_response_free(result);
    literllm_rerank_request_free(rerank_request_handle);
    literllm_default_client_free(client);
}

void test_smoke_rerank_with_top_n(void) {
    /* Reranking with top_n parameter to limit results */
    LITERLLMRerankRequest* rerank_request_handle = literllm_rerank_request_from_json("{\"documents\":[\"Python is a programming language.\",\"Cats are cute animals.\",\"Python was created by Guido van Rossum.\",\"The sun is a star.\"],\"model\":\"rerank-v3.5\",\"query\":\"What is Python?\",\"top_n\":2}");
    assert(rerank_request_handle != NULL && "failed to build request");
    const char* mock_base = getenv("MOCK_SERVER_URL");
    assert(mock_base != NULL && "MOCK_SERVER_URL must be set");
    char base_url[1024];
    snprintf(base_url, sizeof(base_url), "%s/fixtures/smoke_rerank_with_top_n", mock_base);
    LITERLLMDefaultClient* client = literllm_create_client("test-key", base_url, 0, 0, NULL);
    assert(client != NULL && "failed to create client");
    LITERLLMRerankResponse* result = literllm_default_client_rerank(client, rerank_request_handle);
    assert(result != NULL && "expected call to succeed");
    char* results = literllm_rerank_response_results(result);
    char* results_json = literllm_rerank_response_results(result);
    assert(results_json != NULL);
    char* results_0_relevance_score = alef_json_get_string(results_json, "0");
    {
        /* count_equals: count elements in array */
        assert(results != NULL && "expected non-null collection JSON");
        int elem_count = alef_json_array_count(results);
        assert(elem_count == 2 && "expected 2 elements");
    }
    assert(results_0_relevance_score != NULL && atof(results_0_relevance_score) > 0.9 && "expected greater than");
    literllm_free_string(results);
    free(results_0_relevance_score);
    literllm_free_string(results_json);
    literllm_rerank_response_free(result);
    literllm_rerank_request_free(rerank_request_handle);
    literllm_default_client_free(client);
}
