// DO NOT EDIT - auto-generated by alef
// alef:hash:3fb07515ba02077671946cad7f111c0c7840343537bb31d1488bc316651dca95
package io.xberg.literllm;

/**
 * `status` preserves the exact HTTP status code received (401 or 403).
 */
public class AuthenticationException extends LiterLlmErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new AuthenticationException with the given message. */
    public AuthenticationException(final String message) {
        super(message);
    }

    /** Creates a new AuthenticationException with the given message and cause. */
    public AuthenticationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
