// DO NOT EDIT - auto-generated by alef
// alef:hash:07df79b06f7f819edf0c1dae372b6a8759219fcce15a13259868b5ce5ffdc9b7
package io.xberg.literllm;

/** Exception for BudgetExceededException. */
public class BudgetExceededException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new BudgetExceededException with the given message. */
  public BudgetExceededException(final String message) {
    super(message);
  }

  /** Creates a new BudgetExceededException with the given message and cause. */
  public BudgetExceededException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
