// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:43b77fe87feffdf58bb80f1d37f77f01c0f5bd65dc381a68cc8825f11a95ff9b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.literllm;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Chat completion response from the API.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ChatCompletionResponse.Builder.class)
public record ChatCompletionResponse(
    @JsonProperty("id") String id,
    @JsonProperty("object") String object,
    @JsonProperty("created") long created,
    @JsonProperty("model") String model,
    @JsonProperty("choices") List<Choice> choices,
    @Nullable @JsonProperty("usage") Usage usage,
    @Nullable @JsonProperty("system_fingerprint") String systemFingerprint,
    @Nullable @JsonProperty("service_tier") String serviceTier
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for ChatCompletionResponse deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        private String id;
        private String object;
        private long created;
        private String model;
        private List<Choice> choices = List.of();
        @Nullable private Usage usage;
        @JsonProperty("system_fingerprint")
        @Nullable private String systemFingerprint;
        @JsonProperty("service_tier")
        @Nullable private String serviceTier;

        /** Sets the id field. */
        @JsonProperty("id")
        public Builder withId(final String value) {
            this.id = value;
            return this;
        }

        /** Sets the object field. */
        @JsonProperty("object")
        public Builder withObject(final String value) {
            this.object = value;
            return this;
        }

        /** Sets the created field. */
        @JsonProperty("created")
        public Builder withCreated(final long value) {
            this.created = value;
            return this;
        }

        /** Sets the model field. */
        @JsonProperty("model")
        public Builder withModel(final String value) {
            this.model = value;
            return this;
        }

        /** Sets the choices field. */
        @JsonProperty("choices")
        public Builder withChoices(final List<Choice> value) {
            this.choices = value;
            return this;
        }

        /** Sets the usage field. */
        @JsonProperty("usage")
        public Builder withUsage(final @Nullable Usage value) {
            this.usage = value;
            return this;
        }

        /** Sets the systemFingerprint field. */
        @JsonProperty("system_fingerprint")
        public Builder withSystemFingerprint(final @Nullable String value) {
            this.systemFingerprint = value;
            return this;
        }

        /** Sets the serviceTier field. */
        @JsonProperty("service_tier")
        public Builder withServiceTier(final @Nullable String value) {
            this.serviceTier = value;
            return this;
        }

        /** Constructs a ChatCompletionResponse instance from the builder's current state. */
        public ChatCompletionResponse build() {
            return new ChatCompletionResponse(
                id,
                object,
                created,
                model,
                choices,
                usage,
                systemFingerprint,
                serviceTier
            );
        }
    }
    // CPD-ON
}
