// DO NOT EDIT - auto-generated by alef
// alef:hash:12ba226655dd71043ff98454d0da03d9d72e6a16c135bd7421fb9a2b83defb7d
package io.xberg.literllm;

/** Exception for ContentPolicyException. */
public class ContentPolicyException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ContentPolicyException with the given message. */
  public ContentPolicyException(final String message) {
    super(message);
  }

  /** Creates a new ContentPolicyException with the given message and cause. */
  public ContentPolicyException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
