// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7944d9976ed5e784d58bb60b20a64df43c6faa98460b1282aa94dfadc636b045
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Result of decoding a {@code data:} URL — MIME type and the decoded byte payload.
 *
 * Named struct (rather than a tuple) so polyglot bindings can extract
 * {@code decode_data_url} with a typed return rather than a sanitized scalar.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DecodedDataUrl.Builder.class)
public record DecodedDataUrl(
    @JsonProperty("mime") String mime,
    @JsonSerialize(using = ByteArraySerializer.class) @JsonProperty("data") byte[] data
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for DecodedDataUrl deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        private String mime;
        private byte[] data = new byte[0];

        /** Sets the mime field. */
        @JsonProperty("mime")
        public Builder withMime(final String value) {
            this.mime = value;
            return this;
        }

        /** Sets the data field. */
        @JsonProperty("data")
        public Builder withData(final byte[] value) {
            this.data = value;
            return this;
        }

        /** Constructs a DecodedDataUrl instance from the builder's current state. */
        public DecodedDataUrl build() {
            return new DecodedDataUrl(
                mime,
                data
            );
        }
    }
    // CPD-ON
}
