// DO NOT EDIT - auto-generated by alef
// alef:hash:614a9a228c315e2e022431f3529f2dc8acdbb8c9b89123fe631385dfe0d5ad5f
package io.xberg.literllm;

/** Exception for HookRejectedException. */
public class HookRejectedException extends LiterLlmErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new HookRejectedException with the given message. */
    public HookRejectedException(final String message) {
        super(message);
    }

    /** Creates a new HookRejectedException with the given message and cause. */
    public HookRejectedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
