// DO NOT EDIT - auto-generated by alef
// alef:hash:a2643c3023f0f24a705285bb57661b14e33e1ff0fc1ec27e229d40f9b7d39691
package io.xberg.literllm;

/**
 * A different request body was submitted for an existing `Idempotency-Key`.
 *
 * Per the OpenAI `Idempotency-Key` convention, once a key is used with a
 * particular request body, subsequent requests using the same key must carry
 * an identical body.  A body mismatch is a hard error (not retryable).
 *
 * HTTP equivalent: 409 Conflict.
 */
public class IdempotencyConflictException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new IdempotencyConflictException with the given message. */
  public IdempotencyConflictException(final String message) {
    super(message);
  }

  /** Creates a new IdempotencyConflictException with the given message and cause. */
  public IdempotencyConflictException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
