// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b34f5dac0a6af082b71cab3b75e126050fd38402a73d6d3ff06130b6fe7d8875
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.literllm;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * A single reranked document with its relevance score.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = RerankResult.Builder.class)
public record RerankResult(
    @JsonProperty("index") int index,
    @JsonProperty("relevance_score") double relevanceScore,
    @Nullable @JsonProperty("document") RerankResultDocument document
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for RerankResult deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        private int index;
        @JsonProperty("relevance_score")
        private double relevanceScore;
        @Nullable private RerankResultDocument document;

        /** Sets the index field. */
        @JsonProperty("index")
        public Builder withIndex(final int value) {
            this.index = value;
            return this;
        }

        /** Sets the relevanceScore field. */
        @JsonProperty("relevance_score")
        public Builder withRelevanceScore(final double value) {
            this.relevanceScore = value;
            return this;
        }

        /** Sets the document field. */
        @JsonProperty("document")
        public Builder withDocument(final @Nullable RerankResultDocument value) {
            this.document = value;
            return this;
        }

        /** Constructs a RerankResult instance from the builder's current state. */
        public RerankResult build() {
            return new RerankResult(
                index,
                relevanceScore,
                document
            );
        }
    }
    // CPD-ON
}
