// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8c6394307ee786542760e258bcc70a27da623ca905384e09eb87f8ddb8d7e534
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.literllm;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import java.util.Map;

/**
 * A tool available for the response request.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ResponseTool.Builder.class)
public record ResponseTool(
    @JsonProperty("type") String toolType,
    @com.fasterxml.jackson.annotation.JsonAnyGetter Map<String, Object> config) {
  /** Creates a new Builder for constructing instances of this record. */
  public static Builder builder() {
    return new Builder();
  }

  // CPD-OFF
  /** Jackson builder for ResponseTool deserialization. */
  @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
  @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
  public static final class Builder {

    @JsonProperty("type")
    private String toolType;

    private Map<String, Object> config = new java.util.HashMap<>();

    /** Sets the toolType field. */
    @JsonProperty("type")
    public Builder withToolType(final String value) {
      this.toolType = value;
      return this;
    }

    /** Sets the config field. */
    @com.fasterxml.jackson.annotation.JsonIgnore
    public Builder withConfig(final Map<String, Object> value) {
      this.config = value;
      return this;
    }

    /** Absorbs unknown sibling fields (serde flatten). */
    @com.fasterxml.jackson.annotation.JsonAnySetter
    public Builder configEntry(final String key, final Object value) {
      this.config.put(key, value);
      return this;
    }

    /** Constructs a ResponseTool instance from the builder's current state. */
    public ResponseTool build() {
      return new ResponseTool(toolType, config);
    }
  }
  // CPD-ON
}
