// DO NOT EDIT - auto-generated by alef
// alef:hash:c7947a41084f71e69944233535fbeda5cd13b37144078f1895b6b57a7802d3fe
package io.xberg.literllm;

/**
 * `status` preserves the exact HTTP status code received (500, or other 5xx not covered
 * by `ServiceUnavailable`).
 */
public class ServerErrorException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ServerErrorException with the given message. */
  public ServerErrorException(final String message) {
    super(message);
  }

  /** Creates a new ServerErrorException with the given message and cause. */
  public ServerErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
