// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d954bd0ab4851664242c5d5bf76bcc6f4c84e06fe6cd42e3effba8a0bb5c3dcf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.literllm;

import java.lang.foreign.MemorySegment;

/**
 * The value broadcast from a singleflight leader to all followers.
 *
 * The error value is shared so every follower receives the same upstream
 * failure without cloning the underlying error.
 */
@SuppressWarnings("PMD")
public class SingleflightResult implements AutoCloseable {
    private final MemorySegment handle;

    SingleflightResult(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }
    @Override
    @SuppressWarnings("PMD.AvoidCatchingGenericException")
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.LITERLLM_SINGLEFLIGHT_RESULT_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free SingleflightResult: " + e.getMessage(), e);
            }
        }
    }
}
