// DO NOT EDIT - auto-generated by alef
// alef:hash:1c1a4f40437bd3664405b1b60a53b4dc867f8b6f298baac7d0bf32a63ff9e517
package io.xberg.literllm;

/**
 * A catch-all for errors that occur during streaming response processing.
 *
 * This variant covers multiple sub-conditions including UTF-8 decoding
 * failures, CRC/checksum mismatches (AWS EventStream), JSON parse errors
 * in individual SSE chunks, and buffer overflow conditions.  The `message`
 * field contains a human-readable description of the specific failure.
 */
public class StreamingException extends LiterLlmErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new StreamingException with the given message. */
  public StreamingException(final String message) {
    super(message);
  }

  /** Creates a new StreamingException with the given message and cause. */
  public StreamingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
