// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b34f5dac0a6af082b71cab3b75e126050fd38402a73d6d3ff06130b6fe7d8875
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package io.xberg.literllm.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.literllm.LiterLlm;
import io.xberg.literllm.ChatCompletionRequest;
import java.util.Optional;
import io.xberg.literllm.JsonUtil;

/** E2e tests for category: configuration. */
public class ConfigurationTest {

    @Test
    void testCustomBaseUrl() throws Exception {
        // Client configured with a custom base URL routes all requests to that endpoint
        var request = JsonUtil.fromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"local-model\"}", ChatCompletionRequest.class);

        String mockServerUrl = System.getProperty("mockServerUrl"); if (mockServerUrl == null) { mockServerUrl = System.getenv("MOCK_SERVER_URL"); } String mockUrl = (mockServerUrl != null ? mockServerUrl : "http://localhost:8000") + "/fixtures/custom_base_url";
        var client = LiterLlm.createClient("test-key", mockUrl, null, null, null);
        var result = client.chat(request);
        assertEquals(1, result.choices().size(), "expected exactly 1 elements");assertEquals("Hi there!", java.util.Optional.ofNullable(result.choices().get(0).message().content()).map(v -> v.text()).orElse("").trim());assertEquals("stop", java.util.Optional.ofNullable(result.choices().get(0).finishReason()).map(v -> v.getValue()).orElse("").trim());assertEquals("local-model", result.model().trim());

    }


    @Test
    void testExtraHeaders() throws Exception {
        // Client configured with extra custom headers successfully completes a chat request
        var request = JsonUtil.fromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"gpt-4\"}", ChatCompletionRequest.class);

        String mockServerUrl = System.getProperty("mockServerUrl"); if (mockServerUrl == null) { mockServerUrl = System.getenv("MOCK_SERVER_URL"); } String mockUrl = (mockServerUrl != null ? mockServerUrl : "http://localhost:8000") + "/fixtures/extra_headers";
        var client = LiterLlm.createClient("test-key", mockUrl, null, null, null);
        var result = client.chat(request);
        assertEquals(1, result.choices().size(), "expected exactly 1 elements");assertEquals("stop", java.util.Optional.ofNullable(result.choices().get(0).finishReason()).map(v -> v.getValue()).orElse("").trim());

    }


    @Test
    void testLocalProviderLlamacpp() throws Exception {
        // llamacpp local provider routes requests via llamacpp/ model prefix with no auth
        var request = JsonUtil.fromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"llamacpp/my-model\"}", ChatCompletionRequest.class);

        String mockServerUrl = System.getProperty("mockServerUrl"); if (mockServerUrl == null) { mockServerUrl = System.getenv("MOCK_SERVER_URL"); } String mockUrl = (mockServerUrl != null ? mockServerUrl : "http://localhost:8000") + "/fixtures/local_provider_llamacpp";
        var client = LiterLlm.createClient("test-key", mockUrl, null, null, null);
        var result = client.chat(request);
        assertEquals(1, result.choices().size(), "expected exactly 1 elements");assertEquals("Hi there! I'm running locally.", java.util.Optional.ofNullable(result.choices().get(0).message().content()).map(v -> v.text()).orElse("").trim());assertEquals("stop", java.util.Optional.ofNullable(result.choices().get(0).finishReason()).map(v -> v.getValue()).orElse("").trim());assertEquals("my-model", result.model().trim());

    }


    @Test
    void testLocalProviderOllama() throws Exception {
        // Ollama local provider routes requests via ollama/ model prefix with no auth
        var request = JsonUtil.fromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"ollama/qwen2:0.5b\"}", ChatCompletionRequest.class);

        String mockServerUrl = System.getProperty("mockServerUrl"); if (mockServerUrl == null) { mockServerUrl = System.getenv("MOCK_SERVER_URL"); } String mockUrl = (mockServerUrl != null ? mockServerUrl : "http://localhost:8000") + "/fixtures/local_provider_ollama";
        var client = LiterLlm.createClient("test-key", mockUrl, null, null, null);
        var result = client.chat(request);
        assertEquals(1, result.choices().size(), "expected exactly 1 elements");assertEquals("Hello! How can I help you today?", java.util.Optional.ofNullable(result.choices().get(0).message().content()).map(v -> v.text()).orElse("").trim());assertEquals("stop", java.util.Optional.ofNullable(result.choices().get(0).finishReason()).map(v -> v.getValue()).orElse("").trim());assertEquals("qwen2:0.5b", result.model().trim());

    }


    @Test
    void testLocalProviderVllm() throws Exception {
        // vLLM local provider routes requests via vllm/ model prefix with no auth
        var request = JsonUtil.fromJson("{\"messages\":[{\"content\":\"Hello\",\"role\":\"user\"}],\"model\":\"vllm/meta-llama/Llama-3.2-1B\"}", ChatCompletionRequest.class);

        String mockServerUrl = System.getProperty("mockServerUrl"); if (mockServerUrl == null) { mockServerUrl = System.getenv("MOCK_SERVER_URL"); } String mockUrl = (mockServerUrl != null ? mockServerUrl : "http://localhost:8000") + "/fixtures/local_provider_vllm";
        var client = LiterLlm.createClient("test-key", mockUrl, null, null, null);
        var result = client.chat(request);
        assertEquals(1, result.choices().size(), "expected exactly 1 elements");assertEquals("Hello! How may I assist you?", java.util.Optional.ofNullable(result.choices().get(0).message().content()).map(v -> v.text()).orElse("").trim());assertEquals("stop", java.util.Optional.ofNullable(result.choices().get(0).finishReason()).map(v -> v.getValue()).orElse("").trim());assertEquals("meta-llama/Llama-3.2-1B", result.model().trim());

    }

}
