// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1c2da475a93d435187a14de8098d1aaee2346f1e3199d84696805e5f6265736b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// ignore_for_file: unused_local_variable

import 'package:test/test.dart';
import 'dart:io';
import 'package:liter_llm/liter_llm.dart';
import 'package:liter_llm/src/liter_llm_bridge_generated/frb_generated.dart' show RustLib;
import 'dart:async';
import 'dart:convert';

// E2e tests for category: contract

String _alefE2eText(Object? value) {
  if (value == null) return '';
  // Check if it's an enum by examining its toString representation.
  final str = value.toString();
  if (str.contains('.')) {
    // Enum.toString() returns 'EnumName.variantName'. Extract the variant name.
    final parts = str.split('.');
    if (parts.length == 2) {
      final variantName = parts[1];
      // Convert camelCase variant names to snake_case for serde compatibility.
      // E.g. 'toolCalls' -> 'tool_calls', 'stop' -> 'stop'.
      return _camelToSnake(variantName);
    }
  }
  return str;
}

String _camelToSnake(String camel) {
  final buffer = StringBuffer();
  for (int i = 0; i < camel.length; i++) {
    final char = camel[i];
    if (char.contains(RegExp(r'[A-Z]'))) {
      if (i > 0) buffer.write('_');
      buffer.write(char.toLowerCase());
    } else {
      buffer.write(char);
    }
  }
  return buffer.toString();
}

Process? _sutProcess;
String? _spawnedSutUrl;

String _sutUrl() => _spawnedSutUrl ?? Platform.environment['MOCK_SERVER_URL'] ?? Platform.environment['SUT_URL'] ?? 'http://localhost:8008';

void main() {
  setUpAll(() async {
    await RustLib.init();
    if (Platform.environment['MOCK_SERVER_URL'] == null && Platform.environment['SUT_URL'] == null) {
      final _harness = Platform.script.resolve('../app_harness.dart').toFilePath();
      if (File(_harness).existsSync()) {
        _sutProcess = await Process.start('dart', ['run', _harness], mode: ProcessStartMode.normal);
        final _ready = Completer<void>();
        _sutProcess!.stdout
            .transform(utf8.decoder)
            .transform(const LineSplitter())
            .listen((_line) {
          final _trimmed = _line.trim();
          if (_trimmed.startsWith('SUT_URL=')) {
            _spawnedSutUrl = _trimmed.substring('SUT_URL='.length);
            if (!_ready.isCompleted) _ready.complete();
          }
        }, onDone: () {
          if (!_ready.isCompleted) _ready.complete();
        });
        await _ready.future.timeout(const Duration(seconds: 15), onTimeout: () {});
      }
    }
  });

  tearDownAll(() async {
    RustLib.dispose();
    final proc = _sutProcess;
    if (proc != null) {
      proc.kill();
      await proc.exitCode;
    }
  });

  test('Verify all bindings expose the full API surface — constructor accepts all config options and every method exists', () async {
    final _request = await createChatCompletionRequestFromJson(json: '{"messages":[{"content":"Contract test","role":"user"}],"model":"openai/gpt-4o"}');
    final _mockUrl = "${_sutUrl()}/fixtures/binding_api_parity";
        final _client = await LiterLlmBridge.createClient('test-key', baseUrl: _mockUrl);
    final result = await _client.chat(req: _request);
    expect(result.choices.length, equals(1));
    expect(result.choices[0].message.content.toString().trim(), equals('OK'.toString().trim()));
    expect(_alefE2eText(result.choices[0].finishReason).trim(), equals('stop'.toString().trim()));
    expect(result.usage?.totalTokens, equals(6));
    expect(result.model.toString().trim(), equals('gpt-4o'.toString().trim()));
  });

  test('Verify ocr() method exists in all bindings', () async {
    final _request = await createOcrRequestFromJson(json: '{"document":{"type":"document_url","url":"https://example.com/contract-test.pdf"},"model":"mistral/mistral-ocr-latest"}');
    final _mockUrl = "${_sutUrl()}/fixtures/contract_ocr";
        final _client = await LiterLlmBridge.createClient('test-key', baseUrl: _mockUrl);
    final result = await _client.ocr(req: _request);
  });

  test('Verify search() method exists in all bindings', () async {
    final _request = await createSearchRequestFromJson(json: '{"model":"brave/web-search","query":"contract test query"}');
    final _mockUrl = "${_sutUrl()}/fixtures/contract_search";
        final _client = await LiterLlmBridge.createClient('test-key', baseUrl: _mockUrl);
    final result = await _client.search(req: _request);
  });

}
