// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2f76943b83094bcb60a373ebb5c500743e498cc07bea253060aeb8c5d67a6ee1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// ignore_for_file: unused_local_variable

import 'package:test/test.dart';
import 'dart:io';
import 'package:liter_llm/liter_llm.dart';
import 'package:liter_llm/src/liter_llm_bridge_generated/frb_generated.dart' show RustLib;

// E2e tests for category: contract
void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test('Verify all bindings expose the full API surface — constructor accepts all config options and every method exists', () async {
    final _request = await createChatCompletionRequestFromJson(json: '{"messages":[{"content":"Contract test","role":"user"}],"model":"openai/gpt-4o"}');
    final _mockUrl = "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/binding_api_parity";
        final _client = await LiterLlmBridge.createClient('test-key', baseUrl: _mockUrl);
    final result = await _client.chat(req: _request);
    expect(result.choices.length, equals(1));
    expect(result.choices[0].message.content.toString().trim(), equals('OK'.toString().trim()));
    expect(result.choices[0].finishReason.toString().trim(), equals('stop'.toString().trim()));
    expect(result.usage?.totalTokens, equals(6));
    expect(result.model.toString().trim(), equals('gpt-4o'.toString().trim()));
  });

  test('Verify ocr() method exists in all bindings', () async {
    final _request = await createOcrRequestFromJson(json: '{"document":{"type":"document_url","url":"https://example.com/contract-test.pdf"},"model":"mistral/mistral-ocr-latest"}');
    final _mockUrl = "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/contract_ocr";
        final _client = await LiterLlmBridge.createClient('test-key', baseUrl: _mockUrl);
    final result = await _client.ocr(req: _request);
  });

  test('Verify search() method exists in all bindings', () async {
    final _request = await createSearchRequestFromJson(json: '{"model":"brave/web-search","query":"contract test query"}');
    final _mockUrl = "${Platform.environment["MOCK_SERVER_URL"] ?? "http://localhost:8080"}/fixtures/contract_search";
        final _client = await LiterLlmBridge.createClient('test-key', baseUrl: _mockUrl);
    final result = await _client.search(req: _request);
  });

}
