// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a2b07c7a24747fe5cff6e84e8a30ff1da5e80432b31c373d87bc4c64072efcc2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: cache
package e2e_test

import (
	"encoding/json"
	"os"
	"testing"

	pkg "github.com/kreuzberg-dev/liter-llm/packages/go"
)

func Test_CacheHit(t *testing.T) {
	// Tests that identical chat requests return cached response
	var request pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}`), &request); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/cache_hit"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Chat(request)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	// skipped: field 'cache_hit' not available on result type
}

func Test_CacheMissTtl(t *testing.T) {
	// Tests that cache expires after TTL
	var request pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"Hello","role":"user"}],"model":"gpt-4"}`), &request); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/cache_miss_ttl"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Chat(request)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	// skipped: field 'cache_hit' not available on result type
}

func Test_CacheOpendalMemory(t *testing.T) {
	// Cache hit with OpenDAL memory backend returns cached response on repeat request
	var request pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"Hello","role":"user"}],"model":"openai/gpt-4o"}`), &request); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/cache_opendal_memory"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Chat(request)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	// skipped: field 'cache_hit' not available on result type
}

func Test_CacheStreamBypass(t *testing.T) {
	// Tests that streaming requests bypass cache entirely
	t.Skip("non-HTTP fixture: Go binding does not expose a callable for the configured `[e2e.call]` function")
}
