// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:544145d38a17c86a338329f4f36991d632f5d42983b9f720f380351b27bb928e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: contract
package e2e_test

import (
	"encoding/json"
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"

	pkg "github.com/kreuzberg-dev/liter-llm/packages/go"
)

func Test_BindingApiParity(t *testing.T) {
	// Verify all bindings expose the full API surface — constructor accepts all config options and every method exists
	var request pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"Contract test","role":"user"}],"model":"openai/gpt-4o"}`), &request); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/binding_api_parity"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	result, err := client.Chat(request)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var choices0MessageContent string
	if result.Choices[0].Message.Content != nil {
		choices0MessageContent = string(*result.Choices[0].Message.Content)
	}
	var choices0FinishReason string
	if result.Choices[0].FinishReason != nil {
		choices0FinishReason = string(*result.Choices[0].FinishReason)
	}
	assert.Equal(t, len(result.Choices), 1, "expected exactly 1 elements")
	if strings.TrimSpace(string(choices0MessageContent)) != `OK` {
		t.Errorf("equals mismatch: got %v", choices0MessageContent)
	}
	if strings.TrimSpace(string(choices0FinishReason)) != `stop` {
		t.Errorf("equals mismatch: got %v", choices0FinishReason)
	}
	if result.Usage != nil {
		if result.Usage.TotalTokens != 6 {
			t.Errorf("equals mismatch: got %v", result.Usage.TotalTokens)
		}
	}
	if strings.TrimSpace(string(result.Model)) != `gpt-4o` {
		t.Errorf("equals mismatch: got %v", result.Model)
	}
}

func Test_ContractOcr(t *testing.T) {
	// Verify ocr() method exists in all bindings
	var request pkg.OcrRequest
	if err := json.Unmarshal([]byte(`{"document":{"type":"document_url","url":"https://example.com/contract-test.pdf"},"model":"mistral/mistral-ocr-latest"}`), &request); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/contract_ocr"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Ocr(request)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ContractSearch(t *testing.T) {
	// Verify search() method exists in all bindings
	var request pkg.SearchRequest
	if err := json.Unmarshal([]byte(`{"model":"brave/web-search","query":"contract test query"}`), &request); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/contract_search"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Search(request)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
