// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:797e09398ae0b95dd0e3de94d7374eedafcd20d08532c7cf378cbcd09e3083a7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: custom_provider
package e2e_test

import (
	"encoding/json"
	"os"
	"testing"

	pkg "github.com/kreuzberg-dev/liter-llm/packages/go"
)

func Test_ProviderAuth(t *testing.T) {
	// Tests custom provider with custom auth header
	var request pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"Hello","role":"user"}],"model":"my-auth-model-v1"}`), &request); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/provider_auth"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Chat(request)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_RegisterProvider(t *testing.T) {
	// Tests that a custom provider can be registered and routes requests
	var request pkg.ChatCompletionRequest
	if err := json.Unmarshal([]byte(`{"messages":[{"content":"Hello","role":"user"}],"model":"my-model-v1"}`), &request); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	mockURL := os.Getenv("MOCK_SERVER_URL") + "/fixtures/register_provider"
	client, clientErr := pkg.CreateClient("test-key", &mockURL, nil, nil, nil)
	if clientErr != nil {
		t.Fatalf("create client failed: %v", clientErr)
	}
	_, err := client.Chat(request)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
